(() => {
'use strict';
const WORKER_URL='https://cvstudio-contacto.cvpro-duccionesar.workers.dev';
const db=window.cvstudioSupabase,$=id=>document.getElementById(id);
const box=$('paymentOrders'),stats=$('paymentStats'),message=$('paymentPanelMessage'),search=$('paymentSearch'),paymentFilter=$('paymentStatusFilter'),orderFilter=$('orderStatusFilter'),dateFilter=$('paymentDateFilter'),refresh=$('refreshPayments'),pricesBox=$('servicePrices');
let orders=[],products=[],loaded=false;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const normalizePaymentStatus=v=>{const x=String(v||'').toLowerCase();if(['pending','pendiente','in_process','in_mediation','authorized'].includes(x))return 'pending';if(x==='approved')return 'approved';if(['rejected','cancelled','cancelado','refunded','charged_back','error_preferencia'].includes(x))return x;return x||'pending';};
const paymentLabel=v=>{const x=normalizePaymentStatus(v);return x==='approved'?'Pago aprobado':x==='pending'?'Pendiente de pago':x==='rejected'?'Pago rechazado':x==='cancelled'||x==='cancelado'?'Cancelado':x==='refunded'?'Reintegrado':x==='charged_back'?'Contracargo':x==='error_preferencia'?'Error al iniciar pago':'No aprobado';};
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
const date=v=>v?new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
async function api(action,payload={}){const {data:{session}}=await db.auth.getSession();if(!session?.access_token)throw new Error('La sesión venció.');const r=await fetch(WORKER_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||'No se pudo completar la operación.');return d;}
function dateMatches(value,filter){if(!filter)return true;const d=new Date(value),now=new Date();if(filter==='today')return d.toDateString()===now.toDateString();if(filter==='week'){const start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);return d>=start;}if(filter==='month')return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();return true;}
function filtered(){const q=search.value.trim().toLowerCase(),p=paymentFilter.value,o=orderFilter.value,df=dateFilter.value;return orders.filter(x=>(!q||[x.codigo,x.cliente_nombre,x.cliente_email,x.cliente_whatsapp,x.producto_nombre].join(' ').toLowerCase().includes(q))&&(!p||normalizePaymentStatus(x.estado_pago)===p)&&(!o||x.estado_pedido===o)&&dateMatches(x.created_at,df));}
function renderStats(){const approved=orders.filter(x=>normalizePaymentStatus(x.estado_pago)==='approved'),pending=orders.filter(x=>normalizePaymentStatus(x.estado_pago)==='pending').length;stats.innerHTML=[["Pedidos",orders.length,''],["Aprobados",approved.length,'green'],["Pendientes",pending,'yellow'],["Ingresos confirmados",money(approved.reduce((a,x)=>a+Number(x.importe||0),0)),'green']].map(([l,v,c])=>`<article class="stat ${c}"><span>${l}</span><strong>${esc(v)}</strong></article>`).join('');}
function renderEvents(events=[]){if(!events.length)return '<p class="order-history-empty">Todavía no hay movimientos adicionales.</p>';return `<ol class="order-history">${events.map(e=>`<li><span>${date(e.created_at)}</span><strong>${esc(e.description)}</strong></li>`).join('')}</ol>`;}
function render(){renderStats();const rows=filtered();box.innerHTML=rows.length?rows.map(x=>`<article class="payment-order-card" data-order-id="${esc(x.id)}"><header><div><span class="code">${esc(x.codigo)}</span><h2>${esc(x.producto_nombre)}</h2><p>${esc(x.cliente_nombre)} · ${esc(x.cliente_email)}</p></div><span class="payment-pill" data-payment="${esc(normalizePaymentStatus(x.estado_pago))}">${esc(paymentLabel(x.estado_pago))}</span></header><div class="payment-order-grid"><div><span>Importe</span><strong>${money(x.importe)}</strong></div><div><span>WhatsApp</span><a href="https://wa.me/${esc(String(x.cliente_whatsapp||'').replace(/\D/g,''))}" target="_blank">${esc(x.cliente_whatsapp)}</a></div><div><span>Medio</span><strong>${esc(x.medio_pago||'Mercado Pago · Checkout Pro')}</strong></div><div><span>Creado</span><strong>${date(x.created_at)}</strong></div>${x.mercadopago_payment_id?`<div><span>ID de pago</span><strong>${esc(x.mercadopago_payment_id)}</strong></div>`:''}${x.fecha_aprobacion?`<div><span>Aprobado</span><strong>${date(x.fecha_aprobacion)}</strong></div>`:''}</div><div class="payment-order-actions"><select data-order-state>${['Pendiente de pago','Pago recibido','En producción','Entregado','Finalizado','Cancelado'].map(v=>`<option ${x.estado_pedido===v?'selected':''}>${v}</option>`).join('')}</select><button type="button" data-save-order>Guardar estado</button><button type="button" class="secondary-button" data-copy-order>Copiar datos</button><button type="button" class="secondary-button" data-toggle-history>Ver historial</button></div><div class="order-history-panel" hidden>${renderEvents(x.events)}</div></article>`).join(''):'<div class="empty">No hay pedidos que coincidan con los filtros.</div>';
box.querySelectorAll('.payment-order-card').forEach(card=>{const x=orders.find(o=>o.id===card.dataset.orderId);card.querySelector('[data-save-order]').onclick=async()=>{const btn=card.querySelector('[data-save-order]'),estado=card.querySelector('[data-order-state]').value;btn.disabled=true;try{await api('payments-admin-update',{id:x.id,estadoPedido:estado});x.estado_pedido=estado;message.textContent=`Pedido ${x.codigo} actualizado.`;await load(false);}catch(e){message.textContent=e.message;}finally{btn.disabled=false;}};card.querySelector('[data-copy-order]').onclick=()=>navigator.clipboard.writeText(`${x.codigo}\n${x.cliente_nombre}\n${x.cliente_email}\n${x.cliente_whatsapp}\n${x.producto_nombre}\n${money(x.importe)}\nPago: ${paymentLabel(x.estado_pago)}\nPedido: ${x.estado_pedido}`);card.querySelector('[data-toggle-history]').onclick=e=>{const panel=card.querySelector('.order-history-panel');panel.hidden=!panel.hidden;e.currentTarget.textContent=panel.hidden?'Ver historial':'Ocultar historial';};});}
function renderPrices(){pricesBox.innerHTML=products.length?products.map(p=>`<article class="service-price-card" data-product-id="${esc(p.product_id)}"><div class="service-price-heading"><div><span>${esc(p.product_id)}</span><h3>${esc(p.title)}</h3></div><label class="switch-row"><input type="checkbox" data-active ${p.active!==false?'checked':''}><span>Servicio activo</span></label></div><div class="service-price-fields"><label><span>Precio comercial</span><input type="number" min="1" step="1" data-unit-price value="${Number(p.unit_price)}"></label><label><span>Precio de prueba</span><input type="number" min="1" step="1" data-test-price value="${p.test_price??''}" placeholder="Ej.: 100"></label><label class="test-mode"><input type="checkbox" data-test-mode ${p.test_mode?'checked':''}><span>Usar precio de prueba</span></label><button type="button" data-save-price>Guardar precio</button></div>${p.test_mode?'<p class="test-mode-alert">Modo prueba activo: la web y Mercado Pago usarán temporalmente este precio.</p>':''}</article>`).join(''):'<div class="empty">No se pudieron cargar los servicios.</div>';
pricesBox.querySelectorAll('.service-price-card').forEach(card=>{card.querySelector('[data-save-price]').onclick=async()=>{const btn=card.querySelector('[data-save-price]');btn.disabled=true;try{const d=await api('payments-admin-product-update',{productId:card.dataset.productId,unitPrice:card.querySelector('[data-unit-price]').value,testPrice:card.querySelector('[data-test-price]').value,testMode:card.querySelector('[data-test-mode]').checked,active:card.querySelector('[data-active]').checked});const i=products.findIndex(p=>p.product_id===card.dataset.productId);products[i]=d.product;renderPrices();message.textContent='Precio actualizado. La web utilizará el nuevo importe al recargarse.';}catch(e){message.textContent=e.message;}finally{btn.disabled=false;}};});}
async function load(showMessage=true){if(showMessage)message.textContent='Cargando pedidos y precios…';try{const [ordersData,productsData]=await Promise.all([api('payments-admin-list'),api('payments-admin-products')]);orders=ordersData.orders||[];products=productsData.products||[];loaded=true;message.textContent='';render();renderPrices();}catch(e){message.textContent=e.message;}}
document.addEventListener('cvstudio:payments-open',()=>{if(!loaded)load();});refresh?.addEventListener('click',()=>load());[search,paymentFilter,orderFilter,dateFilter].forEach(el=>el?.addEventListener(el.tagName==='INPUT'?'input':'change',render));
})();
