'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='nicky-ritmo-demo-v1';
const initial=[
 {id:'cumbia',name:'Cumbia Esencial',brand:'Korg',model:'Pa700',size:'1 GB',price:25000,art:0,description:'Una colección de ritmos inspirados en la cumbia para darle energía a tus presentaciones. Este producto, su precio y su compatibilidad son ejemplos para evaluar el diseño.'},
 {id:'folklore',name:'Folklore Vivo',brand:'Yamaha',model:'PSR-SX900',size:'1,5 GB',price:28000,art:1,description:'Una propuesta de ritmos y sonidos inspirados en el folklore. Producto ilustrativo: los estilos, contenidos y compatibilidad definitivos serán los informados por Nicky Ritmo.'},
 {id:'latino',name:'Latino Pro',brand:'Korg',model:'Pa1000',size:'1,2 GB',price:32000,art:2,description:'Texturas y ritmos latinos para explorar nuevas ideas en tu teclado. El archivo y las especificaciones son de ejemplo. Revisá el modelo compatible antes de una compra real.'},
 {id:'pop',name:'Ritmos Pop',brand:'Roland',model:'E-A7',size:'1 GB',price:24000,art:3,description:'Una selección inspirada en el pop para acompañar tus interpretaciones. Producto de demostración: el pack final y sus características serán definidos por el cliente.'}
];
function validProduct(p){return p&&typeof p.id==='string'&&typeof p.name==='string'&&typeof p.model==='string'&&['Korg','Yamaha','Roland'].includes(p.brand)&&Number.isFinite(p.price)&&p.price>=0&&p.price<=10000000&&Number.isInteger(p.art)&&p.art>=0&&p.art<=3&&typeof p.description==='string'&&typeof p.size==='string'}
function restore(){try{const d=JSON.parse(localStorage.getItem(KEY));if(!d||!Array.isArray(d.products)||!d.products.every(validProduct))return null;return{products:d.products,cart:Array.isArray(d.cart)?d.cart.filter(x=>typeof x==='string'):[],orders:Array.isArray(d.orders)?d.orders.filter(x=>x&&typeof x.id==='string'&&Array.isArray(x.products)&&x.products.every(validProduct)):[]}}catch{return null}}
let state=restore()||{products:structuredClone(initial),cart:[],orders:[]};
let editing=null,payment='Mercado Pago',audioContext=null,audioTimer=null,playing=null,toastTimer;
const money=x=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(x);
function e(tag,cls='',text=''){const n=document.createElement(tag);n.className=cls;n.textContent=text;return n}
function button(text,cls,action){const n=e('button',cls,text);n.type='button';n.addEventListener('click',action);return n}
function art(p){const n=e('div','pack-art pack-'+p.art);n.setAttribute('role','img');n.setAttribute('aria-label','Caja de '+p.name);return n}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('No se pudo guardar en este navegador. La demo sigue disponible en esta sesión.')}updateCartCount()}
function updateCartCount(){const valid=new Set(state.products.map(x=>x.id));state.cart=[...new Set(state.cart)].filter(id=>valid.has(id));$('#cartCount').textContent=state.cart.length;$('#cartButton').setAttribute('aria-label','Abrir carrito, '+state.cart.length+' productos')}
function show(selector){closeMenu();const d=$(selector);if(!d.open)d.showModal()}
function closeMenu(){$('.header nav').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false')}
function refreshModels(){const current=$('#modelFilter').value,brand=$('#brandFilter').value;$('#modelFilter').replaceChildren(new Option('Modelo',''));[...new Set(state.products.filter(p=>!brand||p.brand===brand).map(p=>p.model))].sort().forEach(m=>$('#modelFilter').add(new Option(m,m)));if([...$('#modelFilter').options].some(x=>x.value===current))$('#modelFilter').value=current}
function resetFilters(){$('#search').value='';$('#brandFilter').value='';$('#modelFilter').value='';refreshModels();renderProducts()}
function audioButton(p){const b=button('','audio-button',()=>toggleAudio(p));b.dataset.audio=p.id;b.append(e('span','play','▶'),e('span','','Escuchar demo'));b.setAttribute('aria-label','Escuchar muestra ilustrativa de '+p.name);return b}
function syncAudioButtons(){$$('[data-audio]').forEach(b=>{const on=b.dataset.audio===playing;b.classList.toggle('playing',on);b.setAttribute('aria-pressed',String(on));b.firstElementChild.textContent=on?'■':'▶';b.lastElementChild.textContent=on?'Detener muestra':'Escuchar demo'})}
async function stopAudio(){clearTimeout(audioTimer);audioTimer=null;playing=null;const c=audioContext;audioContext=null;if(c)await c.close().catch(()=>{});syncAudioButtons()}
async function toggleAudio(p){if(playing===p.id){await stopAudio();return}await stopAudio();try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return toast('Este navegador no permite la muestra de audio.');audioContext=new AudioCtx();await audioContext.resume();playing=p.id;const ctx=audioContext,t=ctx.currentTime+.06,bpm=[106,92,120,112][p.art],beat=60/bpm,notes=[[60,64,67,69],[62,65,69,67],[60,67,70,72],[60,64,69,67]][p.art];const master=ctx.createGain();master.gain.value=.13;master.connect(ctx.destination);for(let i=0;i<16;i++){const at=t+i*beat/2;const osc=ctx.createOscillator(),g=ctx.createGain();osc.type='triangle';osc.frequency.value=440*Math.pow(2,(notes[i%4]-69)/12);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.7,at+.01);g.gain.exponentialRampToValueAtTime(.001,at+beat*.65);osc.connect(g);g.connect(master);osc.start(at);osc.stop(at+beat*.7);if(i%2===0){const kick=ctx.createOscillator(),kg=ctx.createGain();kick.frequency.setValueAtTime(130,at);kick.frequency.exponentialRampToValueAtTime(45,at+.14);kg.gain.setValueAtTime(.9,at);kg.gain.exponentialRampToValueAtTime(.001,at+.2);kick.connect(kg);kg.connect(master);kick.start(at);kick.stop(at+.22)}}syncAudioButtons();toast('Muestra sintética ilustrativa · No es el audio del pack real');audioTimer=setTimeout(stopAudio,Math.ceil(beat*8*1000)+500)}catch{await stopAudio();toast('No pudimos reproducir la muestra en este navegador.')}}
function renderProducts(){const q=$('#search').value.trim().toLocaleLowerCase('es'),brand=$('#brandFilter').value,model=$('#modelFilter').value;const list=state.products.filter(p=>(!brand||p.brand===brand)&&(!model||p.model===model)&&[p.name,p.brand,p.model,p.description].join(' ').toLocaleLowerCase('es').includes(q));$('#resetFilters').hidden=!q&&!brand&&!model;$('#products').replaceChildren();$('#catalogStatus').textContent=list.length+' pack'+(list.length===1?'':'s')+' de ejemplo · Precios y compatibilidad ilustrativos';if(!list.length){const empty=e('div','empty');empty.append(e('h3','','No encontramos ese pack'),e('p','muted','Probá otra búsqueda, marca o modelo.'),button('Ver todos los packs','button secondary',resetFilters));$('#products').append(empty)}list.forEach(p=>{const c=e('article','product-card'),photo=button('','product-image',()=>openDetail(p.id));photo.setAttribute('aria-label','Ver '+p.name);photo.append(art(p));const body=e('div','product-card-body');body.append(e('h3','',p.name),e('p','compatibility','Para '+p.brand+' '+p.model),e('p','compatibility-note','Compatibilidad específica'));const price=e('div','price-row');price.append(e('strong','',money(p.price)),e('span','','Precio de ejemplo'));body.append(price,audioButton(p),button('Ver pack →','button primary full',()=>openDetail(p.id)));c.append(photo,body);$('#products').append(c)});syncAudioButtons()}
function openDetail(id){const p=state.products.find(p=>p.id===id);if(!p)return;$('#detailContent').replaceChildren();const layout=e('div','detail-layout'),photo=e('div','detail-photo'),body=e('div','detail-copy');photo.append(art(p));body.append(e('span','eyebrow blue','PACK DIGITAL · '+p.brand),e('h2','',p.name),e('p','muted',p.description));const compat=e('div','compat-box');compat.append(e('strong','','Modelo: '+p.brand+' '+p.model),e('span','','Archivo de ejemplo · '+p.size),e('span','','Este pack no se anuncia como compatible con otros teclados.'));const price=e('div','price-row');price.append(e('strong','',money(p.price)),e('span','','Precio ilustrativo'));body.append(compat,price,audioButton(p),button('Agregar al carrito →','button primary full',()=>addToCart(p.id)),e('p','muted small','Demo de propuesta · No se vende ni entrega un pack real.'));layout.append(photo,body);$('#detailContent').append(layout);show('#detailDialog');syncAudioButtons()}
function addToCart(id){if(state.cart.includes(id))return toast('Este pack ya está en tu carrito');state.cart.push(id);save();toast('Pack agregado al carrito')}
function cartProducts(){return state.cart.map(id=>state.products.find(p=>p.id===id)).filter(Boolean)}
function renderCart(){const box=$('#cartItems'),summary=$('#cartSummary');box.replaceChildren();summary.replaceChildren();summary.className='cart-summary';const products=cartProducts();if(!products.length){box.append(e('div','empty','Todavía no elegiste un pack.'),button('Explorar catálogo','button primary full',()=>{$('#cartDialog').close();goCatalog()}));return}products.forEach(p=>{const row=e('div','cart-item'),body=e('div','cart-item-body');body.append(e('h3','',p.name),e('p','',p.brand+' '+p.model),e('strong','',money(p.price)));row.append(art(p),body,button('Quitar','text-button',()=>{state.cart=state.cart.filter(x=>x!==p.id);save();renderCart()}));box.append(row)});const total=e('div','total');total.append(e('span','','Total de ejemplo'),e('strong','',money(products.reduce((s,p)=>s+p.price,0))));summary.append(total,button('Probar compra simulada →','button primary',openCheckout),e('p','small muted','Sin cobros reales. Los importes son ilustrativos.'))}
function openCheckout(){if(!cartProducts().length)return toast('Elegí un pack para probar la compra');stopAudio();$('#cartDialog').close();$('#detailDialog').close();$('#checkoutItems').replaceChildren();const total=e('div','total');total.append(e('span','',cartProducts().length+' pack'+(cartProducts().length===1?'':'s')),e('strong','',money(cartProducts().reduce((s,p)=>s+p.price,0))));$('#checkoutItems').append(total);show('#checkoutDialog')}
function simulatePayment(){const products=cartProducts();if(!products.length)return toast('El carrito está vacío');const order={id:'DEMO-'+Date.now().toString(36).toUpperCase(),date:new Date().toISOString(),payment,products:structuredClone(products)};state.orders.unshift(order);state.cart=[];save();$('#checkoutDialog').close();renderPurchases();show('#purchasesDialog');toast('Pago simulado aprobado · Descarga de prueba habilitada')}
function downloadSample(order,p){const txt=['NICKY RITMO · DEMOSTRACIÓN CVSTUDIO','', 'Este archivo acredita únicamente el recorrido de una descarga simulada.','NO contiene ritmos, sonidos ni archivos instalables para un teclado.','', 'Pack de ejemplo: '+p.name,'Compatibilidad ilustrativa: '+p.brand+' '+p.model,'Pedido de prueba: '+order.id,'', 'En la tienda definitiva, la descarga correspondería al archivo real comprado y se autorizaría después de verificar el pago desde el servidor.'].join('\n');const url=URL.createObjectURL(new Blob([txt],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Nicky-Ritmo-Demo-'+p.id.replace(/[^a-z0-9-]/gi,'').slice(0,50)+'.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Descargaste un archivo de prueba, no un pack real')}
function renderPurchases(){const list=$('#purchaseList');list.replaceChildren();$('#clearPurchases').hidden=!state.orders.length;if(!state.orders.length){const empty=e('div','empty');empty.append(e('h3','','Tu biblioteca empieza con un pack'),e('p','muted','Probá una compra simulada para ver cómo se habilitaría la descarga.'),button('Explorar catálogo','button primary',()=>{$('#purchasesDialog').close();goCatalog()}));list.append(empty);return}state.orders.forEach(order=>{const box=e('article','order'),top=e('div','order-top');top.append(e('span','',order.id+' · '+order.payment),e('span','approved','Aprobado · Simulado'));box.append(top);order.products.forEach(p=>{const row=e('div','order-product'),info=e('div');info.append(e('h3','',p.name),e('p','',p.brand+' '+p.model+' · Archivo de prueba TXT'));row.append(info,button('↓ Descargar prueba','button primary',()=>downloadSample(order,p)));box.append(row)});list.append(box)})}
function goCatalog(){closeMenu();$('#catalog').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#search').focus({preventScroll:true})}
function renderAdmin(){const list=$('#adminList');list.replaceChildren();$('#adminCount').textContent=state.products.length+' packs de ejemplo';state.products.forEach(p=>{const row=e('div','admin-row'),body=e('div','admin-row-body'),actions=e('div','admin-row-actions');body.append(e('h4','',p.name),e('p','',p.brand+' '+p.model+' · '+money(p.price)));actions.append(button('Editar','text-button',()=>editProduct(p)),button('Eliminar','text-button',()=>{if(!confirm('¿Eliminar este pack de la demo en tu navegador?'))return;state.products=state.products.filter(x=>x.id!==p.id);state.cart=state.cart.filter(x=>x!==p.id);save();refreshModels();renderProducts();renderAdmin();toast('Pack eliminado de esta demo')}));row.append(art(p),body,actions);list.append(row)})}
function editProduct(p=null){editing=p;const f=$('#productForm');f.reset();['name','brand','model','price','size','art','description'].forEach(k=>f.elements[k].value=p?.[k]??(k==='brand'?'Korg':k==='art'?'0':k==='size'?'1 GB':''));$('#editorTitle').textContent=p?'Editar pack':'Nuevo pack';$('#adminList').hidden=true;$('.admin-toolbar').hidden=true;$('#resetDemo').hidden=true;f.hidden=false;f.elements.name.focus()}
function endEdit(){$('#productForm').hidden=true;$('#adminList').hidden=false;$('.admin-toolbar').hidden=false;$('#resetDemo').hidden=false;editing=null}
const socialLinks=[
 ['Instagram','https://www.instagram.com/nicky_ritmos_argentina/','<rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.5" r="1.2"/>'],
 ['Facebook','https://web.facebook.com/keyboard.nnycck?_rdc=1&_rdr#','<path d="M14 22v-9h3l.5-4H14V7c0-1.2.4-2 2-2h2V1.5A26 26 0 0 0 15 1c-3 0-5 1.9-5 5v3H7v4h3v9Z"/>'],
 ['WhatsApp','https://api.whatsapp.com/send?phone=5491144367389','<path fill="none" stroke="currentColor" stroke-width="1.8" d="M21 11.8a9 9 0 0 1-13.2 8L2 22l1.8-5.7A9 9 0 1 1 21 11.8Z"/><path d="M8 6.5c-.7 0-1.8 1-1.8 2.3 0 3.3 4.4 7.5 7.9 7.5 1.2 0 2.4-1 2.4-1.8v-.7l-2.8-1.4-.9 1.2c-1.6-.7-3-2-3.8-3.7l1.1-.9L8.8 6.5Z"/>'],
 ['YouTube','https://www.youtube.com/@nickyritmosargentina','<path fill-rule="evenodd" d="M21.5 5.5C21 4 19 4 12 4S3 4 2.5 5.5C2 7 2 9 2 12s0 5 .5 6.5C3 20 5 20 12 20s9 0 9.5-1.5C22 17 22 15 22 12s0-5-.5-6.5ZM10 8l6 4-6 4Z"/>'],
 ['TikTok','https://www.tiktok.com/@nickyritmosargentina?is_from_webapp=1&sender_device=pc','<path d="M14 2h3c.3 2.3 1.7 3.8 4 4v3a8 8 0 0 1-4-1.1V16a6 6 0 1 1-6-6h1v3h-1a3 3 0 1 0 3 3Z"/>']
];
function socials(cls='socials'){const box=e('div',cls);socialLinks.forEach(([label,url,path])=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',label+' de Nicky Ritmo');a.title=label;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','social-icon');svg.setAttribute('aria-hidden','true');svg.innerHTML=path;a.append(svg);box.append(a)});return box}
$('footer').prepend(socials());
const contact=$('#contactDialog');const contactParagraph=contact.querySelector(':scope > p');contactParagraph.textContent='Consultá por ritmos, sonidos y compatibilidad de tu teclado. Encontrá a Nicky Ritmo en sus redes o escribile por WhatsApp.';contact.querySelector('.notice').remove();contact.insertBefore(socials('socials contact-socials'),contact.querySelector(':scope > a'));const contactButton=contact.querySelector(':scope > a');contactButton.href=socialLinks[2][1];contactButton.textContent='Consultar por WhatsApp ↗';
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{b.closest('dialog').close();stopAudio()}));$$('dialog').forEach(d=>{d.addEventListener('cancel',stopAudio);d.addEventListener('click',event=>{if(event.target!==d)return;const r=d.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom){d.close();stopAudio()}})});
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;if(action==='home'){closeMenu();window.scrollTo({top:0,behavior:'smooth'})}if(action==='catalog')goCatalog();if(action==='how')show('#howDialog');if(action==='contact')show('#contactDialog');if(action==='purchases'){renderPurchases();show('#purchasesDialog')}}));
$('#menuButton').addEventListener('click',()=>{const open=$('.header nav').classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',String(open))});$('#cartButton').addEventListener('click',()=>{renderCart();show('#cartDialog')});$('#brand').addEventListener('click',()=>{endEdit();renderAdmin();show('#adminDialog')});$('#search').addEventListener('input',renderProducts);$('#brandFilter').addEventListener('change',()=>{$('#modelFilter').value='';refreshModels();renderProducts()});$('#modelFilter').addEventListener('change',renderProducts);$('#resetFilters').addEventListener('click',resetFilters);$('#tryDemo').addEventListener('click',()=>{$('#howDialog').close();goCatalog()});$$('[data-payment]').forEach(b=>b.addEventListener('click',()=>{payment=b.dataset.payment;$$('[data-payment]').forEach(x=>x.classList.toggle('active',x===b))}));$('#simulatePayment').addEventListener('click',simulatePayment);$('#clearPurchases').addEventListener('click',()=>{if(!confirm('¿Borrar las compras de prueba de este navegador?'))return;state.orders=[];save();renderPurchases()});$('#addProduct').addEventListener('click',()=>editProduct());$('#cancelEdit').addEventListener('click',endEdit);$('#resetDemo').addEventListener('click',()=>{if(!confirm('¿Restaurar los cuatro packs de ejemplo? Se conservarán tus compras de prueba.'))return;state.products=structuredClone(initial);state.cart=[];save();resetFilters();renderAdmin();toast('Catálogo de ejemplo restaurado')});
$('#productForm').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;const p={id:editing?.id||crypto.randomUUID(),name:f.elements.name.value.trim(),brand:f.elements.brand.value,model:f.elements.model.value.trim(),price:Number(f.elements.price.value),size:f.elements.size.value.trim(),art:Number(f.elements.art.value),description:f.elements.description.value.trim()};if(!validProduct(p)||!p.name||!p.model||!p.description||!p.size)return toast('Revisá los datos del pack.');if(editing)state.products=state.products.map(x=>x.id===editing.id?p:x);else state.products.push(p);save();endEdit();refreshModels();renderProducts();renderAdmin();toast('Guardado en este navegador · No modifica la tienda real')});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudio()});refreshModels();renderProducts();updateCartCount();
