'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='nicky-ritmo-demo-v2';
const initial=[
 {id:'cumbia',name:'Cumbia Esencial',brand:'Korg',model:'Pa700',size:'1 GB',price:25000,art:0,description:'Una colección de ritmos inspirados en la cumbia para darle energía a tus presentaciones. Este producto, su precio y su compatibilidad son ejemplos para evaluar el diseño.'},
 {id:'folklore',name:'Folklore Vivo',brand:'Yamaha',model:'PSR-SX900',size:'1,5 GB',price:28000,art:1,description:'Una propuesta de ritmos y sonidos inspirados en el folklore. Producto ilustrativo: los estilos, contenidos y compatibilidad definitivos serán los informados por Nicky Ritmo.'},
 {id:'latino',name:'Latino Pro',brand:'Korg',model:'Pa1000',size:'1,2 GB',price:32000,art:2,description:'Texturas y ritmos latinos para explorar nuevas ideas en tu teclado. El archivo y las especificaciones son de ejemplo. Revisá el modelo compatible antes de una compra real.'},
 {id:'pop',name:'Ritmos Pop',brand:'Roland',model:'E-A7',size:'1 GB',price:24000,art:3,description:'Una selección inspirada en el pop para acompañar tus interpretaciones. Producto de demostración: el pack final y sus características serán definidos por el cliente.'},
 {id:'cuarteto',name:'Cuarteto Fiesta',brand:'Korg',model:'Pa5X',size:'1,3 GB',price:35000,art:4,description:'Ritmos inspirados en el cuarteto para una propuesta llena de energía. Producto y compatibilidad de ejemplo.'},
 {id:'tropical',name:'Tropical Sessions',brand:'Yamaha',model:'PSR-SX700',size:'1,1 GB',price:29000,art:5,description:'Una propuesta tropical con grooves y percusión para el escenario. Pack ilustrativo de demostración.'},
 {id:'baladas',name:'Baladas Studio',brand:'Roland',model:'E-X50',size:'1 GB',price:26000,art:6,description:'Texturas suaves y acompañamientos inspirados en baladas. El contenido y el modelo son ejemplos de la propuesta.'},
 {id:'dance',name:'Dance Evolution',brand:'Korg',model:'Pa4X',size:'1,5 GB',price:38000,art:7,description:'Una propuesta de ritmos electrónicos para explorar nuevos sonidos. Producto, precio y compatibilidad ilustrativos.'}
];
function validProduct(p){return p&&typeof p.id==='string'&&typeof p.name==='string'&&typeof p.model==='string'&&['Korg','Yamaha','Roland','Casio'].includes(p.brand)&&Number.isFinite(p.price)&&p.price>=0&&p.price<=10000000&&Number.isInteger(p.art)&&p.art>=0&&p.art<=7&&typeof p.description==='string'&&typeof p.size==='string'}
function restore(){try{const d=JSON.parse(localStorage.getItem(KEY));if(!d||!Array.isArray(d.products)||!d.products.every(validProduct))return null;return{products:d.products,cart:Array.isArray(d.cart)?d.cart.filter(x=>typeof x==='string'):[],orders:Array.isArray(d.orders)?d.orders.filter(x=>x&&typeof x.id==='string'&&Array.isArray(x.products)&&x.products.every(validProduct)):[]}}catch{return null}}
let state={products:structuredClone(initial),cart:restore()?.cart||[],orders:restore()?.orders||[]};
let editing=null,payment='Mercado Pago',audioContext=null,audioTimer=null,playing=null,toastTimer;
const productMedia=new Map(),orderMedia=new Map();let previewAudio=null,editorAudioUrl='',editingMedia={sample:null,full:null};
const money=x=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(x);
function e(tag,cls='',text=''){const n=document.createElement(tag);n.className=cls;n.textContent=text;return n}
function button(text,cls,action){const n=e('button',cls,text);n.type='button';n.addEventListener('click',action);return n}
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','icon');svg.setAttribute('aria-hidden','true');const use=document.createElementNS(svg.namespaceURI,'use');use.setAttribute('href','#'+name);svg.append(use);return svg}
function art(p){if(p.cover){const n=e('img','pack-cover');n.src=p.cover;n.alt='Portada de '+p.name;n.loading='lazy';return n}if(p.art<4){const n=e('div','pack-art pack-'+p.art);n.setAttribute('role','img');n.setAttribute('aria-label','Caja de '+p.name);return n}const n=e('div','designed-pack design-'+p.art);n.setAttribute('role','img');n.setAttribute('aria-label','Caja de '+p.name);const face=e('div','pack-face');face.append(e('span','box-brand','Nicky Ritmo'),e('strong','box-title',p.name));const visual=e('div','box-visual');visual.append(icon(p.art===7?'file':'note'));for(let i=0;i<14;i++){const bar=e('i');bar.style.setProperty('--bar',((Math.sin(i*1.9)+1)*30+15)+'%');visual.append(bar)}face.append(visual,e('span','box-category','RITMOS & SONIDOS'));n.append(e('div','pack-spine','NICKY RITMO'),face);return n}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('No se pudo guardar en este navegador. La demo sigue disponible en esta sesión.')}updateCartCount()}
function updateCartCount(){const valid=new Set(state.products.map(x=>x.id));state.cart=[...new Set(state.cart)].filter(id=>valid.has(id));$('#cartCount').textContent=state.cart.length;$('#cartButton').setAttribute('aria-label','Abrir carrito, '+state.cart.length+' productos')}
function show(selector){closeMenu();const d=$(selector);if(!d.open)d.showModal()}
function closeMenu(){$('.header nav').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false')}
function refreshModels(){const current=$('#modelFilter').value,brand=$('#brandFilter').value;$('#modelFilter').replaceChildren(new Option('Modelo',''));[...new Set(state.products.filter(p=>!brand||p.brand===brand).map(p=>p.model))].sort().forEach(m=>$('#modelFilter').add(new Option(m,m)));if([...$('#modelFilter').options].some(x=>x.value===current))$('#modelFilter').value=current}
function resetFilters(){$('#search').value='';$('#brandFilter').value='';$('#modelFilter').value='';refreshModels();renderProducts()}
function audioButton(p){const b=button('','audio-button',()=>toggleAudio(p));b.dataset.audio=p.id;const play=e('span','play');play.append(icon('play'));b.append(play,e('span','','Escuchar demo'));b.setAttribute('aria-label','Escuchar muestra ilustrativa de '+p.name);return b}
function syncAudioButtons(){$$('[data-audio]').forEach(b=>{const on=b.dataset.audio===playing;b.classList.toggle('playing',on);b.setAttribute('aria-pressed',String(on));b.firstElementChild.replaceChildren(icon(on?'stop':'play'));b.lastElementChild.textContent=on?'Detener muestra':'Escuchar demo'})}
async function stopAudio(){if(previewAudio){const a=previewAudio;previewAudio=null;a.pause();URL.revokeObjectURL(a.src);a.removeAttribute('src')}clearTimeout(audioTimer);audioTimer=null;playing=null;const c=audioContext;audioContext=null;if(c)await c.close().catch(()=>{});syncAudioButtons()}
async function toggleAudio(p){if(playing===p.id){await stopAudio();return}await stopAudio();const sample=productMedia.get(p.id)?.sample;if(sample){const a=new Audio(URL.createObjectURL(sample));previewAudio=a;try{await a.play();if(previewAudio!==a)return;playing=p.id;syncAudioButtons();a.onended=()=>{if(previewAudio===a)stopAudio()};a.ontimeupdate=()=>{if(a.currentTime>=15&&previewAudio===a)stopAudio()};audioTimer=setTimeout(stopAudio,15000);toast('Muestra del producto · Hasta 15 segundos')}catch{await stopAudio();toast('No pudimos reproducir ese audio. Probá con MP3, WAV u OGG.')}return}try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return toast('Este navegador no permite la muestra de audio.');audioContext=new AudioCtx();await audioContext.resume();playing=p.id;const ctx=audioContext,t=ctx.currentTime+.06,bpm=[106,92,120,112,132,106,78,126][p.art],beat=60/bpm,notes=[[60,64,67,69],[62,65,69,67],[60,67,70,72],[60,64,69,67]][p.art%4];const master=ctx.createGain();master.gain.value=.13;master.connect(ctx.destination);for(let i=0;i<16;i++){const at=t+i*beat/2;const osc=ctx.createOscillator(),g=ctx.createGain();osc.type='triangle';osc.frequency.value=440*Math.pow(2,(notes[i%4]-69)/12);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.7,at+.01);g.gain.exponentialRampToValueAtTime(.001,at+beat*.65);osc.connect(g);g.connect(master);osc.start(at);osc.stop(at+beat*.7);if(i%2===0){const kick=ctx.createOscillator(),kg=ctx.createGain();kick.frequency.setValueAtTime(130,at);kick.frequency.exponentialRampToValueAtTime(45,at+.14);kg.gain.setValueAtTime(.9,at);kg.gain.exponentialRampToValueAtTime(.001,at+.2);kick.connect(kg);kg.connect(master);kick.start(at);kick.stop(at+.22)}}syncAudioButtons();toast('Muestra sintética ilustrativa · No es el audio del pack real');audioTimer=setTimeout(stopAudio,Math.ceil(beat*8*1000)+500)}catch{await stopAudio();toast('No pudimos reproducir la muestra en este navegador.')}}
function renderProducts(){const q=$('#search').value.trim().toLocaleLowerCase('es'),brand=$('#brandFilter').value,model=$('#modelFilter').value;const list=state.products.filter(p=>(!brand||p.brand===brand)&&(!model||p.model===model)&&[p.name,p.brand,p.model,p.description].join(' ').toLocaleLowerCase('es').includes(q));$('#resetFilters').hidden=!q&&!brand&&!model;$('#products').replaceChildren();$('#catalogStatus').textContent=list.length+' pack'+(list.length===1?'':'s')+' de ejemplo · Precios y compatibilidad ilustrativos';if(!list.length){const empty=e('div','empty');empty.append(e('h3','','No encontramos ese pack'),e('p','muted','Probá otra búsqueda, marca o modelo.'),button('Ver todos los packs','button secondary',resetFilters));$('#products').append(empty)}list.forEach(p=>{const c=e('article','product-card'),photo=button('','product-image',()=>openDetail(p.id));photo.setAttribute('aria-label','Ver '+p.name);photo.append(art(p));const body=e('div','product-card-body');body.append(e('h3','',p.name),e('p','compatibility','Para '+p.brand+' '+p.model),e('p','compatibility-note','Compatibilidad específica'));const price=e('div','price-row');price.append(e('strong','',money(p.price)),e('span','','Precio de ejemplo'));body.append(price,audioButton(p),button('Ver pack →','button primary full',()=>openDetail(p.id)));c.append(photo,body);$('#products').append(c)});syncAudioButtons()}
function openDetail(id){const p=state.products.find(p=>p.id===id);if(!p)return;$('#detailContent').replaceChildren();const layout=e('div','detail-layout'),photo=e('div','detail-photo'),body=e('div','detail-copy');photo.append(art(p));body.append(e('span','eyebrow blue','PACK DIGITAL · '+p.brand),e('h2','',p.name),e('p','muted',p.description));const compat=e('div','compat-box');compat.append(e('strong','','Modelo: '+p.brand+' '+p.model),e('span','','Archivo de ejemplo · '+p.size),e('span','','Este pack no se anuncia como compatible con otros teclados.'));const price=e('div','price-row');price.append(e('strong','',money(p.price)),e('span','','Precio ilustrativo'));body.append(compat,price,audioButton(p),button('Agregar al carrito →','button primary full',()=>addToCart(p.id)),e('p','muted small','Demo de propuesta · No se vende ni entrega un pack real.'));layout.append(photo,body);$('#detailContent').append(layout);show('#detailDialog');syncAudioButtons()}
function addToCart(id){if(state.cart.includes(id))return toast('Este pack ya está en tu carrito');state.cart.push(id);save();toast('Pack agregado al carrito')}
function cartProducts(){return state.cart.map(id=>state.products.find(p=>p.id===id)).filter(Boolean)}
function renderCart(){const box=$('#cartItems'),summary=$('#cartSummary');box.replaceChildren();summary.replaceChildren();summary.className='cart-summary';const products=cartProducts();if(!products.length){box.append(e('div','empty','Todavía no elegiste un pack.'),button('Explorar catálogo','button primary full',()=>{$('#cartDialog').close();goCatalog()}));return}products.forEach(p=>{const row=e('div','cart-item'),body=e('div','cart-item-body');body.append(e('h3','',p.name),e('p','',p.brand+' '+p.model),e('strong','',money(p.price)));row.append(art(p),body,button('Quitar','text-button',()=>{state.cart=state.cart.filter(x=>x!==p.id);save();renderCart()}));box.append(row)});const total=e('div','total');total.append(e('span','','Total de ejemplo'),e('strong','',money(products.reduce((s,p)=>s+p.price,0))));summary.append(total,button('Probar compra simulada →','button primary',openCheckout),e('p','small muted','Sin cobros reales. Los importes son ilustrativos.'))}
function openCheckout(){if(!cartProducts().length)return toast('Elegí un pack para probar la compra');stopAudio();$('#cartDialog').close();$('#detailDialog').close();$('#checkoutItems').replaceChildren();const total=e('div','total');total.append(e('span','',cartProducts().length+' pack'+(cartProducts().length===1?'':'s')),e('strong','',money(cartProducts().reduce((s,p)=>s+p.price,0))));$('#checkoutItems').append(total);show('#checkoutDialog')}
function simulatePayment(){const products=cartProducts();if(!products.length)return toast('El carrito está vacío');const order={id:'DEMO-'+Date.now().toString(36).toUpperCase(),date:new Date().toISOString(),payment,products:structuredClone(products)};const files=new Map();products.forEach(p=>{const file=productMedia.get(p.id)?.full;if(file)files.set(p.id,file)});orderMedia.set(order.id,files);state.orders.unshift(order);state.cart=[];save();$('#checkoutDialog').close();renderPurchases();show('#purchasesDialog');toast('Pago simulado aprobado · Descarga de prueba habilitada')}
function downloadSample(order,p){const complete=orderMedia.get(order.id)?.get(p.id);if(complete){const url=URL.createObjectURL(complete),a=document.createElement('a');a.href=url;a.download=complete.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('Descarga del archivo completo seleccionado · Compra simulada');return}const txt=['NICKY RITMO · DEMOSTRACIÓN CVSTUDIO','', 'Este archivo acredita únicamente el recorrido de una descarga simulada.','NO contiene ritmos, sonidos ni archivos instalables para un teclado.','', 'Pack de ejemplo: '+p.name,'Compatibilidad ilustrativa: '+p.brand+' '+p.model,'Pedido de prueba: '+order.id,'', 'En la tienda definitiva, la descarga correspondería al archivo real comprado y se autorizaría después de verificar el pago desde el servidor.'].join('\n');const url=URL.createObjectURL(new Blob([txt],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Nicky-Ritmo-Demo-'+p.id.replace(/[^a-z0-9-]/gi,'').slice(0,50)+'.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Descargaste un archivo de prueba, no un pack real')}
function renderPurchases(){const list=$('#purchaseList');list.replaceChildren();$('#clearPurchases').hidden=!state.orders.length;if(!state.orders.length){const empty=e('div','empty');empty.append(e('h3','','Tu biblioteca empieza con un pack'),e('p','muted','Probá una compra simulada para ver cómo se habilitaría la descarga.'),button('Explorar catálogo','button primary',()=>{$('#purchasesDialog').close();goCatalog()}));list.append(empty);return}state.orders.forEach(order=>{const box=e('article','order'),top=e('div','order-top');top.append(e('span','',order.id+' · '+order.payment),e('span','approved','Aprobado · Simulado'));box.append(top);order.products.forEach(p=>{const row=e('div','order-product'),info=e('div');info.append(e('h3','',p.name),e('p','',p.brand+' '+p.model+(orderMedia.get(order.id)?.has(p.id)?' · Archivo completo de demostración':' · Archivo de prueba TXT')));const dl=button(orderMedia.get(order.id)?.has(p.id)?'Descargar archivo completo':'Descargar prueba','button primary',()=>downloadSample(order,p));dl.prepend(icon('download'));row.append(info,dl);box.append(row)});list.append(box)})}
function goCatalog(){closeMenu();$('#catalog').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#search').focus({preventScroll:true})}
const socialLinks=[
 ['Instagram','https://www.instagram.com/nicky_ritmos_argentina/','<rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.5" r="1.2"/>'],
 ['Facebook','https://web.facebook.com/keyboard.nnycck?_rdc=1&_rdr#','<path d="M14 22v-9h3l.5-4H14V7c0-1.2.4-2 2-2h2V1.5A26 26 0 0 0 15 1c-3 0-5 1.9-5 5v3H7v4h3v9Z"/>'],
 ['WhatsApp','https://api.whatsapp.com/send?phone=5491144367389','<path fill="none" stroke="currentColor" stroke-width="1.8" d="M21 11.8a9 9 0 0 1-13.2 8L2 22l1.8-5.7A9 9 0 1 1 21 11.8Z"/><path d="M8 6.5c-.7 0-1.8 1-1.8 2.3 0 3.3 4.4 7.5 7.9 7.5 1.2 0 2.4-1 2.4-1.8v-.7l-2.8-1.4-.9 1.2c-1.6-.7-3-2-3.8-3.7l1.1-.9L8.8 6.5Z"/>'],
 ['YouTube','https://www.youtube.com/@nickyritmosargentina','<path fill-rule="evenodd" d="M21.5 5.5C21 4 19 4 12 4S3 4 2.5 5.5C2 7 2 9 2 12s0 5 .5 6.5C3 20 5 20 12 20s9 0 9.5-1.5C22 17 22 15 22 12s0-5-.5-6.5ZM10 8l6 4-6 4Z"/>'],
 ['TikTok','https://www.tiktok.com/@nickyritmosargentina?is_from_webapp=1&sender_device=pc','<path d="M14 2h3c.3 2.3 1.7 3.8 4 4v3a8 8 0 0 1-4-1.1V16a6 6 0 1 1-6-6h1v3h-1a3 3 0 1 0 3 3Z"/>']
];
function socials(cls='socials'){const box=e('div',cls);socialLinks.forEach(([label,url,path])=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',label+' de Nicky Ritmo');a.title=label;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','social-icon');svg.setAttribute('aria-hidden','true');svg.innerHTML=path;a.append(svg);box.append(a)});return box}
$('footer').prepend(socials());
const contact=$('#contactDialog');const contactParagraph=contact.querySelector(':scope > p');contactParagraph.textContent='Consultá por ritmos, sonidos y compatibilidad de tu teclado. Encontrá a Nicky Ritmo en sus redes o escribile por WhatsApp.';contact.querySelector('.notice').remove();contact.insertBefore(socials('socials contact-socials'),contact.querySelector(':scope > a'));const contactButton=contact.querySelector(':scope > a');contactButton.href=socialLinks[2][1];contactButton.textContent='Consultar por WhatsApp ↗';
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{b.closest('dialog').close();stopAudio()}));$$('dialog').forEach(d=>{d.addEventListener('cancel',stopAudio);d.addEventListener('click',event=>{if(event.target!==d)return;const r=d.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom){d.close();stopAudio()}})});
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;if(action==='home'){closeMenu();window.scrollTo({top:0,behavior:'smooth'})}if(action==='catalog')goCatalog();if(action==='how')show('#howDialog');if(action==='contact')show('#contactDialog');if(action==='purchases'){renderPurchases();show('#purchasesDialog')}}));
$('#menuButton').addEventListener('click',()=>{const open=$('.header nav').classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',String(open))});$('#cartButton').addEventListener('click',()=>{renderCart();show('#cartDialog')});$('#brand').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));$('#search').addEventListener('input',renderProducts);$('#brandFilter').addEventListener('change',()=>{$('#modelFilter').value='';refreshModels();renderProducts()});$('#modelFilter').addEventListener('change',renderProducts);$('#resetFilters').addEventListener('click',resetFilters);$('#tryDemo').addEventListener('click',()=>{$('#howDialog').close();goCatalog()});$$('[data-payment]').forEach(b=>b.addEventListener('click',()=>{payment=b.dataset.payment;$$('[data-payment]').forEach(x=>x.classList.toggle('active',x===b))}));$('#simulatePayment').addEventListener('click',simulatePayment);$('#clearPurchases').addEventListener('click',()=>{if(!confirm('¿Borrar las compras de prueba de este navegador?'))return;state.orders=[];save();renderPurchases()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudio()});refreshModels();renderProducts();updateCartCount();

const API='https://eqepkoegzyqklpxkrkhm.supabase.co/functions/v1/nicky-ritmo-api';
let adminToken=sessionStorage.getItem('nicky-admin-session')||'', adminProducts=[],storeSettings=null,editingCover='',adminTab='overview',busy=false;
async function api(action,data={}){const r=await fetch(API,{method:action?'POST':'GET',headers:action?{'Content-Type':'application/json',...(adminToken?{Authorization:'Bearer '+adminToken}:{})}:{},body:action?JSON.stringify({action,...data}):undefined});const d=await r.json();if(!r.ok){if(r.status===401&&action!=='login'){adminToken='';sessionStorage.removeItem('nicky-admin-session');$('#adminDialog').close();show('#loginDialog')}throw Error(d.error||'No pudimos completar la operación.')}return d}
function applySettings(){if(!storeSettings)return;const s=storeSettings.body;const h=$('.hero h1');h.replaceChildren(document.createTextNode(s.headline),document.createElement('br'),e('span','',s.accent));const subtitle=$('.hero-copy p');subtitle.replaceChildren(...String(s.subtitle).split(/\r?\n|(?<=[.!?])\s+/).filter(Boolean).map(line=>e('span','hero-subtitle-line',line)));$('.catalog-top h2').textContent=s.catalogTitle}
function refreshBrands(){const value=$('#brandFilter').value;$('#brandFilter').replaceChildren(new Option('Marca',''));[...new Set(state.products.map(p=>p.brand))].sort().forEach(b=>$('#brandFilter').add(new Option(b,b)));$('#brandFilter').value=value}
async function loadCatalog(){try{const d=await api();if(!Array.isArray(d.products)||!d.products.every(validProduct))throw Error('Catálogo no disponible');state.products=d.products.sort((a,b)=>(a.position||0)-(b.position||0));storeSettings=d.settings;applySettings();refreshBrands();refreshModels();renderProducts();updateCartCount()}catch{toast('No pudimos actualizar el catálogo. Mostramos los packs de ejemplo.')}}
async function loadAdmin(){const d=await api('admin');adminProducts=d.products;storeSettings=d.settings;renderAdmin();return d}
async function enterAdmin(){const b=$('#adminAccess');b.disabled=true;try{if(!adminToken){$('#loginError').textContent='';show('#loginDialog');return}await loadAdmin();setAdminTab('overview');show('#adminDialog')}catch(err){toast(err.message)}finally{b.disabled=false}}
function setAdminTab(tab){$('#sampleAudioPreview').pause();adminTab=tab;$('#productForm').hidden=true;for(const [name,id] of [['overview','adminOverview'],['catalog','adminCatalog'],['settings','adminSettings'],['trash','adminTrash']])$('#'+id).hidden=name!==tab;$$('[data-admin-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.adminTab===tab);b.setAttribute('aria-current',b.dataset.adminTab===tab?'page':'false')});$('#adminTitle').textContent={overview:'Todo en armonía.',catalog:'Tu catálogo, al día.',settings:'Dale tu identidad.',trash:'Nada se pierde.'}[tab];$('#adminError').textContent='';$('.admin-main').scrollTop=0;renderAdmin();if(tab==='settings')fillSettings()}
function adminRow(p,archived=false){const row=e('div','admin-row'),body=e('div','admin-row-body'),actions=e('div','admin-row-actions');body.append(e('h4','',p.name),e('p','',p.brand+' '+p.model+' · '+money(p.price)));const badge=e('span','pill '+(p.published===false?'draft':''),p.published===false?'Borrador':'Publicado');body.append(badge);if(archived)actions.append(button('Restaurar','button secondary',()=>archiveProduct(p,true)));else{const edit=button('Editar','button secondary',()=>editProduct(p));edit.prepend(icon('edit'));const archive=button('','icon-button',()=>archiveProduct(p));archive.append(icon('trash'));archive.setAttribute('aria-label','Archivar '+p.name);actions.append(edit,archive)}row.append(art(p),body,actions);return row}
function renderAdmin(){const active=adminProducts.filter(p=>!p.archived),trash=adminProducts.filter(p=>p.archived),q=$('#adminSearch').value.toLocaleLowerCase('es');$('#adminCount').textContent=active.length+' productos';$('#adminList').replaceChildren();active.filter(p=>[p.name,p.brand,p.model].join(' ').toLocaleLowerCase('es').includes(q)).sort((a,b)=>(a.position||0)-(b.position||0)).forEach(p=>$('#adminList').append(adminRow(p)));if(!$('#adminList').children.length)$('#adminList').append(e('div','empty','No hay productos para esta búsqueda.'));$('#trashList').replaceChildren();trash.forEach(p=>$('#trashList').append(adminRow(p,true)));if(!trash.length)$('#trashList').append(e('div','empty','Tu papelera está vacía.'));$('#adminStats').replaceChildren();for(const [count,label,name] of [[active.length,'Productos','note'],[active.filter(p=>p.published!==false).length,'Publicados','grid'],[active.filter(p=>p.published===false).length,'Borradores','edit']]){const c=e('div','stat-card');c.append(icon(name),e('strong','',String(count)),e('span','',label));$('#adminStats').append(c)}}
async function archiveProduct(p,restore=false){if(busy)return;busy=true;$('#adminError').textContent='';try{await api(restore?'restore':'archive',{id:p.id,version:p.version});await loadAdmin();await loadCatalog();toast(restore?'Producto restaurado':'Producto archivado · Podés recuperarlo desde Papelera')}catch(err){$('#adminError').textContent=err.message}finally{busy=false}}
function editProduct(p=null){editing=p;editingCover=p?.cover||'';editingMedia={...(productMedia.get(p?.id)||{sample:null,full:null})};$('#sampleUpload').value='';$('#fullUpload').value='';refreshMediaEditor();const f=$('#productForm');f.reset();for(const k of ['name','brand','model','price','size','art','description','category','position'])f.elements[k].value=p?.[k]??({brand:'Korg',art:'4',size:'1 GB',category:'Ritmos',position:adminProducts.length+1}[k]||'');f.elements.published.checked=p?.published!==false;$('#editorTitle').textContent=p?'Editar producto':'Crear un nuevo pack';$$('.admin-page').forEach(x=>x.hidden=true);f.hidden=false;$('#adminError').textContent='';$('#coverUpload').value='';previewProduct();$('.admin-main').scrollTop=0;f.elements.name.focus()}
function previewProduct(){const f=$('#productForm');const p={name:f.elements.name.value.trim()||'Tu próximo pack',art:Number(f.elements.art.value),cover:editingCover};const box=$('#productPreview');box.replaceChildren(art(p),e('strong','',p.name),e('p','muted',f.elements.brand.value+' '+(f.elements.model.value||'Modelo compatible')),e('span','preview-price',money(Number(f.elements.price.value)||0)));$('#removeCover').hidden=!editingCover}
function fillSettings(){const f=$('#settingsForm');for(const k of ['headline','accent','subtitle','catalogTitle'])f.elements[k].value=storeSettings?.body[k]||'';previewSettings()}
function previewSettings(){const f=$('#settingsForm');$('#settingsPreviewTitle').replaceChildren(document.createTextNode(f.elements.headline.value),e('span','',f.elements.accent.value));$('#settingsPreviewSubtitle').textContent=f.elements.subtitle.value}
async function uploadCover(){const file=$('#coverUpload').files[0];if(!file)return;if(file.size>1048576||!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Usá JPG, PNG o WebP de hasta 1 MB');$('#coverUpload').value='';return}const controls=$$('#productForm button,#productForm input,#productForm select,#productForm textarea');controls.forEach(b=>b.disabled=true);$('#productSaveHint').textContent='Subiendo portada…';try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});const d=await api('upload',{data,mime:file.type});editingCover=d.url;previewProduct();toast('Portada cargada. Guardá el producto para publicarla.')}catch(err){toast(err.message)}finally{controls.forEach(b=>b.disabled=false);$('#productSaveHint').textContent='Los cambios se guardan en línea.'}}
$('#adminAccess').addEventListener('click',enterAdmin);
$('#togglePassword').addEventListener('click',()=>{const input=$('#loginForm').elements.password;const show=input.type==='password';input.type=show?'text':'password';$('#togglePassword').textContent=show?'Ocultar':'Ver';$('#togglePassword').setAttribute('aria-label',show?'Ocultar contraseña':'Mostrar contraseña')});
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const f=event.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;$('#loginError').textContent='';try{const d=await api('login',{username:f.elements.username.value.trim(),password:f.elements.password.value});adminToken=d.token;sessionStorage.setItem('nicky-admin-session',adminToken);f.elements.password.value='';await loadAdmin();$('#loginDialog').close();setAdminTab('overview');show('#adminDialog')}catch(err){$('#loginError').textContent=err.message}finally{b.disabled=false}});
$('#adminLogout').addEventListener('click',async()=>{try{await api('logout')}catch{}adminToken='';sessionStorage.removeItem('nicky-admin-session');$('#adminDialog').close();toast('Sesión cerrada')});
$$('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>{if(!busy)setAdminTab(b.dataset.adminTab)}));$('#adminSearch').addEventListener('input',renderAdmin);$('#addProduct').addEventListener('click',()=>editProduct());$('#overviewAdd').addEventListener('click',()=>editProduct());$('#cancelEdit').addEventListener('click',()=>setAdminTab('catalog'));$('#productForm').addEventListener('input',previewProduct);$('#coverUpload').addEventListener('change',uploadCover);$('#removeCover').addEventListener('click',()=>{editingCover='';$('#coverUpload').value='';previewProduct()});
$('#productForm').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;const f=event.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;$('#adminError').textContent='';const p={id:editing?.id,version:editing?.version,cover:editingCover,published:f.elements.published.checked};for(const k of ['name','brand','model','size','description','category'])p[k]=f.elements[k].value.trim();for(const k of ['price','art','position'])p[k]=Number(f.elements[k].value);try{const saved=await api('save',{product:p});productMedia.set(saved.product.id,{...editingMedia});await loadAdmin();await loadCatalog();setAdminTab('catalog');toast('Producto guardado en línea')}catch(err){$('#adminError').textContent=err.message}finally{busy=false;b.disabled=false}});
$('#settingsForm').addEventListener('input',previewSettings);$('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const f=event.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;const s={};for(const k of ['headline','accent','subtitle','catalogTitle'])s[k]=f.elements[k].value.trim();try{const d=await api('settings',{settings:s,revision:storeSettings.revision});storeSettings=d.settings;applySettings();toast('Configuración guardada en línea')}catch(err){$('#adminError').textContent=err.message}finally{b.disabled=false}});
loadCatalog();

function fileSize(bytes){return bytes>=1073741824?(bytes/1073741824).toFixed(2)+' GB':bytes>=1048576?(bytes/1048576).toFixed(1)+' MB':Math.ceil(bytes/1024)+' KB'}
function refreshMediaEditor(){const a=$('#sampleAudioPreview');a.pause();a.removeAttribute('src');if(editorAudioUrl){URL.revokeObjectURL(editorAudioUrl);editorAudioUrl=''}const sample=editingMedia.sample,full=editingMedia.full;$('#sampleFileInfo').textContent=sample?sample.name+' · '+fileSize(sample.size):'Todavía no elegiste una muestra.';$('#fullFileInfo').textContent=full?full.name+' · '+fileSize(full.size):'Todavía no elegiste un archivo completo.';$('#clearSample').hidden=!sample;$('#clearFull').hidden=!full;a.hidden=!sample;if(sample){editorAudioUrl=URL.createObjectURL(sample);a.src=editorAudioUrl;a.ontimeupdate=()=>{if(a.currentTime>=15){a.pause();a.currentTime=0}};a.onplay=stopAudio}}
$('#sampleUpload').addEventListener('change',()=>{const file=$('#sampleUpload').files[0];if(!file)return;if(file.size>20971520){toast('La muestra debe pesar hasta 20 MB. Usá un fragmento de unos 15 segundos.');$('#sampleUpload').value='';return}if(!file.type.startsWith('audio/')&&!/\.(mp3|wav|ogg|m4a|aac|flac)$/i.test(file.name)){toast('Elegí un archivo de audio válido.');$('#sampleUpload').value='';return}editingMedia.sample=file;refreshMediaEditor()});
$('#fullUpload').addEventListener('change',()=>{const file=$('#fullUpload').files[0];if(!file)return;editingMedia.full=file;$('#productForm').elements.size.value=fileSize(file.size);refreshMediaEditor();previewProduct()});
$('#clearSample').addEventListener('click',()=>{editingMedia.sample=null;$('#sampleUpload').value='';refreshMediaEditor()});$('#clearFull').addEventListener('click',()=>{editingMedia.full=null;$('#fullUpload').value='';refreshMediaEditor()});
$('#adminDialog').addEventListener('close',()=>$('#sampleAudioPreview').pause());
