-- CVStudio · Biblioteca modular avanzada v3
-- 18 perfiles sectoriales construidos desde 21 módulos y 90 consignas.

create table if not exists public.modulos_evaluacion (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  titulo text not null,
  categoria text not null,
  descripcion text,
  competencias text[] not null default '{}',
  preguntas jsonb not null default '[]'::jsonb check (jsonb_typeof(preguntas)='array'),
  fuentes jsonb not null default '[]'::jsonb,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table public.modulos_evaluacion enable row level security;
revoke all on table public.modulos_evaluacion from anon;
grant select,insert,update,delete on table public.modulos_evaluacion to authenticated;
drop policy if exists "Dirección administra módulos de evaluación" on public.modulos_evaluacion;
create policy "Dirección administra módulos de evaluación" on public.modulos_evaluacion
for all to authenticated
using ((select auth.uid()) in ('3a8b4d50-305a-4da5-9fde-64bd2c8ed68d'::uuid,'6a608be9-da9f-4fb6-941c-4a14ac62a865'::uuid))
with check ((select auth.uid()) in ('3a8b4d50-305a-4da5-9fde-64bd2c8ed68d'::uuid,'6a608be9-da9f-4fb6-941c-4a14ac62a865'::uuid));

insert into public.modulos_evaluacion(slug,titulo,categoria,descripcion,competencias,preguntas,fuentes) values
('razonamiento-datos','Razonamiento y análisis de datos','Núcleo','Interpretación, cálculo aplicado y toma de decisiones con información incompleta.',array['Razonamiento numérico','Interpretación de datos','Resolución de problemas'],$q$[
{"id":"rd1","module":"razonamiento-datos","dimension":"Análisis de datos","difficulty":"alta","context":"Un equipo procesó 420 casos: 168 en el turno A, 147 en el B y el resto en el C. Las incidencias fueron 4, 3 y 5 respectivamente.","text":"¿Qué turno tuvo la mayor tasa de incidencias, no la mayor cantidad absoluta?","options":[{"value":"A","label":"Turno A"},{"value":"B","label":"Turno B"},{"value":"C","label":"Turno C"},{"value":"D","label":"A y C empatan"}],"correct":"C","explanation":"C procesó 105 casos y tuvo 5 incidencias: 4,76%, superior a A y B."},
{"id":"rd2","module":"razonamiento-datos","dimension":"Razonamiento numérico","difficulty":"alta","context":"Una tarea estándar demanda 12 minutos. Tras una mejora, el tiempo baja 15%, pero se agrega un control final de 90 segundos.","text":"¿Cuál es el nuevo tiempo total por tarea?","options":[{"value":"A","label":"9 min 42 s"},{"value":"B","label":"10 min 12 s"},{"value":"C","label":"11 min 42 s"},{"value":"D","label":"12 min 30 s"}],"correct":"C"},
{"id":"rd3","module":"razonamiento-datos","dimension":"Planificación","difficulty":"alta","context":"Hay 7 horas útiles. Las tareas P, Q y R duran 110, 85 y 70 minutos. P debe hacerse antes que R. Además hay dos controles de 35 minutos y una contingencia reservada de 40 minutos.","text":"¿Qué afirmación es correcta?","options":[{"value":"A","label":"No entran todas las tareas"},{"value":"B","label":"Entran y quedan 35 minutos libres"},{"value":"C","label":"Entran y quedan 45 minutos libres"},{"value":"D","label":"Solo entran si R se realiza antes que P"}],"correct":"C"},
{"id":"rd4","module":"razonamiento-datos","dimension":"Inferencia","difficulty":"alta","context":"Todo registro validado tiene responsable identificado. Algunos registros con responsable identificado todavía no fueron auditados. El registro K fue validado.","text":"¿Qué conclusión es necesariamente válida?","options":[{"value":"A","label":"K fue auditado"},{"value":"B","label":"K tiene responsable identificado"},{"value":"C","label":"K no presenta errores"},{"value":"D","label":"K es uno de los registros no auditados"}],"correct":"B"},
{"id":"rd5","module":"razonamiento-datos","dimension":"Análisis de datos","difficulty":"media-alta","context":"Un indicador pasa de 8% a 6% y el volumen permanece estable.","text":"¿Cómo debe describirse correctamente el cambio?","options":[{"value":"A","label":"Bajó 2%"},{"value":"B","label":"Bajó 2 puntos porcentuales, equivalente a una reducción relativa del 25%"},{"value":"C","label":"Bajó 25 puntos porcentuales"},{"value":"D","label":"Mejoró 75%"}],"correct":"B"},
{"id":"rd6","module":"razonamiento-datos","dimension":"Criterio analítico","difficulty":"alta","context":"Dos informes muestran totales distintos para el mismo período. Uno fue exportado a las 10:00 y otro a las 15:00; el sistema admite actualizaciones retroactivas.","text":"¿Cuál es el primer paso más sólido?","options":[{"value":"A","label":"Usar el total mayor"},{"value":"B","label":"Promediar ambos"},{"value":"C","label":"Verificar corte, filtros, versión y movimientos incorporados entre exportaciones"},{"value":"D","label":"Descartar los dos informes"}],"correct":"C"}
]$q$::jsonb,'["https://www.onetcenter.org/content.html","https://esco.ec.europa.eu/en/classification/skill_main"]'::jsonb),
('atencion-instrucciones','Atención, precisión e instrucciones','Núcleo','Control de detalles, reglas condicionales y trazabilidad.',array['Atención selectiva','Precisión','Seguimiento de instrucciones'],$q$[
{"id":"ai1","module":"atencion-instrucciones","dimension":"Seguimiento de instrucciones","difficulty":"alta","context":"Regla: si el código comienza con R y termina en número par, va a Revisión; si contiene X, va a Excepción, aun cuando cumpla la primera regla.","text":"¿Dónde se clasifica R-31X-8?","options":[{"value":"A","label":"Revisión"},{"value":"B","label":"Excepción"},{"value":"C","label":"Archivo"},{"value":"D","label":"No puede determinarse"}],"correct":"B"},
{"id":"ai2","module":"atencion-instrucciones","dimension":"Precisión","difficulty":"alta","text":"Seleccioná la única cadena idéntica a AR7-09I1-BQ5 (la tercera posición es el número 7 y la sexta es la letra I).","options":[{"value":"A","label":"AR7-09I1-BQ5"},{"value":"B","label":"AR7-0911-BQ5"},{"value":"C","label":"A7R-09I1-BQ5"},{"value":"D","label":"AR7-09I1-8Q5"}],"correct":"A"},
{"id":"ai3","module":"atencion-instrucciones","dimension":"Control de calidad","difficulty":"alta","context":"La instrucción exige validar identidad, fecha, importe y autorización. El registro tiene identidad, fecha e importe correctos, pero la autorización está vencida.","text":"¿Qué estado corresponde?","options":[{"value":"A","label":"Aprobado porque tres campos son correctos"},{"value":"B","label":"Pendiente de regularización; no debe aprobarse"},{"value":"C","label":"Aprobado con una nota informal"},{"value":"D","label":"Eliminado sin dejar registro"}],"correct":"B"},
{"id":"ai4","module":"atencion-instrucciones","dimension":"Priorización","difficulty":"media-alta","context":"A: vence hoy y afecta seguridad. B: vence hoy y afecta un reporte interno. C: vence mañana y bloquea a un cliente. D: no vence y lleva 5 minutos.","text":"Sin otra información, ¿qué orden inicial es más defendible?","options":[{"value":"A","label":"D, B, C, A"},{"value":"B","label":"A, C, B, D"},{"value":"C","label":"B, D, A, C"},{"value":"D","label":"C, A, D, B"}],"correct":"B"},
{"id":"ai5","module":"atencion-instrucciones","dimension":"Trazabilidad","difficulty":"media-alta","context":"Descubrís que cargaste un dato incorrecto en un registro ya utilizado por otra área.","text":"¿Cuál es la respuesta más completa?","options":[{"value":"A","label":"Sobrescribirlo y no informar"},{"value":"B","label":"Crear otro registro sin relacionarlos"},{"value":"C","label":"Corregir según procedimiento, conservar trazabilidad y avisar a quienes pudieron verse afectados"},{"value":"D","label":"Esperar a que otra persona lo encuentre"}],"correct":"C"},
{"id":"ai6","module":"atencion-instrucciones","dimension":"Comprensión","difficulty":"alta","context":"Procedimiento: tomar una muestra inicial y luego una cada 45 minutos mientras la línea esté activa. La línea operó de 08:10 a 11:20 sin interrupciones.","text":"¿Cuántas muestras correspondían?","options":[{"value":"A","label":"4"},{"value":"B","label":"5"},{"value":"C","label":"6"},{"value":"D","label":"7"}],"correct":"B"}
]$q$::jsonb,'["https://www.onetcenter.org/content.html"]'::jsonb),
('criterio-entrevista','Criterio laboral y entrevista','Núcleo','Juicio situacional, comunicación, ética y respuestas con evidencia.',array['Juicio situacional','Comunicación','Autoconocimiento'],$q$[
{"id":"ce1","module":"criterio-entrevista","dimension":"Criterio laboral","difficulty":"alta","context":"Tu responsable pide acelerar una entrega. Al revisar, detectás que falta una validación obligatoria y que omitirla podría generar un error importante.","text":"¿Qué respuesta muestra mejor criterio?","options":[{"value":"A","label":"Entregar sin validar para cumplir el horario","score":0},{"value":"B","label":"Negarse sin explicar ni proponer alternativas","score":1},{"value":"C","label":"Explicar el riesgo, estimar el tiempo de validación y acordar una alternativa segura","score":3},{"value":"D","label":"Validar en secreto y avisar después si surge un problema","score":2}]},
{"id":"ce2","module":"criterio-entrevista","dimension":"Trabajo en equipo","difficulty":"alta","context":"Un compañero experimentado propone un atajo habitual que contradice el procedimiento vigente. No hubo incidentes anteriores.","text":"¿Cómo actuarías?","options":[{"value":"A","label":"Aceptar porque tiene más experiencia","score":0},{"value":"B","label":"Revisar el procedimiento con él, explicar la diferencia y escalar la duda antes de aplicarlo","score":3},{"value":"C","label":"Denunciarlo inmediatamente sin conversar","score":1},{"value":"D","label":"Aplicarlo solo esta vez y documentarlo","score":1}]},
{"id":"ce3","module":"criterio-entrevista","dimension":"Comunicación","difficulty":"media-alta","context":"Recibís dos instrucciones incompatibles de personas con autoridad similar y el plazo es corto.","text":"¿Cuál es la mejor intervención?","options":[{"value":"A","label":"Elegir una al azar y avanzar","score":0},{"value":"B","label":"Esperar hasta que se resuelva solo","score":0},{"value":"C","label":"Exponer la contradicción, el impacto y pedir una prioridad explícita dejando registro","score":3},{"value":"D","label":"Hacer parcialmente ambas sin avisar","score":1}]},
{"id":"ce4","module":"criterio-entrevista","dimension":"Integridad","difficulty":"alta","context":"Cometiste un error que todavía puede corregirse, pero informarlo podría generar una demora visible.","text":"¿Qué opción es más profesional?","options":[{"value":"A","label":"Corregirlo silenciosamente si nadie lo notó","score":1},{"value":"B","label":"Informarlo con hechos, contener el impacto y proponer la corrección","score":3},{"value":"C","label":"Atribuirlo a una falla del sistema","score":0},{"value":"D","label":"Esperar a confirmar si tendrá consecuencias","score":0}]},
{"id":"ce5","module":"criterio-entrevista","dimension":"Entrevista estructurada","difficulty":"alta","type":"text","text":"Relatá una situación real en la que tuviste que priorizar tareas bajo presión. Indicá contexto, criterios utilizados, acciones, resultado y qué cambiarías hoy.","rubric":["Contexto verificable","Criterio de prioridad","Acciones propias","Resultado","Aprendizaje"]},
{"id":"ce6","module":"criterio-entrevista","dimension":"Entrevista estructurada","difficulty":"alta","type":"text","text":"Describí un error laboral o académico del que te hayas hecho responsable. ¿Cómo lo detectaste, a quién informaste, cómo lo corregiste y qué prevención implementaste?","rubric":["Responsabilidad sin excusas","Comunicación","Corrección","Prevención"]}
]$q$::jsonb,'["https://www.siop.org/tip-article/is-cognitive-ability-the-best-predictor-of-job-performance-new-research-says-its-time-to-think-again/"]'::jsonb),

('sector-administracion','Administración y oficina','Sector','Gestión documental, conciliación, agenda y confidencialidad.',array['Administración','Organización','Confidencialidad'],$q$[
{"id":"sa1","module":"sector-administracion","dimension":"Gestión administrativa","difficulty":"alta","context":"El mayor contable y el extracto difieren. Hay un movimiento con fecha valor del día siguiente y otro duplicado en el archivo importado.","text":"¿Qué hacés antes de ajustar?","options":[{"value":"A","label":"Forzar el saldo para que coincida","score":0},{"value":"B","label":"Identificar partidas conciliatorias, validar el duplicado y documentar el ajuste autorizado","score":3},{"value":"C","label":"Eliminar ambos movimientos","score":0},{"value":"D","label":"Promediar la diferencia","score":0}]},
{"id":"sa2","module":"sector-administracion","dimension":"Confidencialidad","difficulty":"alta","context":"Una persona conocida de la empresa pide por WhatsApp una nómina con DNI y teléfonos para una tarea urgente, pero no figura como autorizada.","text":"¿Cómo respondés?","options":[{"value":"A","label":"La enviás porque pertenece a la empresa","score":0},{"value":"B","label":"Enviás solo los teléfonos","score":0},{"value":"C","label":"Verificás identidad, finalidad, autorización y canal seguro antes de compartir el mínimo necesario","score":3},{"value":"D","label":"La publicás en el grupo interno","score":0}]},
{"id":"sa3","module":"sector-administracion","dimension":"Planificación","difficulty":"alta","context":"A las 10:00 tenés: pago con corte 11:00, reunión 10:30, cliente esperando respuesta y reporte para las 16:00. El pago requiere aprobación de otra persona.","text":"¿Cuál es la primera secuencia más sólida?","options":[{"value":"A","label":"Empezar el reporte porque es más largo","score":1},{"value":"B","label":"Solicitar ya la aprobación del pago, contener al cliente y preparar la reunión","score":3},{"value":"C","label":"Atender solo al cliente hasta resolver todo","score":1},{"value":"D","label":"Esperar instrucciones","score":0}]},
{"id":"sa4","module":"sector-administracion","dimension":"Entrevista administrativa","difficulty":"alta","type":"text","text":"Explicá cómo organizarías el seguimiento de 60 trámites con distintos responsables, vencimientos y documentación pendiente para reducir olvidos y permitir auditoría."}
]$q$::jsonb,'["https://www.argentina.gob.ar/aaip/datospersonales"]'::jsonb),
('sector-atencion','Atención al cliente y call center','Sector','Escucha, diagnóstico, comunicación y resolución trazable.',array['Atención al cliente','Comunicación','Resolución de reclamos'],$q$[
{"id":"sat1","module":"sector-atencion","dimension":"Diagnóstico del reclamo","difficulty":"alta","context":"El cliente afirma que le cobraron dos veces. Ves dos autorizaciones, pero solo una está confirmada; la otra figura pendiente y puede liberarse automáticamente.","text":"¿Qué respuesta es más completa?","options":[{"value":"A","label":"Asegurar que no existe ningún problema","score":0},{"value":"B","label":"Reconocer la preocupación, explicar estados sin prometer, verificar plazos y dejar un seguimiento","score":3},{"value":"C","label":"Derivarlo al banco sin revisar","score":1},{"value":"D","label":"Devolver ambos importes inmediatamente","score":0}]},
{"id":"sat2","module":"sector-atencion","dimension":"Comunicación","difficulty":"alta","context":"Una clienta enojada interrumpe y mezcla tres problemas distintos.","text":"¿Cómo ordenás la conversación?","options":[{"value":"A","label":"La interrumpís para corregirla","score":0},{"value":"B","label":"Escuchás, resumís los tres temas, confirmás prioridades y acordás próximos pasos","score":3},{"value":"C","label":"Respondés solo el problema más fácil","score":1},{"value":"D","label":"Transferís sin contexto","score":0}]},
{"id":"sat3","module":"sector-atencion","dimension":"Límites y escalamiento","difficulty":"alta","context":"La solución solicitada excede tu autoridad, pero existe una alternativa parcial inmediata.","text":"¿Qué hacés?","options":[{"value":"A","label":"Prometés la solución total","score":0},{"value":"B","label":"Negás todo sin explicar","score":0},{"value":"C","label":"Explicás tu alcance, ofrecés la alternativa y escalás con plazo y número de caso","score":3},{"value":"D","label":"Pedís que vuelva a llamar","score":1}]},
{"id":"sat4","module":"sector-atencion","dimension":"Entrevista de servicio","difficulty":"alta","type":"text","text":"Redactá cómo responderías a un cliente que recibió información contradictoria dos veces y amenaza con publicar el caso. Incluí contención, verificación, solución y seguimiento."}
]$q$::jsonb,'[]'::jsonb),
('sector-ventas','Ventas y comercial','Sector','Descubrimiento, negociación ética, indicadores y seguimiento.',array['Ventas consultivas','Negociación','Orientación a resultados'],$q$[
{"id":"sv1","module":"sector-ventas","dimension":"Venta consultiva","difficulty":"alta","context":"El prospecto pide precio de inmediato, pero menciona un problema que tu solución solo cubre parcialmente.","text":"¿Qué enfoque es más profesional?","options":[{"value":"A","label":"Cerrar rápido y omitir la limitación","score":0},{"value":"B","label":"Explorar impacto y criterios, transparentar el alcance y cotizar una alternativa adecuada","score":3},{"value":"C","label":"Dar el mayor descuento","score":1},{"value":"D","label":"Enviar una tarifa genérica","score":1}]},
{"id":"sv2","module":"sector-ventas","dimension":"Indicadores comerciales","difficulty":"alta","context":"La conversión sube de 20% a 25%, pero el ticket promedio baja 30% y el margen cae.","text":"¿Qué conclusión es más responsable?","options":[{"value":"A","label":"La campaña mejoró sin dudas","score":0},{"value":"B","label":"La conversión aislada no alcanza; hay que evaluar ingreso, margen y calidad del cliente","score":3},{"value":"C","label":"Debe eliminarse la campaña","score":1},{"value":"D","label":"El ticket no importa","score":0}]},
{"id":"sv3","module":"sector-ventas","dimension":"Negociación","difficulty":"alta","context":"El cliente exige una condición que volvería inviable el servicio y dice que un competidor la acepta.","text":"¿Cómo negociás?","options":[{"value":"A","label":"Aceptás y resolvés después","score":0},{"value":"B","label":"Descalificás al competidor","score":0},{"value":"C","label":"Indagás la necesidad detrás de la condición y proponés concesiones equivalentes y sostenibles","score":3},{"value":"D","label":"Cortás la conversación","score":1}]},
{"id":"sv4","module":"sector-ventas","dimension":"Entrevista comercial","difficulty":"alta","type":"text","text":"Prepará un plan de recuperación para una cartera con muchas consultas, baja conversión y seguimientos atrasados. Explicá segmentación, prioridades, métricas y frecuencia."}
]$q$::jsonb,'[]'::jsonb),
('sector-produccion','Producción y calidad','Sector','Control de procesos, desvíos, trazabilidad y mejora.',array['Producción','Calidad','Mejora continua'],$q$[
{"id":"sp1","module":"sector-produccion","dimension":"Control de proceso","difficulty":"alta","context":"Una medición sale fuera de tolerancia. El instrumento está vigente, pero el operario informa una vibración inusual durante la lectura.","text":"¿Qué secuencia es más sólida?","options":[{"value":"A","label":"Repetir hasta obtener un valor aceptable","score":0},{"value":"B","label":"Contener producto, registrar, verificar condiciones y método, repetir justificadamente y escalar el desvío","score":3},{"value":"C","label":"Ajustar la tolerancia","score":0},{"value":"D","label":"Descartar solo la pieza medida","score":1}]},
{"id":"sp2","module":"sector-produccion","dimension":"Trazabilidad","difficulty":"alta","context":"Se mezclaron dos lotes visualmente idénticos y no puede asegurarse qué unidades pertenecen a cada uno.","text":"¿Qué corresponde?","options":[{"value":"A","label":"Asignar todo al lote más reciente","score":0},{"value":"B","label":"Aislar el material afectado y reconstruir trazabilidad antes de liberarlo","score":3},{"value":"C","label":"Liberar si el aspecto es correcto","score":0},{"value":"D","label":"Cambiar las etiquetas","score":0}]},
{"id":"sp3","module":"sector-produccion","dimension":"Mejora continua","difficulty":"alta","context":"Un defecto aparece en 2% del turno mañana y 9% del turno noche durante cuatro semanas.","text":"¿Cuál es la investigación inicial más útil?","options":[{"value":"A","label":"Culpar al turno noche","score":0},{"value":"B","label":"Comparar materiales, ajustes, ambiente, método, dotación y medición por turno","score":3},{"value":"C","label":"Aumentar la tolerancia","score":0},{"value":"D","label":"Promediar ambos porcentajes","score":1}]},
{"id":"sp4","module":"sector-produccion","dimension":"Entrevista técnica","difficulty":"alta","type":"text","text":"Describí cómo investigarías un defecto repetitivo sin causa evidente: contención, datos a recolectar, hipótesis, prueba de causa y verificación de la acción."}
]$q$::jsonb,'["https://www.argentina.gob.ar/srt/prevencion/publicaciones/manual"]'::jsonb),
('sector-logistica','Logística y depósito','Sector','Inventario, recepción, preparación y seguridad operativa.',array['Logística','Inventario','Seguridad'],$q$[
{"id":"sl1","module":"sector-logistica","dimension":"Inventario","difficulty":"alta","context":"El sistema indica 42 unidades; el conteo físico da 38. Hay dos pedidos preparados sin confirmar y una devolución sin ubicar.","text":"¿Qué hacés primero?","options":[{"value":"A","label":"Ajustar el sistema a 38","score":0},{"value":"B","label":"Bloquear movimientos del ítem, verificar documentos y ubicaciones y reconciliar antes del ajuste autorizado","score":3},{"value":"C","label":"Contar solo la ubicación principal","score":1},{"value":"D","label":"Cancelar los pedidos","score":0}]},
{"id":"sl2","module":"sector-logistica","dimension":"Recepción","difficulty":"alta","context":"Llega mercadería con embalaje húmedo; el remito coincide y el transportista tiene prisa.","text":"¿Qué decisión es más adecuada?","options":[{"value":"A","label":"Firmar conforme para evitar demora","score":0},{"value":"B","label":"Registrar la condición, segregar o inspeccionar según procedimiento y firmar con observación si corresponde","score":3},{"value":"C","label":"Rechazar todo sin revisar","score":1},{"value":"D","label":"Secar el embalaje y almacenar","score":0}]},
{"id":"sl3","module":"sector-logistica","dimension":"Seguridad logística","difficulty":"alta","context":"Un pallet urgente supera la altura estable recomendada y obstruye parcialmente la visión del operador.","text":"¿Qué hacés?","options":[{"value":"A","label":"Moverlo despacio porque es urgente","score":0},{"value":"B","label":"Reacondicionar la carga o usar un medio y recorrido seguro antes de moverla","score":3},{"value":"C","label":"Pedir a alguien que camine delante","score":1},{"value":"D","label":"Reducir solo la velocidad","score":1}]},
{"id":"sl4","module":"sector-logistica","dimension":"Entrevista logística","difficulty":"alta","type":"text","text":"Diseñá un control para reducir errores de picking cuando dos productos tienen envases muy similares. Incluí proceso, señalización, verificación y métrica."}
]$q$::jsonb,'["https://www.argentina.gob.ar/srt/prevencion/agentes-de-riesgos/guia-de-agentes-de-riesgo-presunto"]'::jsonb),
('sector-maestranza','Maestranza y limpieza','Sector','Productos, señalización, bioseguridad, ergonomía y planificación.',array['Limpieza profesional','Seguridad química','Prevención'],$q$[
{"id":"sm1","module":"sector-maestranza","dimension":"Seguridad química","difficulty":"alta","context":"Una superficie tiene suciedad resistente. Un compañero propone mezclar lavandina con otro limpiador para potenciar el efecto.","text":"¿Cómo actuás?","options":[{"value":"A","label":"Mezclás una pequeña cantidad","score":0},{"value":"B","label":"No mezclás; consultás etiqueta y ficha, ventilás y usás el producto y dilución indicados","score":3},{"value":"C","label":"Probás sin guantes","score":0},{"value":"D","label":"Usás más concentración del mismo producto sin consultar","score":1}]},
{"id":"sm2","module":"sector-maestranza","dimension":"Prevención","difficulty":"alta","context":"Debés limpiar un pasillo de alto tránsito y no hay posibilidad de cerrarlo por completo.","text":"¿Qué planificación reduce mejor el riesgo?","options":[{"value":"A","label":"Limpiar todo junto y avisar verbalmente","score":0},{"value":"B","label":"Sectorizar, señalizar antes de comenzar, mantener un paso seguro y retirar señalización cuando esté seco","score":3},{"value":"C","label":"Trabajar más rápido","score":1},{"value":"D","label":"Dejar el carro bloqueando el paso","score":0}]},
{"id":"sm3","module":"sector-maestranza","dimension":"Bioseguridad","difficulty":"alta","context":"Encontrás material cortopunzante dentro de una bolsa común.","text":"¿Qué corresponde?","options":[{"value":"A","label":"Empujarlo hacia el fondo con la mano protegida","score":0},{"value":"B","label":"Detener la manipulación, aislar el área y activar el procedimiento para cortopunzantes","score":3},{"value":"C","label":"Pasarlo a otra bolsa","score":0},{"value":"D","label":"Dejarlo para el siguiente turno","score":0}]},
{"id":"sm4","module":"sector-maestranza","dimension":"Entrevista de maestranza","difficulty":"alta","type":"text","text":"Explicá cómo organizarías la limpieza de baños, comedor y oficinas durante una jornada con público, evitando contaminación cruzada y riesgos de caídas."}
]$q$::jsonb,'["https://www.argentina.gob.ar/srt/prevencion/publicaciones/manual","https://www.argentina.gob.ar/srt/prevencion/epp"]'::jsonb),
('sector-gastronomia','Gastronomía y manipulación de alimentos','Sector','Inocuidad, contaminación cruzada, temperaturas y alérgenos.',array['Manipulación segura','Inocuidad','Organización de cocina'],$q$[
{"id":"sg1","module":"sector-gastronomia","dimension":"Inocuidad","difficulty":"alta","context":"Durante el servicio se corta la cadena de frío de un alimento de alto riesgo y no se sabe cuánto tiempo estuvo fuera de temperatura segura.","text":"¿Qué decisión es correcta?","options":[{"value":"A","label":"Probar olor y sabor","score":0},{"value":"B","label":"Aislarlo, no servirlo y aplicar el procedimiento de descarte o evaluación autorizado","score":3},{"value":"C","label":"Enfriarlo rápidamente y usarlo","score":0},{"value":"D","label":"Cocinarlo más tiempo sin registrar","score":1}]},
{"id":"sg2","module":"sector-gastronomia","dimension":"Contaminación cruzada","difficulty":"alta","context":"Se usó una tabla para pollo crudo y debe prepararse una ensalada inmediata.","text":"¿Qué corresponde?","options":[{"value":"A","label":"Enjuagarla con agua","score":0},{"value":"B","label":"Dar vuelta la tabla","score":0},{"value":"C","label":"Usar utensilios diferenciados limpios y sanitizados; limpiar y desinfectar según procedimiento","score":3},{"value":"D","label":"Secarla con un paño","score":0}]},
{"id":"sg3","module":"sector-gastronomia","dimension":"Alérgenos","difficulty":"alta","context":"Un cliente informa alergia severa. La receta no contiene el alérgeno, pero se prepara en una estación compartida.","text":"¿Cómo actuás?","options":[{"value":"A","label":"Asegurás que es seguro porque la receta no lo incluye","score":0},{"value":"B","label":"Informás el riesgo, verificás protocolo, ingredientes y contaminación cruzada antes de confirmar si puede elaborarse","score":3},{"value":"C","label":"Retirás el ingrediente visible","score":0},{"value":"D","label":"Servís una porción pequeña","score":0}]},
{"id":"sg4","module":"sector-gastronomia","dimension":"Entrevista gastronómica","difficulty":"alta","type":"text","text":"Explicá cómo recibirías, almacenarías y rotarías mercadería perecedera si detectás diferencias de temperatura, envases dañados y fechas próximas."}
]$q$::jsonb,'["https://www.argentina.gob.ar/anmat/regulados/alimentos/carnet-de-manipulacion-de-alimentos/material-didactico","https://www.argentina.gob.ar/anmat/regulados/alimentos/carnet-de-manipuladores"]'::jsonb),
('sector-salud','Salud y apoyo asistencial','Sector','Seguridad del paciente, identificación, confidencialidad y escalamiento.',array['Seguridad del paciente','Comunicación clínica','Confidencialidad'],$q$[
{"id":"ss1","module":"sector-salud","dimension":"Seguridad del paciente","difficulty":"alta","context":"Antes de una práctica observás que el nombre coincide, pero la fecha de nacimiento de la pulsera no coincide con la orden.","text":"¿Qué hacés?","options":[{"value":"A","label":"Continuás porque el nombre coincide","score":0},{"value":"B","label":"Detenés el proceso, verificás con identificadores válidos y notificás la discrepancia","score":3},{"value":"C","label":"Corregís la pulsera sin informar","score":0},{"value":"D","label":"Preguntás solo a un acompañante","score":1}]},
{"id":"ss2","module":"sector-salud","dimension":"Comunicación segura","difficulty":"alta","context":"Recibís una indicación verbal que no comprendés por completo y la situación no es una emergencia inmediata.","text":"¿Cuál es la mejor respuesta?","options":[{"value":"A","label":"Interpretarla según experiencia","score":0},{"value":"B","label":"Pedir aclaración, repetir la indicación para confirmar y registrar por el canal previsto","score":3},{"value":"C","label":"Preguntar a otro compañero después","score":1},{"value":"D","label":"No realizarla sin avisar","score":1}]},
{"id":"ss3","module":"sector-salud","dimension":"Confidencialidad","difficulty":"alta","context":"Un familiar solicita resultados y dice que siempre acompaña al paciente, pero no consta autorización.","text":"¿Qué corresponde?","options":[{"value":"A","label":"Informar por confianza","score":0},{"value":"B","label":"Verificar identidad, autorización y política antes de brindar información","score":3},{"value":"C","label":"Dar una explicación parcial","score":0},{"value":"D","label":"Mostrar la pantalla sin entregar copia","score":0}]},
{"id":"ss4","module":"sector-salud","dimension":"Entrevista asistencial","difficulty":"alta","type":"text","text":"Describí cómo actuarías si observás un cambio relevante en el estado de un paciente que está fuera de tu competencia resolver. Incluí observación, comunicación, urgencia y registro."}
]$q$::jsonb,'["https://www.argentina.gob.ar/salud/calidadatencionmedica/seguridadpaciente","https://www.argentina.gob.ar/salud/calidadatencionmedica"]'::jsonb),
('sector-seguridad','Seguridad privada y vigilancia','Sector','Observación, control de accesos, incidentes y límites de actuación.',array['Vigilancia','Control de accesos','Gestión de incidentes'],$q$[
{"id":"sse1","module":"sector-seguridad","dimension":"Control de accesos","difficulty":"alta","context":"Una persona conocida del gerente intenta ingresar sin credencial y afirma que la esperan. El gerente no responde.","text":"¿Qué hacés?","options":[{"value":"A","label":"La dejás pasar por su vínculo","score":0},{"value":"B","label":"Aplicás el procedimiento de verificación y espera, sin excepciones informales","score":3},{"value":"C","label":"Le pedís que entre rápido","score":0},{"value":"D","label":"Retenés su documento fuera del procedimiento","score":1}]},
{"id":"sse2","module":"sector-seguridad","dimension":"Gestión de incidentes","difficulty":"alta","context":"Observás humo leve en un sector técnico; no hay alarma activa y no conocés el origen.","text":"¿Cuál es la reacción más adecuada?","options":[{"value":"A","label":"Investigar solo y demorar el aviso","score":0},{"value":"B","label":"Activar comunicación y protocolo, preservar tu seguridad y orientar la respuesta según el plan","score":3},{"value":"C","label":"Esperar a ver llamas","score":0},{"value":"D","label":"Abrir todas las puertas","score":0}]},
{"id":"sse3","module":"sector-seguridad","dimension":"Límites de actuación","difficulty":"alta","context":"Durante una discusión, una persona te exige revisar el teléfono de otra para demostrar un supuesto robo.","text":"¿Cómo actuás?","options":[{"value":"A","label":"Revisás el teléfono para resolver rápido","score":0},{"value":"B","label":"Preservás la situación, comunicás a la autoridad correspondiente y actuás dentro del protocolo y facultades","score":3},{"value":"C","label":"Obligás a desbloquearlo","score":0},{"value":"D","label":"Ignorás el incidente","score":1}]},
{"id":"sse4","module":"sector-seguridad","dimension":"Entrevista de vigilancia","difficulty":"alta","type":"text","text":"Redactá un parte objetivo sobre una persona que intentó ingresar sin autorización, se alteró verbalmente y finalmente se retiró. Diferenciá hechos observados de interpretaciones."}
]$q$::jsonb,'["https://www.argentina.gob.ar/normativa/provincial/ley-12297-123456789-0abc-defg-792-2100bvorpyel/actualizacion"]'::jsonb),
('sector-mantenimiento','Mantenimiento técnico','Sector','Diagnóstico, bloqueo, intervención y documentación.',array['Mantenimiento','Diagnóstico técnico','Seguridad'],$q$[
{"id":"smt1","module":"sector-mantenimiento","dimension":"Diagnóstico","difficulty":"alta","context":"Un motor se detiene por sobretemperatura. Al reiniciarlo en frío vuelve a operar, pero no se conoce la causa.","text":"¿Qué decisión es más sólida?","options":[{"value":"A","label":"Dejarlo funcionando hasta que falle","score":0},{"value":"B","label":"Investigar carga, ventilación, lubricación, alimentación y protecciones antes de liberarlo","score":3},{"value":"C","label":"Anular la protección","score":0},{"value":"D","label":"Cambiar el motor sin medir","score":1}]},
{"id":"smt2","module":"sector-mantenimiento","dimension":"Seguridad de intervención","difficulty":"alta","context":"La máquina está detenida desde el tablero, pero conserva energía neumática acumulada.","text":"¿Qué corresponde antes de intervenir?","options":[{"value":"A","label":"Confiar en el botón de parada","score":0},{"value":"B","label":"Aislar todas las energías, bloquear, verificar ausencia y descargar acumulaciones según procedimiento","score":3},{"value":"C","label":"Pedir a alguien que vigile el botón","score":1},{"value":"D","label":"Trabajar rápido","score":0}]},
{"id":"smt3","module":"sector-mantenimiento","dimension":"Trazabilidad técnica","difficulty":"alta","context":"Una reparación elimina el síntoma, pero no reproduce la falla original.","text":"¿Cómo cerrás la orden?","options":[{"value":"A","label":"Como solucionada definitivamente","score":0},{"value":"B","label":"Documentás hallazgos, acción, pruebas y condición de seguimiento sin afirmar una causa no verificada","score":3},{"value":"C","label":"Sin detalles","score":0},{"value":"D","label":"La dejás abierta indefinidamente","score":1}]},
{"id":"smt4","module":"sector-mantenimiento","dimension":"Entrevista técnica","difficulty":"alta","type":"text","text":"Explicá tu método para diagnosticar una falla intermitente que ocurre solo una vez por turno. Incluí datos, hipótesis, medición, seguridad y criterio de liberación."}
]$q$::jsonb,'["https://www.argentina.gob.ar/srt/prevencion/agentes-de-riesgos/guia-de-agentes-de-riesgo-presunto"]'::jsonb),
('sector-construccion','Construcción y obra','Sector','Riesgos críticos, coordinación, permisos y reporte.',array['Construcción','Prevención','Trabajo seguro'],$q$[
{"id":"sco1","module":"sector-construccion","dimension":"Trabajo en altura","difficulty":"alta","context":"La tarea es breve y el punto de anclaje previsto no está disponible.","text":"¿Qué hacés?","options":[{"value":"A","label":"La realizás con cuidado porque dura poco","score":0},{"value":"B","label":"Detenés y replanteás protección, acceso y anclaje con responsable competente","score":3},{"value":"C","label":"Usás una cañería cercana","score":0},{"value":"D","label":"Pedís que alguien sostenga la escalera","score":1}]},
{"id":"sco2","module":"sector-construccion","dimension":"Coordinación de riesgos","difficulty":"alta","context":"Dos contratistas trabajarán simultáneamente: uno genera chispas y otro manipula material combustible en el nivel inferior.","text":"¿Qué corresponde?","options":[{"value":"A","label":"Avisarles que tengan cuidado","score":1},{"value":"B","label":"Coordinar permisos, aislar o secuenciar tareas y verificar controles antes de iniciar","score":3},{"value":"C","label":"Comenzar la tarea más urgente","score":0},{"value":"D","label":"Dejar que cada supervisor decida por separado","score":0}]},
{"id":"sco3","module":"sector-construccion","dimension":"Excavaciones","difficulty":"alta","context":"Tras una lluvia intensa, la excavación parece estable y el cronograma está atrasado.","text":"¿Cómo procedés?","options":[{"value":"A","label":"Ingresás si no ves grietas","score":0},{"value":"B","label":"Reevaluás estabilidad, acceso, agua y protecciones antes de autorizar el ingreso","score":3},{"value":"C","label":"Ingresás de a uno","score":1},{"value":"D","label":"Solo agregás iluminación","score":0}]},
{"id":"sco4","module":"sector-construccion","dimension":"Entrevista de obra","difficulty":"alta","type":"text","text":"Describí cómo responderías a una orden urgente que entra en conflicto con una condición de seguridad. Incluí detención, comunicación, alternativa y reinicio."}
]$q$::jsonb,'["https://www.argentina.gob.ar/srt/prevencion/publicaciones/manual"]'::jsonb),
('sector-retail','Comercio, caja y reposición','Sector','Caja, fraude, inventario y atención.',array['Caja','Retail','Prevención de pérdidas'],$q$[
{"id":"sr1","module":"sector-retail","dimension":"Control de caja","difficulty":"alta","context":"Al cierre faltan $18.000. Hubo un retiro parcial sin firma y una devolución autorizada verbalmente.","text":"¿Qué hacés?","options":[{"value":"A","label":"Ponés el dinero para cerrar","score":0},{"value":"B","label":"Recontás, conciliás movimientos y comprobantes, preservás evidencia y reportás según procedimiento","score":3},{"value":"C","label":"Culpás al turno anterior","score":0},{"value":"D","label":"Ajustás como gasto","score":0}]},
{"id":"sr2","module":"sector-retail","dimension":"Prevención de fraude","difficulty":"alta","context":"Un cliente pide dividir una devolución en varias operaciones y cobrarla en un medio distinto al original.","text":"¿Qué respuesta es más adecuada?","options":[{"value":"A","label":"Aceptar para evitar conflicto","score":0},{"value":"B","label":"Aplicar política, verificar operación original y escalar cualquier excepción","score":3},{"value":"C","label":"Negar sin explicar","score":1},{"value":"D","label":"Hacer una parte sin registrar","score":0}]},
{"id":"sr3","module":"sector-retail","dimension":"Reposición segura","difficulty":"alta","context":"Un producto de alta rotación se agotó en góndola, pero el único acceso al stock bloquea una salida de emergencia durante la reposición.","text":"¿Qué priorizás?","options":[{"value":"A","label":"Reponer rápido y liberar después","score":0},{"value":"B","label":"Mantener la salida libre y reorganizar el método o momento de reposición","score":3},{"value":"C","label":"Poner un cartel","score":1},{"value":"D","label":"Cerrar la salida con llave","score":0}]},
{"id":"sr4","module":"sector-retail","dimension":"Entrevista retail","difficulty":"alta","type":"text","text":"Explicá cómo manejarías simultáneamente una fila creciente, una diferencia de precio y una alerta de posible hurto sin abandonar controles ni acusar sin evidencia."}
]$q$::jsonb,'[]'::jsonb),
('sector-hoteleria','Hotelería y recepción','Sector','Reservas, privacidad, incidentes y experiencia del huésped.',array['Hotelería','Recepción','Servicio'],$q$[
{"id":"sh1","module":"sector-hoteleria","dimension":"Gestión de reservas","difficulty":"alta","context":"Dos sistemas muestran la misma habitación confirmada para huéspedes distintos y el hotel está completo.","text":"¿Qué respuesta es más profesional?","options":[{"value":"A","label":"Esperar a que llegue el segundo huésped","score":0},{"value":"B","label":"Verificar trazabilidad, contactar proactivamente, asegurar alternativa equivalente y documentar compensación autorizada","score":3},{"value":"C","label":"Cancelar la reserva más barata","score":0},{"value":"D","label":"Decir que fue error del sistema","score":1}]},
{"id":"sh2","module":"sector-hoteleria","dimension":"Privacidad","difficulty":"alta","context":"Una persona llama preguntando si cierto huésped está alojado y afirma ser familiar.","text":"¿Qué hacés?","options":[{"value":"A","label":"Confirmás sin dar habitación","score":0},{"value":"B","label":"No confirmás presencia y aplicás el protocolo de contacto o mensajes autorizado","score":3},{"value":"C","label":"Das el horario de llegada","score":0},{"value":"D","label":"Transferís directamente a la habitación","score":0}]},
{"id":"sh3","module":"sector-hoteleria","dimension":"Gestión de incidentes","difficulty":"alta","context":"Un huésped informa olor a gas leve en su habitación, pero luego dice que desapareció.","text":"¿Cómo procedés?","options":[{"value":"A","label":"No hacés nada porque desapareció","score":0},{"value":"B","label":"Activás protocolo, reubicás si corresponde y solicitás verificación técnica antes de reutilizar","score":3},{"value":"C","label":"Abrís la ventana y cerrás el caso","score":1},{"value":"D","label":"Pedís que vuelva a avisar si empeora","score":0}]},
{"id":"sh4","module":"sector-hoteleria","dimension":"Entrevista hotelera","difficulty":"alta","type":"text","text":"Respondé a un huésped que llega de madrugada y cuya reserva no aparece, aunque muestra un comprobante válido. Incluí verificación, contención y alternativas."}
]$q$::jsonb,'[]'::jsonb),
('sector-transporte','Transporte y conducción','Sector','Planificación, fatiga, carga e incidentes.',array['Transporte','Conducción segura','Planificación'],$q$[
{"id":"st1","module":"sector-transporte","dimension":"Fatiga","difficulty":"alta","context":"Faltan 40 minutos para destino. Notás dificultad para mantener atención y bostezos repetidos; la entrega tiene ventana estricta.","text":"¿Qué decisión es correcta?","options":[{"value":"A","label":"Aumentar velocidad","score":0},{"value":"B","label":"Detenerte en un lugar seguro, informar y aplicar el protocolo de fatiga","score":3},{"value":"C","label":"Abrir la ventana y continuar","score":0},{"value":"D","label":"Tomar café sin detenerte","score":1}]},
{"id":"st2","module":"sector-transporte","dimension":"Carga segura","difficulty":"alta","context":"La documentación coincide, pero parte de la carga se desplazó y una sujeción está floja.","text":"¿Qué hacés?","options":[{"value":"A","label":"Continuás despacio","score":0},{"value":"B","label":"Inmovilizás en condición segura y corregís/validás la sujeción antes de continuar","score":3},{"value":"C","label":"Firmás una observación al llegar","score":1},{"value":"D","label":"Compensás moviendo otra carga","score":0}]},
{"id":"st3","module":"sector-transporte","dimension":"Incidentes","difficulty":"alta","context":"Tenés un roce menor sin lesionados y la otra parte propone resolverlo sin registrar para no perder tiempo.","text":"¿Cómo actuás?","options":[{"value":"A","label":"Aceptás si el daño es pequeño","score":0},{"value":"B","label":"Asegurás el lugar y cumplís el procedimiento de información, datos y reporte","score":3},{"value":"C","label":"Sacás una foto y seguís","score":1},{"value":"D","label":"Discutís responsabilidades en el lugar","score":0}]},
{"id":"st4","module":"sector-transporte","dimension":"Entrevista de transporte","difficulty":"alta","type":"text","text":"Planificá un recorrido con ventana de entrega, pronóstico adverso y tiempo legal de descanso próximo. Indicá prioridades, comunicación y criterios para reprogramar."}
]$q$::jsonb,'["https://www.argentina.gob.ar/srt/prevencion/publicaciones/manual"]'::jsonb),
('sector-rrhh','Recursos Humanos','Sector','Selección, confidencialidad, conflictos y documentación.',array['Recursos Humanos','Selección','Relaciones laborales'],$q$[
{"id":"srr1","module":"sector-rrhh","dimension":"Selección justa","difficulty":"alta","context":"Un líder pide descartar a una candidata por una característica personal no relacionada con el puesto, aunque cumple los requisitos.","text":"¿Qué hacés?","options":[{"value":"A","label":"Aceptás para cuidar la relación","score":0},{"value":"B","label":"Volvés a criterios laborales objetivos, documentás y escalás la solicitud improcedente","score":3},{"value":"C","label":"La descartás con otro motivo","score":0},{"value":"D","label":"Confrontás públicamente al líder","score":1}]},
{"id":"srr2","module":"sector-rrhh","dimension":"Confidencialidad","difficulty":"alta","context":"Un gerente solicita por chat un informe médico completo cuando solo necesita saber aptitud y restricciones laborales pertinentes.","text":"¿Qué respuesta protege mejor los datos?","options":[{"value":"A","label":"Enviar todo por jerarquía","score":0},{"value":"B","label":"Compartir únicamente información autorizada y necesaria por canal seguro","score":3},{"value":"C","label":"Mandar una captura parcial","score":0},{"value":"D","label":"Comentar verbalmente los detalles","score":0}]},
{"id":"srr3","module":"sector-rrhh","dimension":"Gestión de conflictos","difficulty":"alta","context":"Dos personas relatan versiones opuestas de un conflicto y ambas piden una sanción inmediata.","text":"¿Cuál es el primer abordaje?","options":[{"value":"A","label":"Sancionar a quien tenga menos antigüedad","score":0},{"value":"B","label":"Preservar imparcialidad, recabar hechos y evidencia, aplicar el procedimiento y medidas preventivas si hay riesgo","score":3},{"value":"C","label":"Reunirlas sin preparación","score":1},{"value":"D","label":"No intervenir","score":0}]},
{"id":"srr4","module":"sector-rrhh","dimension":"Entrevista de RRHH","difficulty":"alta","type":"text","text":"Diseñá una entrevista estructurada para un puesto operativo: competencias, preguntas conductuales, criterios de puntuación y controles para comparar candidatos con equidad."}
]$q$::jsonb,'["https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures"]'::jsonb),
('sector-liderazgo','Supervisión y liderazgo','Sector','Delegación, desempeño, riesgo y decisiones.',array['Liderazgo','Delegación','Gestión del desempeño'],$q$[
{"id":"sli1","module":"sector-liderazgo","dimension":"Gestión del desempeño","difficulty":"alta","context":"Una persona de alto rendimiento incumple repetidamente un control porque considera que retrasa el trabajo.","text":"¿Cómo intervenís?","options":[{"value":"A","label":"Lo tolerás por sus resultados","score":0},{"value":"B","label":"Revisás hechos e impacto, fijás expectativa y seguimiento, y analizás mejoras sin omitir el control","score":3},{"value":"C","label":"Lo sancionás sin conversación","score":1},{"value":"D","label":"Quitás el control a todo el equipo","score":0}]},
{"id":"sli2","module":"sector-liderazgo","dimension":"Delegación","difficulty":"alta","context":"Una tarea crítica debe delegarse a alguien nuevo que conoce la teoría pero no la ejecutó solo.","text":"¿Qué delegación es más sólida?","options":[{"value":"A","label":"Asignarla completa sin seguimiento","score":0},{"value":"B","label":"Definir resultado, límites, riesgos, puntos de control y apoyo proporcional","score":3},{"value":"C","label":"No delegar nunca","score":1},{"value":"D","label":"Dar instrucciones vagas para evaluar iniciativa","score":0}]},
{"id":"sli3","module":"sector-liderazgo","dimension":"Decisiones bajo presión","difficulty":"alta","context":"Cumplir la meta exige operar por encima de una capacidad recomendada, aunque todavía dentro de un límite técnico discutido.","text":"¿Cómo decidís?","options":[{"value":"A","label":"Maximizás producción hasta el límite","score":0},{"value":"B","label":"Evaluás riesgo, evidencia y autorizaciones; priorizás operación segura y comunicás el impacto en la meta","score":3},{"value":"C","label":"Pedís al equipo que decida","score":1},{"value":"D","label":"Ocultás el aumento temporal","score":0}]},
{"id":"sli4","module":"sector-liderazgo","dimension":"Entrevista de liderazgo","difficulty":"alta","type":"text","text":"Explicá cómo conducirías al equipo después de un error importante sin lesionados: contención, aprendizaje, responsabilidad, comunicación y prevención de una cultura de ocultamiento."}
]$q$::jsonb,'[]'::jsonb),
('sector-it','Soporte IT y operaciones digitales','Sector','Diagnóstico, seguridad de acceso, incidentes y comunicación.',array['Soporte técnico','Ciberseguridad','Gestión de incidentes'],$q$[
{"id":"sit1","module":"sector-it","dimension":"Seguridad de acceso","difficulty":"alta","context":"Una directora pide por teléfono restablecer urgentemente la contraseña de otra persona y conoce datos internos, pero llama desde un número no registrado.","text":"¿Qué hacés?","options":[{"value":"A","label":"La restablecés por jerarquía","score":0},{"value":"B","label":"Aplicás verificación de identidad y autorización sin omitir controles por urgencia","score":3},{"value":"C","label":"Enviás una clave temporal por WhatsApp","score":0},{"value":"D","label":"Le pedís un dato adicional informal","score":1}]},
{"id":"sit2","module":"sector-it","dimension":"Diagnóstico técnico","difficulty":"alta","context":"Tras una actualización, solo parte de los usuarios pierde acceso. Todos usan la misma aplicación, pero pertenecen a grupos distintos.","text":"¿Qué hipótesis conviene comprobar primero?","options":[{"value":"A","label":"Falla total de internet","score":0},{"value":"B","label":"Permisos, políticas o configuración aplicada diferencialmente por grupo","score":3},{"value":"C","label":"Daño físico en todos los equipos","score":0},{"value":"D","label":"Error de cada usuario","score":1}]},
{"id":"sit3","module":"sector-it","dimension":"Gestión de incidentes","difficulty":"alta","context":"Detectás actividad anómala en una cuenta privilegiada, pero bloquearla podría interrumpir un proceso crítico.","text":"¿Cómo actuás?","options":[{"value":"A","label":"Esperás para no afectar el proceso","score":0},{"value":"B","label":"Activás respuesta a incidentes, contenés según riesgo y coordinás continuidad con evidencia y registro","score":3},{"value":"C","label":"Cambiás la contraseña sin avisar","score":1},{"value":"D","label":"Publicás la alerta en un chat general","score":0}]},
{"id":"sit4","module":"sector-it","dimension":"Entrevista IT","difficulty":"alta","type":"text","text":"Explicá cómo gestionarías un incidente intermitente que no podés reproducir: preguntas al usuario, evidencia, hipótesis, pruebas, comunicación y criterio de cierre."}
]$q$::jsonb,'[]'::jsonb),
('sector-finanzas','Finanzas, caja y contabilidad','Sector','Conciliación, controles, fraude y análisis.',array['Contabilidad','Controles internos','Análisis financiero'],$q$[
{"id":"sf1","module":"sector-finanzas","dimension":"Control interno","difficulty":"alta","context":"La misma persona puede crear un proveedor, cargar su factura y aprobar el pago. La operación es legítima y urgente.","text":"¿Qué riesgo y respuesta identificás?","options":[{"value":"A","label":"No hay riesgo si la persona es confiable","score":0},{"value":"B","label":"Hay falta de segregación; se requiere control compensatorio y aprobación independiente documentada","score":3},{"value":"C","label":"Se paga y se revisa a fin de año","score":1},{"value":"D","label":"Se elimina al proveedor","score":0}]},
{"id":"sf2","module":"sector-finanzas","dimension":"Conciliación","difficulty":"alta","context":"Una transferencia figura debitada en banco pero pendiente en el sistema interno. El proveedor reclama falta de pago.","text":"¿Qué hacés?","options":[{"value":"A","label":"Pagás nuevamente","score":0},{"value":"B","label":"Verificás identificadores, estado bancario y circuito interno antes de informar o reprocesar","score":3},{"value":"C","label":"Marcás pagado manualmente","score":1},{"value":"D","label":"Ignorás el reclamo","score":0}]},
{"id":"sf3","module":"sector-finanzas","dimension":"Análisis financiero","difficulty":"alta","context":"Los ingresos crecieron 12%, los costos variables 20% y los costos fijos no cambiaron.","text":"¿Qué afirmación es defendible sin más datos?","options":[{"value":"A","label":"La utilidad necesariamente creció","score":0},{"value":"B","label":"El margen puede haberse deteriorado; hay que analizar volumen y estructura de costos","score":3},{"value":"C","label":"La empresa está en pérdida","score":0},{"value":"D","label":"Los costos fijos ya no importan","score":0}]},
{"id":"sf4","module":"sector-finanzas","dimension":"Entrevista financiera","difficulty":"alta","type":"text","text":"Describí cómo investigarías un pago duplicado: contención, evidencia, causa, recuperación, comunicación y control preventivo."}
]$q$::jsonb,'[]'::jsonb)
on conflict(slug) do update set titulo=excluded.titulo,categoria=excluded.categoria,descripcion=excluded.descripcion,
competencias=excluded.competencias,preguntas=excluded.preguntas,fuentes=excluded.fuentes,activo=true,actualizado_en=now();

with perfiles(slug,titulo,tipo,descripcion,sector,duracion,cantidad,modulo) as (values
('avanzado-administracion','Administración y oficina · avanzado','Perfil administrativo','Datos, conciliación, organización, confidencialidad y entrevista.','Administración',35,18,'sector-administracion'),
('avanzado-atencion-cliente','Atención al cliente y call center · avanzado','Perfil de servicio','Diagnóstico, comunicación, reclamos y límites de actuación.','Atención al cliente',35,18,'sector-atencion'),
('avanzado-ventas','Ventas consultivas · avanzado','Perfil comercial','Descubrimiento, negociación ética, indicadores y seguimiento.','Comercial',35,18,'sector-ventas'),
('avanzado-produccion','Producción y calidad · avanzado','Perfil técnico','Procesos, desvíos, trazabilidad y mejora continua.','Industria',35,18,'sector-produccion'),
('avanzado-logistica','Logística y depósito · avanzado','Perfil operativo','Inventario, recepción, picking y seguridad.','Logística',35,18,'sector-logistica'),
('avanzado-maestranza','Maestranza y limpieza · avanzado','Perfil operativo','Limpieza profesional, químicos, bioseguridad y prevención.','Maestranza',35,18,'sector-maestranza'),
('avanzado-gastronomia','Gastronomía e inocuidad · avanzado','Perfil gastronómico','Manipulación, temperaturas, contaminación cruzada y alérgenos.','Gastronomía',35,18,'sector-gastronomia'),
('avanzado-salud','Salud y apoyo asistencial · avanzado','Perfil sanitario','Seguridad del paciente, identificación, comunicación y confidencialidad.','Salud',35,18,'sector-salud'),
('avanzado-seguridad','Seguridad privada y vigilancia · avanzado','Perfil de seguridad','Accesos, observación, incidentes y límites de actuación.','Seguridad',35,18,'sector-seguridad'),
('avanzado-mantenimiento','Mantenimiento técnico · avanzado','Perfil técnico','Diagnóstico, energías, intervención y documentación.','Mantenimiento',35,18,'sector-mantenimiento'),
('avanzado-construccion','Construcción y obra · avanzado','Perfil operativo','Riesgos críticos, coordinación y permisos de trabajo.','Construcción',35,18,'sector-construccion'),
('avanzado-retail','Comercio, caja y reposición · avanzado','Perfil retail','Caja, fraude, inventario, atención y seguridad.','Retail',35,18,'sector-retail'),
('avanzado-hoteleria','Hotelería y recepción · avanzado','Perfil hotelero','Reservas, privacidad, incidentes y experiencia del huésped.','Hotelería',35,18,'sector-hoteleria'),
('avanzado-transporte','Transporte y conducción · avanzado','Perfil de transporte','Fatiga, carga, incidentes y planificación.','Transporte',35,18,'sector-transporte'),
('avanzado-rrhh','Recursos Humanos · avanzado','Perfil profesional','Selección justa, datos sensibles, conflictos y entrevista.','Recursos Humanos',35,18,'sector-rrhh'),
('avanzado-liderazgo','Supervisión y liderazgo · avanzado','Perfil de conducción','Delegación, desempeño, decisiones y cultura de seguridad.','Liderazgo',40,18,'sector-liderazgo'),
('avanzado-it','Soporte IT y operaciones digitales · avanzado','Perfil tecnológico','Diagnóstico, accesos, incidentes y comunicación técnica.','Tecnología',35,18,'sector-it'),
('avanzado-finanzas','Finanzas, caja y contabilidad · avanzado','Perfil financiero','Conciliación, controles internos, fraude y análisis.','Finanzas',35,18,'sector-finanzas')
), construidas as (
  select p.*,
    (select coalesce(jsonb_agg(q.question),'[]'::jsonb)
     from public.modulos_evaluacion m cross join lateral jsonb_array_elements(m.preguntas) q(question)
     where m.slug in ('razonamiento-datos','atencion-instrucciones','criterio-entrevista',p.modulo)) as banco,
    (select coalesce(jsonb_agg(distinct c.competencia),'[]'::jsonb)
     from public.modulos_evaluacion m cross join lateral unnest(m.competencias) c(competencia)
     where m.slug in ('razonamiento-datos','atencion-instrucciones','criterio-entrevista',p.modulo)) as competencias,
    (select coalesce(jsonb_agg(distinct f.fuente),'[]'::jsonb)
     from public.modulos_evaluacion m cross join lateral jsonb_array_elements_text(m.fuentes) f(fuente)
     where m.slug in ('razonamiento-datos','atencion-instrucciones','criterio-entrevista',p.modulo)) as fuentes
  from perfiles p
)
insert into public.plantillas_evaluacion(slug,titulo,tipo,descripcion,sector,nivel,duracion_minutos,cantidad_preguntas,version_contenido,competencias,fuentes,preguntas,activa)
select slug,titulo,tipo,descripcion,sector,'Avanzado',duracion,cantidad,'3.0',competencias,fuentes,banco,true from construidas
on conflict(slug) do update set titulo=excluded.titulo,tipo=excluded.tipo,descripcion=excluded.descripcion,
sector=excluded.sector,nivel=excluded.nivel,duracion_minutos=excluded.duracion_minutos,cantidad_preguntas=excluded.cantidad_preguntas,
version_contenido=excluded.version_contenido,competencias=excluded.competencias,fuentes=excluded.fuentes,preguntas=excluded.preguntas,
activa=true,actualizado_en=now();

-- Retira del catálogo las plantillas básicas v1.6; conserva los intentos históricos.
update public.plantillas_evaluacion set activa=false,actualizado_en=now()
where slug in ('logica-atencion-calidad-20','calidad-produccion-15','administracion-atencion-15','comercial-ventas-15');

comment on table public.modulos_evaluacion is 'Biblioteca modular de competencias y situaciones para construir simulacros por puesto.';
