-- CVStudio v4.4.0 · Catálogo administrable e historial comercial
create table if not exists public.servicios_precios (
  product_id text primary key,
  title text not null,
  unit_price numeric(12,2) not null check (unit_price > 0),
  active boolean not null default true,
  test_mode boolean not null default false,
  test_price numeric(12,2),
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);
insert into public.servicios_precios(product_id,title,unit_price,active,test_mode,test_price,sort_order) values
('cv-profesional','CV Profesional',12000,true,false,null,10),
('cv-freelance','CV Freelance Profesional',16000,true,false,null,20),
('linkedin','Perfil Profesional de LinkedIn',19000,true,false,null,30),
('combo-2-cv','Combo 2 CV Profesionales',20000,true,false,null,40),
('combo-cv-linkedin','Combo CV + LinkedIn',25000,true,false,null,50)
on conflict(product_id) do nothing;

create table if not exists public.pedidos_eventos (
  id bigint generated by default as identity primary key,
  external_reference text not null,
  event_type text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists pedidos_eventos_ref_idx on public.pedidos_eventos(external_reference,created_at desc);
alter table public.servicios_precios enable row level security;
alter table public.pedidos_eventos enable row level security;
grant usage on schema public to service_role;
grant select,insert,update,delete on public.servicios_precios to service_role;
grant select,insert,update,delete on public.pedidos_eventos to service_role;
grant usage,select on all sequences in schema public to service_role;
