const API='https://eqepkoegzyqklpxkrkhm.supabase.co/functions/v1/psico-api';
let content={"heroTitle":"Migrar también\nes una forma\nde encontrarse.","heroText":"Un espacio de escucha, acompañamiento y comunidad para quienes viven la experiencia migratoria, lejos o cerca de casa.","heroNote":"Distintos lugares.\nMismas preguntas.\nMás humanidad.","about":"Un espacio de escucha, acompañamiento y comunidad para quienes viven la experiencia migratoria, lejos o cerca de casa.\nUna mirada transversal que recorre todos nuestros espacios.","logo":"","podcastIntro":"Conversaciones reales sobre migración, identidad, salud mental y todo lo que implica empezar de nuevo.","membershipText":"Accedé a más contenido, encuentros exclusivos y un espacio seguro para compartir tu proceso.","spaces":[{"title":"Terapia Individual","description":"Personas que residen en Argentina.","detail":"Espacio de acompañamiento individual."},{"title":"Bitácora Migrante","description":"Personas migrantes. Espacio individual.","detail":"Acompañamiento individual en la experiencia migratoria."},{"title":"Punto de Encuentro","description":"Personas migrantes. Espacio grupal.","detail":"Propuesta grupal para personas migrantes."},{"title":"Comunidad en Tránsito","description":"Organización y coordinación de reuniones de convivencia.","detail":"Red y organización de experiencias de convivencia."},{"title":"Experiencia Inmersiva","description":"Centros culturales, talleres, arte, danza, yoga, meditación, teatros, bares, etc.","detail":"Experiencias que vinculan cultura, arte y bienestar."}],"episodes":[{"title":"Nosotrxs, lxs argentinxs, llevamos la solidaridad adentro","url":"","cover":"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=85"},{"title":"Aprender a convivir en comunidad","url":"","cover":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=150&q=80"},{"title":"Si volver es una forma de llegar","url":"","cover":"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=150&q=80"}],"articles":[{"title":"Empezar de nuevo también puede dar miedo","body":"Reflexiones sobre el cambio y la incertidumbre. Publicación de muestra: contenido oficial pendiente."},{"title":"Lo que se lleva en la valija (y lo que no)","body":"Sobre recuerdos, pertenencia e identidad. Publicación de muestra: contenido oficial pendiente."},{"title":"La fuerza de encontrar una red en el exterior","body":"Tejer vínculos y sentirnos cerca. Publicación de muestra: contenido oficial pendiente."}]},priorFocus,episodeIndex=0;
const $=s=>document.querySelector(s),escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openDialog(html){priorFocus=document.activeElement;$('#modalContent').innerHTML=html;$('#overlay').classList.add('open');document.body.style.overflow='hidden';$('.close').focus()}
function hideModal(){$('#overlay').classList.remove('open');document.body.style.overflow='';priorFocus?.focus()}
function toggleMenu(b){const open=$('.top .menu').classList.toggle('open');b.setAttribute('aria-expanded',String(open))}
function spaceDetail(e,i){e.preventDefault();const s=content?.spaces[i];if(!s)return;openDialog('<span class="tag">NUESTROS ESPACIOS</span><h2>'+escapeHTML(s.title)+'</h2><p class="body-copy">'+escapeHTML(s.detail||s.description)+'</p>')}
function showModal(type){if(type==='admin'){location.href='gestion/';return}if(type==='login'||type==='register'){openDialog('<span class="tag">TU CUENTA</span><h2>'+ (type==='login'?'Iniciar sesión':'Sumarte a la comunidad')+'</h2><p>El acceso de miembros estará disponible cuando se habiliten los registros públicos.</p><p>Podés explorar los espacios y las publicaciones de esta propuesta.</p><button class="btn" onclick="hideModal()">Seguir explorando →</button>');return}if(type==='subscribe'){openDialog('<span class="tag">SUSCRIPCIÓN</span><h2>Formá parte de esta comunidad.</h2><p class="body-copy">'+escapeHTML(content?.membershipText)+'</p><div class="notice">Los planes, beneficios y medios de pago están en preparación.</div>');return}if(type==='podcasts'){openDialog('<span class="tag">PODCAST / AUDIOS</span><h2>Historias que nos acercan.</h2>'+ (content?.episodes||[]).map((ep,i)=>'<button class="article-entry" style="background:none;border:0;text-align:left;color:inherit;width:100%" onclick="hideModal();chooseEpisode('+i+')">'+escapeHTML(ep.title)+(ep.url?' &nbsp; ▶':' · Próximamente')+'</button>').join(''));}}
function showArticles(){openDialog('<span class="tag">ARTÍCULOS Y RECURSOS</span><h2>Ideas para acompañarte.</h2>'+ (content?.articles||[]).map((a,i)=>'<button class="article-entry" style="background:none;border:0;text-align:left;color:inherit;width:100%" onclick="articleDetail('+i+')">'+escapeHTML(a.title)+' &nbsp; →</button>').join(''))}
function articleDetail(i){const a=content?.articles[i];if(a)openDialog('<span class="tag">ARTÍCULOS Y RECURSOS</span><h2>'+escapeHTML(a.title)+'</h2><p class="body-copy">'+escapeHTML(a.body)+'</p>')}
function about(e){e.preventDefault();openDialog('<span class="tag">SOBRE NOSOTROS</span><h2>Una Psico Argentina</h2><p class="body-copy">'+escapeHTML(content?.about)+'</p>')}
function chooseEpisode(i){const ep=content?.episodes[i];if(!ep)return;episodeIndex=i;$('.player h3').textContent=ep.title;$('.player .tag').textContent='EP. '+String(i+1).padStart(2,'0');if(ep.cover&&ep.cover.startsWith('https://'))$('.cover').style.backgroundImage='linear-gradient(0deg,#15344755,transparent),url('+JSON.stringify(ep.cover)+')';let audio=$('#realAudio');if(audio){audio.pause();audio.remove()}$('#playButton').textContent='▶';$('#audioMessage').textContent=ep.url?'Listo para escuchar':'Audio pendiente de publicación';if(ep.url){audio=document.createElement('audio');audio.id='realAudio';audio.className='audio-element';audio.controls=true;audio.preload='none';audio.src=ep.url;$('.player-body').append(audio);audio.addEventListener('play',()=>$('#playButton').textContent='Ⅱ');audio.addEventListener('pause',()=>$('#playButton').textContent='▶');audio.addEventListener('error',()=>$('#audioMessage').textContent='No se pudo cargar el audio. Revisá el enlace del episodio.')}}
async function togglePlay(){const audio=$('#realAudio');if(!audio){$('#audioMessage').textContent='Este episodio se publicará próximamente.';return}try{if(audio.paused)await audio.play();else audio.pause()}catch{$('#audioMessage').textContent='No se pudo reproducir. Probá desde los controles del audio.'}}
function applyContent(c){content=c;$('.hero h1').textContent=c.heroTitle;$('.hero p').textContent=c.heroText;$('.hero-note').textContent=c.heroNote;$('.audio-layout > div:first-child p').textContent=c.podcastIntro;$('.subscription-preview p').textContent=c.membershipText;document.querySelectorAll('.space-card').forEach((card,i)=>{const s=c.spaces[i];card.querySelector('h3').textContent=s.title;card.querySelector('p').textContent=s.description;card.querySelector('.more').setAttribute('aria-label','Conocer '+s.title)});document.querySelectorAll('.brand').forEach(b=>{b.querySelector('.logo-image')?.remove();if(c.logo&&(/^(https:\/\/|data:image\/(png|jpeg|webp);base64,)/.test(c.logo))){const im=document.createElement('img');im.src=c.logo;im.alt='Logo de Una Psico Argentina';im.className='logo-image';b.prepend(im)}});const list=$('.episode-list');list.innerHTML=c.episodes.slice(1,3).map((ep,i)=>'<button class="episode" onclick="chooseEpisode('+(i+1)+')">'+(ep.cover?'<img src="'+escapeHTML(ep.cover)+'" alt="" loading="lazy">':'<span class="ep-play">♫</span>')+'<span><small>EP. '+String(i+2).padStart(2,'0')+'</small><strong>'+escapeHTML(ep.title)+'</strong></span><span class="ep-play">›</span></button>').join('');if(c.episodes.length)chooseEpisode(0);else{$('.player h3').textContent='Nuevos episodios próximamente';$('#audioMessage').textContent='';}}
$('#overlay').addEventListener('click',e=>{if(e.target.id==='overlay')hideModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')hideModal();if(e.key!=='Tab'||!$('#overlay').classList.contains('open'))return;const f=[...$('.modal').querySelectorAll('a,button,input')];if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}});
const wave=$('#wave');for(let i=0;i<60;i++){const s=document.createElement('span');s.style.setProperty('--h',(4+Math.abs(Math.sin(i*2.4))*22)+'px');wave.append(s)}
applyContent(content);
fetch(API+'?action=content',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(r=>{if(r.content)applyContent(r.content)}).catch(()=>{console.warn('No se pudo actualizar el contenido.');});
