const API='https://eqepkoegzyqklpxkrkhm.supabase.co/functions/v1/psico-api';
let content={"heroTitle": "Migrar también\nes una forma\nde encontrarse.", "heroText": "Un espacio de escucha, acompañamiento y comunidad para quienes viven la experiencia migratoria, lejos o cerca de casa.", "heroNote": "Distintos lugares.\nMismas preguntas.\nMás humanidad.", "about": "Un espacio de escucha, acompañamiento y comunidad para quienes viven la experiencia migratoria, lejos o cerca de casa.\nUna mirada transversal que recorre todos nuestros espacios.", "logo": "", "podcastIntro": "Recursos y estrategias de afrontamiento que acompañan los distintos espacios. Explorá las temporadas y sus audios.", "membershipText": "Accedé a más contenido, encuentros exclusivos y un espacio seguro para compartir tu proceso.", "spaces": [{"title": "Terapia Individual", "description": "Personas que residen en Argentina.", "detail": "Espacio de acompañamiento individual."}, {"title": "Bitácora Migrante", "description": "Personas migrantes. Espacio individual.", "detail": "Acompañamiento individual en la experiencia migratoria."}, {"title": "Punto de Encuentro", "description": "Personas migrantes. Espacio grupal.", "detail": "Propuesta grupal para personas migrantes."}, {"title": "Comunidad en Tránsito", "description": "Personas migrantes que comparten una vivienda.", "detail": "Organización y coordinación de reuniones de convivencia para personas migrantes que se encuentran momentáneamente en una vivienda compartida."}, {"title": "Experiencia Inmersiva", "description": "Cultura, arte y experiencias de bienestar.", "detail": "Propuestas en centros culturales, ateliers y galerías de arte, estudios de danza, yoga y meditación, teatros y bares, entre otros espacios."}], "episodes": [], "articles": [{"title": "Empezar de nuevo también puede dar miedo", "body": "Reflexiones sobre el cambio y la incertidumbre. Publicación de muestra: contenido oficial pendiente."}, {"title": "Lo que se lleva en la valija (y lo que no)", "body": "Sobre recuerdos, pertenencia e identidad. Publicación de muestra: contenido oficial pendiente."}, {"title": "La fuerza de encontrar una red en el exterior", "body": "Tejer vínculos y sentirnos cerca. Publicación de muestra: contenido oficial pendiente."}], "seasons": [{"title": "Temporada 1", "description": "Recursos y estrategias de afrontamiento."}]};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toggleMenu(b){const open=$('.top .menu').classList.toggle('open');b.setAttribute('aria-expanded',String(open))}
function shell(label,title,body){return '<div class="detail-inner"><a class="back-link" href="#espacios">← Volver a los espacios</a><div class="tag">'+esc(label)+'</div><h1>'+esc(title)+'</h1>'+body+'</div>'}
function route(){const hash=location.hash.slice(1)||'inicio',detail=$('#detailView'),home=$('#homeView');let html='';const match=/^espacio-([1-5])$/.exec(hash);if(match){const s=content.spaces[Number(match[1])-1];html=shell('Modalidades de atención y acompañamiento',s.title,'<p class="lead">'+esc(s.description)+'</p><div class="detail-copy">'+esc(s.detail)+'</div><a class="btn" href="#podcast">Explorar recursos del Podcast</a>')}
else if(hash==='nosotros'){html=shell('Sobre nosotros','Una Psico Argentina','<div class="detail-copy">'+esc(content.about)+'</div><a class="btn primary" href="#espacios">Conocer los espacios</a>')}
else if(hash==='podcast'){html=shell('Recursos transversales','Podcast','<p class="lead">'+esc(content.podcastIntro)+'</p><div class="season-grid">'+(content.seasons||[{title:'Temporada 1',description:'Recursos y estrategias de afrontamiento.'}]).map((s,i)=>'<article class="season-card"><div class="tag">PODCAST · AUDIOS</div><h2>'+esc(s.title)+'</h2><p>'+esc(s.description)+'</p><a class="btn" href="#temporada-'+(i+1)+'">Explorar temporada</a></article>').join('')+'</div>')}
else if(/^temporada-\d+$/.test(hash)){const i=Number(hash.split('-')[1])-1,seasons=content.seasons||[{title:'Temporada 1',description:'Recursos y estrategias de afrontamiento.'}],s=seasons[i];if(s){const episodes=content.episodes.filter(ep=>(ep.season||'Temporada 1')===s.title);html=shell('Podcast',s.title,'<p class="lead">'+esc(s.description)+'</p>'+episodes.map(ep=>'<article class="audio-item"><h2>'+esc(ep.title)+'</h2>'+(ep.url&&/^https:\/\//.test(ep.url)?'<audio controls preload="none" src="'+esc(ep.url)+'"></audio>':'<p class="pending">Audio próximamente.</p>')+'</article>').join('')+(!episodes.length?'<p class="detail-copy">Los audios de esta temporada estarán disponibles próximamente.</p>':'')+'<a class="btn" href="#podcast">Ver todas las temporadas</a>')}}
home.hidden=!!html;detail.hidden=!html;if(html){detail.innerHTML=html;document.title=detail.querySelector('h1').textContent+' | Una Psico Argentina';window.scrollTo(0,0);detail.focus({preventScroll:true})}else{document.title='Una Psico Argentina | Comunidad migrante';if(hash==='espacios')$('#espacios').scrollIntoView();else window.scrollTo(0,0)}$('.top .menu').classList.remove('open');$('.mobile-toggle').setAttribute('aria-expanded','false')}
function applyContent(c){content=c;$('.hero h1').textContent=c.heroTitle;$('.hero p').textContent=c.heroText;$('.hero-note').textContent=c.heroNote;document.querySelectorAll('.space-card').forEach((card,i)=>{const s=c.spaces[i];if(!s)return;card.querySelector('h3').textContent=s.title;card.querySelector('p').textContent=s.description;card.querySelector('.more').setAttribute('aria-label','Conocer '+s.title)});document.querySelectorAll('.brand').forEach(b=>{b.querySelector('.logo-image')?.remove();if(c.logo&&/^(https:\/\/|data:image\/(png|jpeg|webp);base64,)/.test(c.logo)){const im=document.createElement('img');im.src=c.logo;im.alt='Logo de Una Psico Argentina';im.className='logo-image';b.prepend(im)}});route()}
window.addEventListener('hashchange',route);applyContent(content);fetch(API+'?action=content',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(r=>{if(r.content)applyContent(r.content)}).catch(()=>console.warn('Se muestra la versión de respaldo.'));
