import {client,escape,safeUrl,defaultSettings,money} from './shared.js';
const $=s=>document.querySelector(s), form=$('#product-form'), sf=$('#settings-form');let db,products=[],settings={...defaultSettings},busy=false;
function status(t){$('#status').textContent=t;}
function showLogin(){ $('#dashboard').hidden=true;$('#logout').hidden=true;$('#login').hidden=false; }
async function upload(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Usá una imagen JPG, PNG o WebP de hasta 5 MB.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];const path=crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('viser-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return {url:db.storage.from('viser-media').getPublicUrl(path).data.publicUrl,path};}
function mediaPath(url){const base=db.storage.from('viser-media').getPublicUrl('').data.publicUrl;return url.startsWith(base)?url.slice(base.length):null;}
async function cleanup(url){const path=mediaPath(url);if(!path)return;const {error}=await db.storage.from('viser-media').remove([path]);if(error)status('Guardado. No se pudo eliminar una imagen anterior; revisá el almacenamiento.');}
async function authorized(){const {data,error}=await db.auth.getUser();if(error||!data.user)return false;const admin=await db.from('viser_admins').select('user_id').eq('user_id',data.user.id).maybeSingle();return !admin.error&&!!admin.data;}
function edit(p={}){form.reset();form.elements.id.value=p.id||'';for(const key of ['image','title','description','price','stock','currency','category','sort_order'])if(p[key]!=null)form.elements[key].value=p[key];form.elements.published.checked=p.published!==false;$('#editor-title').textContent=p.id?'Editar producto':'Agregar producto';$('#image-preview').hidden=!p.image;$('#image-preview').src=p.image||'';$('#editor').hidden=false;$('#editor').scrollIntoView({behavior:'smooth',block:'start'});}
function list(){ $('#admin-list').innerHTML=products.length?products.map(p=>`<article class="admin-row"><img src="${escape(safeUrl(p.image))}" alt="${escape(p.title)}"><div class="info"><h3>${escape(p.title)}</h3><span class="muted">${escape(money(p))} · ${p.published?'Visible':'Oculto'}</span></div><button class="btn blue" data-edit="${p.id}">Editar</button><button class="btn danger" data-delete="${p.id}">Eliminar</button></article>`).join(''):'<p>No hay productos. Agregá el primero.</p>';$('#admin-list').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(products.find(p=>p.id===b.dataset.edit)));$('#admin-list').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>run(async()=>{const p=products.find(p=>p.id===b.dataset.delete);if(!confirm('¿Eliminar '+p.title+' del catálogo?'))return;const {data,error}=await db.from('viser_products').delete().eq('id',p.id).select('id');if(error)throw error;if(!data.length)throw new Error('No se pudo eliminar. Verificá tus permisos.');await cleanup(p.image);await load();status('Producto eliminado.');})); }
async function load(){if(!await authorized()){showLogin();throw new Error('Esta cuenta no tiene permiso para administrar VISER.');}const [ps,ss]=await Promise.all([db.from('viser_products').select('*').order('sort_order'),db.from('viser_settings').select('*').eq('id',1).single()]);if(ps.error||ss.error)throw ps.error||ss.error;products=ps.data;settings={...defaultSettings,...ss.data};for(const key of ['whatsapp','email','instagram','facebook'])sf.elements[key].value=settings[key]||'';list();$('#login').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message||'No pudimos completar la operación. Intentá nuevamente.');}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
$('#new').onclick=()=>edit();$('#cancel').onclick=()=>$('#editor').hidden=true;
let preview;form.elements.file.onchange=()=>{if(preview)URL.revokeObjectURL(preview);const f=form.elements.file.files[0];if(f){preview=URL.createObjectURL(f);$('#image-preview').src=preview;$('#image-preview').hidden=false;}};
$('#login-form').onsubmit=e=>{e.preventDefault();run(async()=>{const f=e.target;const {error}=await db.auth.signInWithPassword({email:f.elements.email.value.trim(),password:f.elements.password.value});if(error)throw new Error(error.code==='email_not_confirmed'?'Primero confirmá tu correo desde el enlace que recibiste en info@viserint.com.':'No pudimos ingresar. Revisá tu correo y contraseña.');f.elements.password.value='';await load();status('Sesión iniciada.');});};
$('#logout').onclick=()=>run(async()=>{const {error}=await db.auth.signOut();if(error)throw error;showLogin();status('Sesión cerrada.');});
form.onsubmit=e=>{e.preventDefault();run(async()=>{const f=form.elements,id=f.id.value,old=products.find(p=>p.id===id);let image=f.image.value,newUpload;const file=f.file.files[0];if(file){newUpload=await upload(file);image=newUpload.url;}if(!image)throw new Error('Cargá una imagen para el producto.');const payload={title:f.title.value.trim(),description:f.description.value.trim(),image,price:f.price.value===''?null:Number(f.price.value),currency:f.currency.value,stock:f.stock.value===''?null:Number(f.stock.value),category:f.category.value,sort_order:Number(f.sort_order.value),published:f.published.checked};const result=id?await db.from('viser_products').update(payload).eq('id',id).select('id'):await db.from('viser_products').insert(payload).select('id');if(result.error||!result.data?.length){if(newUpload)await db.storage.from('viser-media').remove([newUpload.path]);throw result.error||new Error('No se guardó el producto. Verificá tus permisos.');}if(old&&old.image!==image)await cleanup(old.image);await load();$('#editor').hidden=true;status('Producto guardado. El cambio ya está disponible en la web pública.');});};
sf.onsubmit=e=>{e.preventDefault();run(async()=>{const f=sf.elements,payload={};for(const key of ['whatsapp','email','instagram','facebook'])payload[key]=f[key].value.trim();payload.whatsapp=payload.whatsapp.replace(/\D/g,'');if(!/^\d{10,15}$/.test(payload.whatsapp))throw new Error('Ingresá WhatsApp con código de país, sin el 0 ni el 15.');let newUpload;if(f.hero.files[0]){newUpload=await upload(f.hero.files[0]);payload.hero_image=newUpload.url;}const {data,error}=await db.from('viser_settings').update(payload).eq('id',1).select('id');if(error||!data.length){if(newUpload)await db.storage.from('viser-media').remove([newUpload.path]);throw error||new Error('No se guardó la configuración.');}if(newUpload)await cleanup(settings.hero_image);sf.reset();await load();status('Portada y contacto actualizados.');});};
try{db=await client();if(!db){status('Panel preparado. Falta conectar la base de datos y crear la cuenta administradora antes de habilitar el ingreso.');$('#login-form').querySelector('button').disabled=true;}else{status('Ingresá con tu cuenta administradora.');if(await authorized())await load();db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')showLogin();});}}catch{status('No pudimos conectar el panel. Revisá la configuración de la base de datos.');}

$('#password-form').onsubmit=e=>{e.preventDefault();run(async()=>{const f=e.target;if(f.elements.password.value!==f.elements.confirm.value)throw new Error('Las contraseñas no coinciden.');if(!await authorized())throw new Error('Ingresá nuevamente para cambiar la contraseña.');const {error}=await db.auth.updateUser({password:f.elements.password.value});if(error)throw error;f.reset();status('Contraseña actualizada. Usala para tu próximo ingreso.');});};
