(() => {
 'use strict';
 const client=window.sionClient, $=s=>document.querySelector(s);
 const login=$('#login'), manager=$('#manager');let version=1, gallery=[], busy=false;
 const text=(id,value)=>$(id).textContent=value;
 function lock(form,value){form.querySelectorAll('button,input').forEach(x=>x.disabled=value)}
 async function start(){
  if(!client){text('#login-status','No se pudo conectar. Recargá la página.');return}
  try{
   const {data,error}=await client.auth.getUser();if(error||!data.user)return;
   const allowed=await client.from('sion_managers').select('user_id').eq('user_id',data.user.id).maybeSingle();
   if(allowed.error||!allowed.data){await client.auth.signOut();throw Error('Esta cuenta no tiene acceso a Siondrinks.')}
   await loadSettings();await loadGallery();login.hidden=true;manager.hidden=false;
  }catch(e){text('#login-status',e.message||'No se pudo cargar el panel.');}
 }
 async function loadSettings(){const r=await client.from('sion_settings').select('*').eq('id',true).single();if(r.error)throw Error('No se pudo cargar la configuración.');const f=$('#settings-form');f.elements.instagram.value=r.data.instagram;f.elements.whatsapp.value=r.data.whatsapp;f.elements.youtube.value='https://www.youtube.com/watch?v='+r.data.youtube_id;version=r.data.version}
 async function loadGallery(){const r=await client.from('sion_gallery').select('*').order('position').order('created_at');if(r.error)throw Error('No se pudo cargar la galería.');gallery=r.data;renderGallery()}
 function renderGallery(){const list=$('#gallery-list');list.replaceChildren();for(const item of gallery){
  const card=document.createElement('article');card.className='photo';const img=document.createElement('img');img.src=item.src;img.alt=item.caption;img.loading='lazy';card.append(img);
  const caption=document.createElement('input');caption.value=item.caption;caption.maxLength=140;const order=document.createElement('input');order.type='number';order.min=0;order.max=9999;order.value=item.position;
  for(const [label,input] of [['Texto de la foto',caption],['Orden',order]]){const l=document.createElement('label');l.textContent=label;l.append(input);card.append(l)}
  const actions=document.createElement('div');actions.className='photo-actions';const save=document.createElement('button');save.textContent='Guardar';save.className='secondary';const remove=document.createElement('button');remove.textContent='Retirar foto';remove.className='danger';actions.append(save,remove);card.append(actions);list.append(card);
  save.onclick=async()=>{if(busy)return;const n=Number(order.value);if(!Number.isInteger(n)||n<0||n>9999){text('#gallery-status','Indicá un orden entre 0 y 9999.');return}busy=true;lock(card,true);try{const r=await client.from('sion_gallery').update({caption:caption.value.trim(),position:n}).eq('id',item.id).select('id');if(r.error||!r.data.length)throw Error();await loadGallery();text('#gallery-status','Foto actualizada.')}catch{text('#gallery-status','No se pudo guardar la foto. Intentá nuevamente.')}finally{busy=false;lock(card,false)}};
  remove.onclick=async()=>{if(busy||!confirm('¿Retirar esta foto de la galería pública?'))return;busy=true;lock(card,true);try{const r=await client.from('sion_gallery').delete().eq('id',item.id).select('id');if(r.error||!r.data.length)throw Error();if(item.storage_path){const d=await client.storage.from('sion-gallery').remove([item.storage_path]);if(d.error)text('#gallery-status','Foto retirada. El archivo no pudo limpiarse del almacenamiento.')}await loadGallery();text('#gallery-status','Foto retirada de la galería.')}catch{text('#gallery-status','No se pudo retirar la foto.')}finally{busy=false;lock(card,false)}};
 }if(!gallery.length){const p=document.createElement('p');p.textContent='Todavía no hay fotos. Cargá las primeras imágenes.';list.append(p)}}
 $('#login-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;lock(f,true);text('#login-status','Ingresando…');try{if(!client)throw Error('No se pudo conectar. Recargá la página.');const r=await fetch(SION.url+'/functions/v1/sion-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:f.elements.username.value.trim(),password:f.elements.password.value})});if(!r.ok)throw Error(r.status===401?'Usuario o contraseña incorrectos.':'No se pudo iniciar sesión. Intentá nuevamente.');const tokens=await r.json();const auth=await client.auth.setSession(tokens);if(auth.error)throw Error('No se pudo iniciar sesión.');f.elements.password.value='';text('#login-status','');await start()}catch(e){text('#login-status',e.message||'No se pudo conectar.')}finally{lock(f,false)}};
 $('#logout').onclick=async()=>{if(busy)return;await client.auth.signOut();manager.hidden=true;login.hidden=false;text('#login-status','Sesión cerrada.');};
 $('#settings-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=e.currentTarget;let instagram;try{const u=new URL(f.elements.instagram.value.trim());if(u.protocol!=='https:'||!['instagram.com','www.instagram.com'].includes(u.hostname)||!u.pathname.slice(1))throw Error();instagram=u.href}catch{text('#settings-status','Ingresá un enlace válido de Instagram con https://.');return}const whatsapp=f.elements.whatsapp.value.replace(/\D/g,'');if(!/^\d{8,15}$/.test(whatsapp)){text('#settings-status','Revisá el WhatsApp e incluí el código de país.');return}const youtube_id=sionVideoId(f.elements.youtube.value.trim());if(!youtube_id){text('#settings-status','Ingresá el enlace de un video de YouTube.');return}busy=true;lock(f,true);text('#settings-status','Guardando…');try{const r=await client.from('sion_settings').update({instagram,whatsapp,youtube_id,version:version+1}).eq('id',true).eq('version',version).select('version');if(r.error)throw Error('No se pudieron guardar los cambios.');if(!r.data.length){await loadSettings();throw Error('La configuración cambió en otra sesión. Se cargó la versión actual; revisala y guardá de nuevo.')}version=r.data[0].version;text('#settings-status','Cambios guardados. Se verán al abrir o recargar la web.')}catch(e){text('#settings-status',e.message)}finally{busy=false;lock(f,false)}};
 async function optimize(file){const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('No se pudo procesar la foto.')),'image/webp',.88))}finally{bitmap.close()}}
 $('#upload-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=e.currentTarget,files=[...f.elements.photos.files];if(files.length>10||files.some(x=>!['image/jpeg','image/png','image/webp'].includes(x.type)||x.size>8*1024*1024)){text('#upload-status','Elegí hasta 10 fotos JPG, PNG o WebP, de hasta 8 MB cada una.');return}busy=true;lock(f,true);let completed=0;try{let next=Math.max(-1,...gallery.map(x=>x.position))+1;for(const file of files){text('#upload-status',`Cargando foto ${completed+1} de ${files.length}…`);const blob=await optimize(file),path=crypto.randomUUID()+'.webp';const upload=await client.storage.from('sion-gallery').upload(path,blob,{contentType:'image/webp',upsert:false});if(upload.error)throw Error('No se pudo cargar '+file.name);const src=client.storage.from('sion-gallery').getPublicUrl(path).data.publicUrl;const row=await client.from('sion_gallery').insert({src,storage_path:path,caption:file.name.replace(/\.[^.]+$/,'').slice(0,140),position:next++});if(row.error){await client.storage.from('sion-gallery').remove([path]);throw Error('No se pudo agregar '+file.name+' a la galería.')}completed++}f.reset();text('#upload-status',`${completed} foto(s) agregada(s) a la galería.`)}catch(e){text('#upload-status',`${completed} foto(s) guardada(s). ${e.message} Revisá la galería antes de reintentar.`)}finally{try{await loadGallery()}catch{text('#gallery-status','Recargá el panel para actualizar la galería.')}busy=false;lock(f,false)}};
 start();
})();
