const enc=new TextEncoder();
const hex=(a:ArrayBuffer)=>Array.from(new Uint8Array(a),x=>x.toString(16).padStart(2,'0')).join('');
const unhex=(s:string)=>new Uint8Array(s.match(/../g)!.map(x=>parseInt(x,16)));
const digest=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
const allowed=new Set(['https://cvstudio.com.ar','https://www.cvstudio.com.ar','https://cvstudio-ar.github.io']);
async function db(path:string,method='GET',body?:unknown,headers:Record<string,string>={}){const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const r=await fetch(Deno.env.get('SUPABASE_URL')+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error('Database request failed');const text=await r.text();return text?JSON.parse(text):null;}
function validContent(c:any){if(!c||typeof c!=='object'||Array.isArray(c)||JSON.stringify(c).length>800000)return false;for(const k of ['heroTitle','heroText','heroNote','about','podcastIntro','membershipText'])if(typeof c[k]!=='string'||c[k].length>10000)return false;if(!Array.isArray(c.spaces)||c.spaces.length!==5||c.spaces.some((s:any)=>!s||['title','description','detail'].some(k=>typeof s[k]!=='string'||s[k].length>10000)))return false;if(!Array.isArray(c.episodes)||c.episodes.length>40||c.episodes.some((e:any)=>!e||['title','url','cover'].some(k=>typeof e[k]!=='string'||e[k].length>10000)||e.url&&!/^https:\/\//.test(e.url)||e.cover&&!/^https:\/\//.test(e.cover)))return false;if(c.seasons!==undefined&&(!Array.isArray(c.seasons)||c.seasons.length>40||c.seasons.some((s:any)=>!s||typeof s.title!=='string'||s.title.length>250||typeof s.description!=='string'||s.description.length>10000)||new Set(c.seasons.map((s:any)=>s.title)).size!==c.seasons.length))return false;if(c.episodes.some((e:any)=>e.season!==undefined&&(typeof e.season!=='string'||e.season.length>250||c.seasons&&!c.seasons.some((s:any)=>s.title===e.season))))return false;if(!Array.isArray(c.articles)||c.articles.length>40||c.articles.some((a:any)=>!a||typeof a.title!=='string'||typeof a.body!=='string'||a.title.length>250||a.body.length>25000))return false;if(c.logo&&(!/^https:\/\//.test(c.logo)&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(c.logo)))return false;return true;}
Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin')||'';const headers:Record<string,string>={'Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS'};if(allowed.has(origin))headers['Access-Control-Allow-Origin']=origin;const respond=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers});if(origin&&!allowed.has(origin))return respond({error:'Origen no permitido.'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});try{const url=new URL(req.url);const action=url.searchParams.get('action')||'content';if(action==='content'&&req.method==='GET'){const rows=await db('psico_site_content?key=eq.main&select=content,revision,updated_at');return respond(rows[0]||{content:null,revision:0});}
if(action==='login'&&req.method==='POST'){if(Number(req.headers.get('content-length')||0)>4096)return respond({error:'Solicitud inválida.'},413);const body=await req.json();if(typeof body.username!=='string'||typeof body.password!=='string'||body.username.length>80||body.password.length>200)return respond({error:'Credenciales inválidas.'},400);const ip=(req.headers.get('x-forwarded-for')||req.headers.get('cf-connecting-ip')||'unknown').split(',')[0].trim();const ipHash=await digest('psico-login:'+ip);const since=new Date(Date.now()-15*60*1000).toISOString();await db('psico_login_attempts','POST',{ip_hash:ipHash},{Prefer:'return=minimal'});const attempts=await db('psico_login_attempts?ip_hash=eq.'+ipHash+'&attempted_at=gte.'+encodeURIComponent(since)+'&select=id&limit=10');if(attempts.length>8)return respond({error:'Demasiados intentos. Probá nuevamente en 15 minutos.'},429);const accounts=await db('psico_admin_accounts?username=eq.'+encodeURIComponent(body.username)+'&select=username,password_salt,password_hash,iterations');const account=accounts[0];const salt=account?unhex(account.password_salt):new Uint8Array(24);const key=await crypto.subtle.importKey('raw',enc.encode(body.password),'PBKDF2',false,['deriveBits']);const computed=hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:account?.iterations||210000,hash:'SHA-256'},key,256));const expected=account?.password_hash||'0'.repeat(64);let diff=0;for(let i=0;i<64;i++)diff|=computed.charCodeAt(i)^expected.charCodeAt(i);if(!account||diff)return respond({error:'Usuario o contraseña incorrectos.'},401);const random=crypto.getRandomValues(new Uint8Array(32));const token=hex(random.buffer);const expires_at=new Date(Date.now()+8*3600000).toISOString();await db('psico_admin_sessions','POST',{token_hash:await digest(token),username:account.username,expires_at},{Prefer:'return=minimal'});await db('psico_admin_sessions?expires_at=lt.'+encodeURIComponent(new Date().toISOString()),'DELETE');await db('psico_login_attempts?attempted_at=lt.'+encodeURIComponent(new Date(Date.now()-86400000).toISOString()),'DELETE');return respond({token,expires_at,username:account.username});}
const token=(req.headers.get('Authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))return respond({error:'Iniciá sesión para continuar.'},401);const tokenHash=await digest(token);const sessions=await db('psico_admin_sessions?token_hash=eq.'+tokenHash+'&expires_at=gt.'+encodeURIComponent(new Date().toISOString())+'&select=username');if(!sessions.length)return respond({error:'La sesión venció. Volvé a ingresar.'},401);
if(action==='logout'&&req.method==='POST'){await db('psico_admin_sessions?token_hash=eq.'+tokenHash,'DELETE');return respond({ok:true});}
if(action==='admin'&&req.method==='GET'){const rows=await db('psico_site_content?key=eq.main&select=content,revision,updated_at');return respond({...rows[0],username:sessions[0].username});}
if(action==='content'&&req.method==='PUT'){if(Number(req.headers.get('content-length')||0)>1000000)return respond({error:'El contenido es demasiado grande.'},413);const text=await req.text();if(text.length>1000000)return respond({error:'El contenido es demasiado grande.'},413);const body=JSON.parse(text);if(!validContent(body.content)||!Number.isInteger(body.revision))return respond({error:'Revisá los campos y enlaces. Usá direcciones HTTPS.'},400);const rows=await db('psico_site_content?key=eq.main&revision=eq.'+body.revision,'PATCH',{content:body.content,revision:body.revision+1,updated_at:new Date().toISOString()},{Prefer:'return=representation'});if(!rows.length)return respond({error:'Hay una versión más reciente. Recargá el panel antes de guardar.'},409);return respond({ok:true,revision:rows[0].revision,updated_at:rows[0].updated_at});}
return respond({error:'Ruta no encontrada.'},404);
}catch{return respond({error:'No pudimos completar la solicitud. Intentá nuevamente.'},500);}});
