'use strict';
(() => {
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const db=window.supabase.createClient('https://eqepkoegzyqklpxkrkhm.supabase.co','sb_publishable_k-VAklYxdMXQ8C2bun1WoA_N7M98apd',{auth:{storageKey:'mica-admin-session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
let products=[],settings={whatsapp:'5492964652318',headline:'Tu esencia. Tu estilo.',subtitle:'Perfumes e indumentaria para acompañar cada versión de vos.',instagram:''},filter='all',manager=false,editing=null,bag=[],toastTimer,previewURL;
try{bag=JSON.parse(localStorage.getItem('mica-selection')||'[]').filter(x=>typeof x.id==='string'&&typeof x.option==='string'&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=99).slice(0,50);}catch{bag=[]}
const money=v=>v===null||v===''||v===undefined?'Consultar precio':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(Number(v));
function el(tag, cls, text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function btn(text,cls,action){const n=el('button',cls,text);n.type='button';n.addEventListener('click',action);return n;}
function imageSrc(value,category='perfumes'){const fallback=category==='perfumes'?'assets/perfumes.webp':'assets/indumentaria.webp';if(!value)return fallback;if(/^assets\/[a-z0-9.-]+$/i.test(value))return value;try{const u=new URL(value);return u.protocol==='https:'?u.href:fallback}catch{return fallback}}
function img(value,alt,category){const n=el('img');n.src=imageSrc(value,category);n.alt=alt;n.loading='lazy';n.addEventListener('error',()=>{if(n.dataset.fallback)return;n.dataset.fallback='1';n.src=imageSrc('',category)});return n;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200)}
function show(id){const d=$(id);if(!d.open)d.showModal()}
function closeMenu(){ $('nav').classList.remove('open');$('#menuButton').setAttribute('aria-expanded','false') }
function openWA(text){const n=String(settings.whatsapp).replace(/\D/g,'');window.open('https://wa.me/'+n+'?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')}
const generalWA=()=>openWA('Hola, vi la demo de MICA en CVStudio y me gustaría hacer una consulta sobre perfumes e indumentaria.');
function applySettings(){const parts=settings.headline.split(/\.\s*/).filter(Boolean);const h=$('#headline');h.replaceChildren();parts.forEach((v,i)=>{h.append(document.createTextNode(v+'.'));if(i<parts.length-1)h.append(el('br'))});$('#subtitle').textContent=settings.subtitle;const link=$('#instagramLink');try{const u=new URL(settings.instagram);if(u.protocol==='https:'&&(u.hostname==='instagram.com'||u.hostname==='www.instagram.com')){link.href=u.href;link.hidden=false}else link.hidden=true}catch{link.hidden=true}}
async function loadSettings(){const {data,error}=await db.from('mica_settings').select('*').eq('id','main').single();if(error)throw error;settings=data;applySettings()}
async function loadProducts(){const {data,error}=await db.from('mica_products').select('*').order('sort_order').order('created_at');if(error)throw error;products=data;updateCount();return data}
function publicProducts(){return products.filter(p=>p.active)}
function saveBag(){try{localStorage.setItem('mica-selection',JSON.stringify(bag))}catch{}updateCount()}
function updateCount(){ $('#bagCount').textContent=bag.reduce((s,x)=>s+x.qty,0);$('#bagButton').setAttribute('aria-label','Ver mi selección, '+$('#bagCount').textContent+' artículos') }
function productPrice(p){const n=el('div','price',money(p.price));if(p.price!==null)n.append(el('span','price-note',' · precio de ejemplo'));return n}
function renderCatalog(){const query=$('#search').value.trim().toLocaleLowerCase('es');let list=publicProducts().filter(p=>(filter==='all'||p.category===filter)&&[p.name,p.description,p.options].join(' ').toLocaleLowerCase('es').includes(query));const sort=$('#sort').value;list.sort((a,b)=>sort==='asc'?(a.price??Infinity)-(b.price??Infinity):sort==='desc'?(b.price??-1)-(a.price??-1):sort==='name'?a.name.localeCompare(b.name,'es'):Number(b.featured)-Number(a.featured)||a.sort_order-b.sort_order);$('#products').replaceChildren();$('#catalogStatus').textContent=list.length+' producto'+(list.length===1?'':'s')+' en la colección';$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));if(!list.length){const empty=el('div','empty');empty.append(el('h3','',query?'No encontramos ese favorito':'Estamos preparando la colección'),el('p','muted',query?'Probá con otro nombre o categoría.':'Volvé pronto para conocer las novedades.'));if(query)empty.append(btn('Limpiar búsqueda','button light',()=>{$('#search').value='';filter='all';renderCatalog()}));$('#products').append(empty);return}list.forEach(p=>{const c=el('article','product-card');const photo=btn('','product-image',()=>openProduct(p.id));photo.setAttribute('aria-label','Ver '+p.name);photo.append(img(p.image_url,p.name,p.category));if(p.featured||!p.available)photo.append(el('span','badge',!p.available?'Sin disponibilidad':'Destacado'));const body=el('div','product-card-body');body.append(el('div','product-kicker',p.category),el('h3','',p.name),productPrice(p),btn('Ver detalles →','button light',()=>openProduct(p.id)));c.append(photo,body);$('#products').append(c)})}
async function openCatalog(category='all'){closeMenu();filter=category;$('#search').value='';show('#catalogDialog');$('#catalogStatus').textContent='Actualizando la colección…';if(products.length)renderCatalog();else $('#products').replaceChildren(...[1,2,3].map(()=>el('div','loading-card')));try{await loadProducts();renderCatalog()}catch{$('#products').replaceChildren();$('#catalogStatus').textContent='No pudimos cargar la colección. Revisá tu conexión.';$('#products').append(btn('Volver a intentar','button light',()=>openCatalog(filter)))}}
function openProduct(id){const p=publicProducts().find(x=>x.id===id);if(!p)return;const box=$('#productDetail');box.replaceChildren();box.append(img(p.image_url,p.name,p.category));box.firstChild.className='detail-image';box.append(el('p','eyebrow',p.category),el('h2','',p.name),productPrice(p),el('p','detail-stock'+(!p.available?' unavailable':''),p.available?'Disponible para consultar':'Consultar próxima disponibilidad'),el('p','detail-description',p.description));let optionSelect;const options=p.options.split(',').map(x=>x.trim()).filter(Boolean);if(options.length){const label=el('label','detail-options',p.category==='perfumes'?'Presentación':'Talle / opción');optionSelect=el('select');options.forEach(x=>{const opt=el('option','',x);opt.value=x;optionSelect.append(opt)});label.append(optionSelect);box.append(label)}const actions=el('div','detail-actions');const ask=()=>openWA('Hola, vi '+p.name+' en la demo de MICA. '+(optionSelect?'Opción: '+optionSelect.value+'. ':'')+'¿Me confirmás precio y disponibilidad?');actions.append(btn('Consultar por WhatsApp','button whatsapp',ask));if(p.available)actions.append(btn('♡ Agregar a mi selección','button light',()=>{addBag(p,optionSelect?.value||'');}));box.append(actions,el('p','demo-note','Producto e imagen ilustrativos. La consulta no confirma una compra.'));show('#productDialog')}
function addBag(p,option){const item=bag.find(x=>x.id===p.id&&x.option===option);if(item){if(item.qty>=99)return toast('Máximo 99 unidades');item.qty++}else{if(bag.length>=50)return toast('Tu selección tiene el máximo de productos');bag.push({id:p.id,option,qty:1})}saveBag();toast('Agregado a tu selección')}
function currentBag(){return bag.map((x,i)=>({...x,index:i,product:publicProducts().find(p=>p.id===x.id)}))}
function renderBag(){const box=$('#bagItems'),summary=$('#bagSummary');box.replaceChildren();summary.replaceChildren();summary.className='bag-summary';if(!bag.length){box.append(el('div','empty','Tu selección está esperando tus favoritos.'),btn('Explorar la colección','button light',()=>{$('#bagDialog').close();openCatalog()}));return}const list=currentBag();list.forEach(x=>{const row=el('div','bag-item');if(x.product)row.append(img(x.product.image_url,x.product.name,x.product.category));const body=el('div','bag-item-body');body.append(el('h3','',x.product?.name||'Producto ya no disponible'),el('p','muted',(x.option?x.option+' · ':'')+(x.product?money(x.product.price):'Quitalo de la selección')));if(x.product&&!x.product.available)body.append(el('p','muted','Consultar disponibilidad'));const quantity=el('div','quantity');quantity.append(btn('−','',()=>{if(bag[x.index].qty>1)bag[x.index].qty--;else bag.splice(x.index,1);saveBag();renderBag()}),el('span','',x.qty),btn('+','',()=>{bag[x.index].qty=Math.min(99,bag[x.index].qty+1);saveBag();renderBag()}));body.append(quantity);row.append(body,btn('Quitar','text-link',()=>{bag.splice(x.index,1);saveBag();renderBag()}));box.append(row)});const total=list.reduce((s,x)=>s+(x.product?.price||0)*x.qty,0);const totalRow=el('div','bag-total');totalRow.append(el('span','','Total orientativo'),el('strong','',money(total)));summary.append(totalRow,el('p','muted','Precios de demostración. '+(list.some(x=>!x.product||x.product.price===null)?'Hay artículos sin precio o sin disponibilidad. ':'')+'Confirmá el total y la disponibilidad antes de comprar.'));const ask=btn('Consultar mi selección por WhatsApp','button whatsapp',()=>{const valid=currentBag().filter(x=>x.product);if(!valid.length)return toast('Elegí un producto de la colección');openWA('Hola, vi la demo de MICA. Quisiera consultar precio y disponibilidad de:\n'+valid.map(x=>`• ${x.qty} × ${x.product.name}${x.option?' ('+x.option+')':''}`).join('\n')+'\nGracias.');});ask.disabled=!list.some(x=>x.product);summary.append(ask)}
function message(text,error=false,target='#adminMessage'){const n=$(target);n.textContent=text;n.classList.toggle('error',error)}
async function authorized(){const {data:{user},error}=await db.auth.getUser();if(error||!user)return false;const {data,error:err}=await db.from('mica_managers').select('user_id').eq('user_id',user.id).maybeSingle();if(err)throw err;return !!data}
async function openAdmin(){closeMenu();show('#adminDialog');message('',false,'#loginError');try{manager=await authorized();$('#loginForm').hidden=manager;$('#adminContent').hidden=!manager;if(manager){await loadProducts();renderAdmin();fillSettings()}}catch{message('No pudimos verificar tu acceso. Intentá nuevamente.',true,'#loginError')}}
function fillSettings(){const f=$('#settingsForm');['whatsapp','instagram','headline','subtitle'].forEach(k=>f.elements[k].value=settings[k]||'')}
function renderAdmin(){const stats=$('#adminStats');stats.replaceChildren();[[products.length,'Productos'],[products.filter(p=>p.active).length,'Visibles'],[products.filter(p=>p.featured).length,'Destacados']].forEach(([v,t])=>{const n=el('div','stat');n.append(el('strong','',v),el('span','',t));stats.append(n)});const list=$('#adminList');list.replaceChildren();products.forEach(p=>{const row=el('div','admin-row');const body=el('div','admin-row-body');body.append(el('h4','',p.name),el('p','',`${p.category} · ${money(p.price)} · ${p.active?'Visible':'Oculto'} · ${p.available?'Disponible':'Sin disponibilidad'}`));const actions=el('div','row-actions');actions.append(btn('Editar','text-link',()=>editProduct(p)),btn('Eliminar','text-link danger',()=>deleteProduct(p)));row.append(img(p.image_url,p.name,p.category),body,actions);list.append(row)});if(!products.length)list.append(el('p','muted','Agregá tu primer producto para comenzar.'))}
function backToList(){ $('#productForm').hidden=true;$('#adminProducts').hidden=false;editing=null;message('');if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null} }
function editProduct(p=null){editing=p;message('');const f=$('#productForm');f.reset();['name','category','description','price','image_url','options','sort_order'].forEach(k=>f.elements[k].value=p?.[k]??(k==='category'?'perfumes':k==='sort_order'?'0':''));['available','featured','active'].forEach(k=>f.elements[k].checked=p?p[k]:k!=='featured');$('#imagePreview').src=imageSrc(p?.image_url,p?.category);$('#editorTitle').textContent=p?'Editar producto':'Nuevo producto';$('#adminProducts').hidden=true;$('#settingsForm').hidden=true;f.hidden=false;f.elements.name.focus()}
async function removeOwnedImage(url){const prefix='https://eqepkoegzyqklpxkrkhm.supabase.co/storage/v1/object/public/mica-products/';if(!url?.startsWith(prefix))return;const {data,error}=await db.from('mica_products').select('id').eq('image_url',url).limit(1);if(!error&&!data.length)await db.storage.from('mica-products').remove([decodeURIComponent(url.slice(prefix.length))])}
async function deleteProduct(p){if(!confirm('¿Eliminar “'+p.name+'” del catálogo? Esta acción no se puede deshacer.'))return;try{const {data,error}=await db.from('mica_products').delete().eq('id',p.id).eq('updated_at',p.updated_at).select('id');if(error)throw error;if(!data.length)throw new Error('El producto cambió en otra sesión. Actualizá el panel antes de eliminarlo.');await removeOwnedImage(p.image_url);await loadProducts();renderAdmin();message('Producto eliminado.');if($('#catalogDialog').open)renderCatalog()}catch(e){message(e.message||'No pudimos eliminar el producto.',true)}}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>openCatalog(b.dataset.category)));$$('[data-home]').forEach(b=>b.addEventListener('click',closeMenu));$$('[data-contact]').forEach(b=>b.addEventListener('click',()=>{closeMenu();show('#contactDialog')}));$('#menuButton').addEventListener('click',()=>{const open=$('nav').classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',String(open))});$('#brand').addEventListener('click',openAdmin);$('#heroWhatsApp').addEventListener('click',generalWA);$('#contactWhatsApp').addEventListener('click',generalWA);$('#bagButton').addEventListener('click',async()=>{show('#bagDialog');try{await loadProducts()}catch{toast('No pudimos actualizar la disponibilidad')}renderBag()});$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;renderCatalog()}));$('#search').addEventListener('input',renderCatalog);$('#sort').addEventListener('change',renderCatalog);$('#newProduct').addEventListener('click',()=>editProduct());$('#cancelEdit').addEventListener('click',backToList);
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{message('');$('#productForm').hidden=true;$('#adminProducts').hidden=b.dataset.tab!=='products';$('#settingsForm').hidden=b.dataset.tab!=='settings';$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));fillSettings()}));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,button=$('button',f);button.disabled=true;message('',false,'#loginError');try{const {error}=await db.auth.signInWithPassword({email:f.elements.email.value.trim(),password:f.elements.password.value});if(error)throw new Error('Correo o contraseña incorrectos.');manager=await authorized();if(!manager){await db.auth.signOut();throw new Error('Esta cuenta no tiene acceso al panel de MICA.')}f.elements.password.value='';f.hidden=true;$('#adminContent').hidden=false;await Promise.all([loadProducts(),loadSettings()]);renderAdmin();fillSettings();message('Sesión iniciada.')}catch(e){message(e.message||'No pudimos iniciar sesión.',true,'#loginError')}finally{button.disabled=false}});
$('#signOut').addEventListener('click',async()=>{const {error}=await db.auth.signOut();if(error)return message('No pudimos cerrar sesión. Intentá nuevamente.',true);manager=false;$('#adminContent').hidden=true;$('#loginForm').hidden=false;$('#loginForm').reset();await loadProducts().catch(()=>{});toast('Sesión cerrada')});
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=$('button',f);b.disabled=true;message('Guardando…');try{const instagram=f.elements.instagram.value.trim();if(instagram){const u=new URL(instagram);if(u.protocol!=='https:'||!['instagram.com','www.instagram.com'].includes(u.hostname))throw new Error('Ingresá un enlace válido de Instagram.')}const payload={whatsapp:f.elements.whatsapp.value.trim(),instagram,headline:f.elements.headline.value.trim(),subtitle:f.elements.subtitle.value.trim(),updated_at:new Date().toISOString()};if(!payload.headline||!payload.subtitle)throw new Error('Completá el título y la presentación.');const {data,error}=await db.from('mica_settings').update(payload).eq('id','main').eq('updated_at',settings.updated_at).select().single();if(error)throw new Error('No pudimos guardar. Si otra sesión editó estos datos, cerrá y abrí el panel.');settings=data;applySettings();message('Cambios guardados y publicados.')}catch(e){message(e.message||'No pudimos guardar los cambios.',true)}finally{b.disabled=false}});
$('#productForm').elements.photo.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880){e.target.value='';return message('Elegí una imagen JPG, PNG o WebP de hasta 5 MB.',true)}if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);$('#imagePreview').src=previewURL});$('#productForm').elements.image_url.addEventListener('change',e=>{$('#imagePreview').src=imageSrc(e.target.value,$('#productForm').elements.category.value)});
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type=submit]',f);b.disabled=true;message('Guardando producto…');let uploaded;try{let url=f.elements.image_url.value.trim();if(url&&!/^assets\/[a-z0-9.-]+$/i.test(url)){const u=new URL(url);if(u.protocol!=='https:')throw new Error('El enlace de imagen debe comenzar con https://.')}const file=f.elements.photo.files[0];if(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw new Error('La imagen debe ser JPG, PNG o WebP de hasta 5 MB.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];uploaded=crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('mica-products').upload(uploaded,file,{contentType:file.type,upsert:false});if(error)throw new Error('No pudimos subir la imagen. Intentá nuevamente.');url=db.storage.from('mica-products').getPublicUrl(uploaded).data.publicUrl;}const payload={name:f.elements.name.value.trim(),category:f.elements.category.value,description:f.elements.description.value.trim(),price:f.elements.price.value===''?null:Number(f.elements.price.value),image_url:url,options:f.elements.options.value.trim(),sort_order:Number(f.elements.sort_order.value),available:f.elements.available.checked,featured:f.elements.featured.checked,active:f.elements.active.checked,updated_at:new Date().toISOString()};if(!payload.name)throw new Error('Ingresá el nombre del producto.');const query=editing?db.from('mica_products').update(payload).eq('id',editing.id).eq('updated_at',editing.updated_at):db.from('mica_products').insert(payload);const {data,error}=await query.select().single();if(error||!data)throw new Error('No pudimos guardar el producto. Revisá tu conexión o si cambió en otra sesión.');const old=editing?.image_url;uploaded=null;await loadProducts();renderAdmin();backToList();message('Producto guardado y catálogo actualizado.');if(old&&old!==url)await removeOwnedImage(old);if($('#catalogDialog').open)renderCatalog()}catch(e){if(uploaded)await db.storage.from('mica-products').remove([uploaded]);message(e.message||'No pudimos guardar el producto.',true)}finally{b.disabled=false}});
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){manager=false;$('#adminContent').hidden=true;$('#loginForm').hidden=false}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadSettings().catch(()=>{})});updateCount();loadSettings().catch(()=>toast('Conexión temporalmente no disponible.'));loadProducts().catch(()=>{});
})();
