'use strict';
const locationText='Bv. Vélez Sarsfield 3344 · Santa Fe';
const projectDescription='<p>Altos de Sarsfield se ubica en Barrio Candioti, a pocos metros de Bv. Gálvez y cerca de la costanera, el puente colgante y el polo gastronómico de la ciudad. El proyecto contempla una fachada de diseño propio, ingreso magnético, sensores lumínicos en palieres y ascensor de última generación.</p>';
const properties = [
 {id:1,name:'Altos de Sarsfield',type:'departamento',operation:'pozo',location:'santa-fe',image:'altos-exterior',rooms:'1 y 3 dorm.',area:'48 y 99 m²',feature:'SUM y terraza',description:projectDescription+'<p>Dos tipologías: semipisos de un dormitorio en plantas 1 a 8 y pisos completos de tres dormitorios en plantas 9 a 12.</p><ul><li>SUM con dos asadores, dos baños y espacios que pueden integrarse para reuniones de hasta 25 personas.</li><li>Terraza con patio seco, vistas a la ciudad y solárium húmedo con cascada.</li><li>Siete cocheras en planta baja, de 2,5 m de ancho.</li></ul>',gallery:['altos-fachada','altos-lobby','altos-sum','altos-terraza']},
 {id:2,name:'Altos · 1 dormitorio',type:'departamento',operation:'pozo',location:'santa-fe',image:'altos-1-dormitorio',rooms:'1 dormitorio',area:'48 m²',feature:'2 balcones',description:'<p>Semipisos de un dormitorio, dos unidades por piso entre las plantas 1 y 8. Estar-comedor con cocina semisectorizada y barra, balcón al frente con orientación oeste y balcón al contrafrente con orientación este.</p><ul><li>Ventilación cruzada y dormitorio con placard empotrado.</li><li>Cocina equipada con anafe, campana, calefactor y calefón a gas.</li><li>Mesada de granito, aberturas línea Módena y porcelanato símil madera.</li><li>Paredes terminadas en yeso, iluminación LED y griferías de alta prestación.</li></ul>',gallery:['altos-cocina','altos-dormitorio','altos-lobby','altos-terraza']},
 {id:3,name:'Altos · 3 dormitorios',type:'departamento',operation:'pozo',location:'santa-fe',image:'altos-3-dormitorios',rooms:'3 dormitorios',area:'99 m²',feature:'4 balcones',description:'<p>Pisos completos de tres dormitorios entre las plantas 9 y 12. Amplio estar-comedor, cocina integrada y equipada, ventilación cruzada y cuatro balcones con orientación este y oeste.</p><ul><li>Baño en suite y dormitorio principal con placard empotrado.</li><li>Cocina con alacenas, bajo mesada, campana, calefón, anafe y calefactor.</li><li>Barra en L y distribución que preserva la privacidad del sector íntimo.</li><li>Acceso a los espacios comunes del desarrollo.</li></ul>',gallery:['altos-cocina','altos-sum','altos-terraza','altos-ingreso']},
 {id:4,name:'Departamento con balcón',type:'departamento',operation:'venta',location:'pending',image:'property-4',sample:true},
 {id:5,name:'Dúplex contemporáneo',type:'duplex',operation:'pozo',location:'pending',image:'property-5',sample:true},
 {id:6,name:'Nuevo desarrollo',type:'departamento',operation:'pozo',location:'pending',image:'property-6',sample:true}
];
const icons = {
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
 pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 rooms:'<path d="M3 3h18v18H3zM12 3v8H3m9 0h9M12 11v10M3 15h5"/>',
 area:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m6 0h6v-6"/>',
 star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',
 wa:'<path d="M21 11.5a9 9 0 0 1-13.6 7.7L3 21l1.8-4.3A9 9 0 1 1 21 11.5Z"/><path d="M8 7c.4-.4.7-.2 1 .4l1 2-1 1c.5 1.5 1.8 2.7 3.4 3.2l1-1 2 .9c.6.3.8.6.4 1-1 1.3-2 1.4-3.9.7C10.3 15.1 8 12.8 7.5 10.2 7.2 8.8 7.4 7.8 8 7Z"/>'
};
const svg = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
let favorites = new Set();
try { const saved=JSON.parse(localStorage.getItem('enpozo-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved.filter(n=>properties.some(p=>p.id===n))); } catch (_) {}
let activeFilter='all',searchType='all',searchOperation='all',searchLocation='all';
const grid=document.getElementById('property-grid');
function contact(name){return `https://wa.me/5493425669944?text=${encodeURIComponent('Hola, quiero consultar por '+name+' que vi en En Pozo PROP.')}`;}
function render(){
 let items=properties.filter(p=>(activeFilter==='all'||p.type===activeFilter||p.operation===activeFilter)&&(searchType==='all'||p.type===searchType)&&(searchOperation==='all'||searchOperation==='venta'||p.operation===searchOperation)&&(searchLocation==='all'||p.location===searchLocation));
 const sort=document.getElementById('sort').value;
 if(sort==='name')items.sort((a,b)=>a.name.localeCompare(b.name,'es'));
 if(sort==='favorites')items.sort((a,b)=>Number(favorites.has(b.id))-Number(favorites.has(a.id)));
 grid.innerHTML=items.map(p=>`<article class="card"><div class="card-photo"><img src="assets/${p.image}.webp" alt="Imagen ilustrativa: ${p.name}" width="480" height="300" loading="lazy">${p.sample?'':'<span class="property-tag">En pozo</span>'}<button class="favorite" data-favorite="${p.id}" aria-label="${favorites.has(p.id)?'Quitar de':'Agregar a'} favoritas: ${p.name}" aria-pressed="${favorites.has(p.id)}">${svg('heart')}</button></div><div class="card-body"><h3>${p.name}</h3>${p.sample?'<span class="sample-note">Propiedad de muestra · Imagen ilustrativa</span>':''}<p class="location">${svg('pin')}${p.sample?'Ubicación a confirmar':locationText}</p><div class="features"><span>${svg('rooms')}${p.rooms||'Ambientes'}</span><span>${svg('area')}${p.area||'Superficie'}</span><span>${svg('star')}${p.feature||'Características'}</span></div><div class="card-bottom"><span class="price">Consultar precio</span><button class="view" data-view="${p.id}">Ver propiedad <span aria-hidden="true">⟶</span></button><a class="card-wa" href="${contact(p.name)}" target="_blank" rel="noopener" aria-label="Consultar por WhatsApp: ${p.name}">${svg('wa')}</a></div></div></article>`).join('');
 document.getElementById('empty').hidden=items.length>0;
}
function filter(value){activeFilter=value;searchType='all';searchOperation='all';searchLocation='all';document.querySelectorAll('[data-filter]').forEach(b=>{const on=b.dataset.filter===value;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});document.getElementById('catalog-status').hidden=true;render();}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));
document.querySelectorAll('[data-nav-filter]').forEach(a=>a.addEventListener('click',()=>filter(a.dataset.navFilter)));
document.getElementById('search-form').addEventListener('submit',e=>{e.preventDefault();filter('all');searchType=document.getElementById('type').value;searchOperation=document.getElementById('operation').value;searchLocation=document.getElementById('location').value;render();document.getElementById('propiedades').scrollIntoView({behavior:'smooth'});});
document.getElementById('sort').addEventListener('change',render);
document.getElementById('reset').addEventListener('click',()=>{document.getElementById('type').value='all';document.getElementById('operation').value='all';document.getElementById('location').value='all';filter('all');});
const dialog=document.getElementById('property-dialog');
grid.addEventListener('click',e=>{const f=e.target.closest('[data-favorite]');if(f){const id=Number(f.dataset.favorite);favorites.has(id)?favorites.delete(id):favorites.add(id);try{localStorage.setItem('enpozo-favorites',JSON.stringify([...favorites]));}catch(_){}render();return;}const v=e.target.closest('[data-view]');if(v){const p=properties.find(p=>p.id===Number(v.dataset.view));document.getElementById('dialog-title').textContent=p.name;document.getElementById('dialog-image').src=`assets/${p.image}.webp`;document.getElementById('dialog-image').alt=`Imagen ilustrativa: ${p.name}`;document.getElementById('dialog-contact').href=contact(p.name);dialog.querySelector('.sample-label').textContent=p.sample?'Propiedad ilustrativa':'Altos de Sarsfield · Desarrollo en pozo';document.getElementById('dialog-location').textContent=p.sample?'Ubicación a confirmar':locationText;document.getElementById('dialog-description').innerHTML=p.description||'<p>Esta imagen forma parte del catálogo de muestra. Los datos, precios y características se incorporarán con la información de los proyectos reales.</p>';document.getElementById('dialog-gallery').innerHTML=(p.gallery||[]).map(name=>`<a href="assets/${name}.webp" target="_blank" rel="noopener" aria-label="Ampliar imagen del desarrollo"><img src="assets/${name}.webp" alt="Render ilustrativo de Altos de Sarsfield" loading="lazy"></a>`).join('');dialog.showModal();}});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.getElementById('more-properties').addEventListener('click',()=>{filter('all');document.getElementById('catalog-status').hidden=false;});
render();
