const URL=Deno.env.get('SUPABASE_URL')!;
let KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
try { KEY=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||KEY; } catch {}
const headers={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const origins=new Set(['https://cvstudio.com.ar','https://www.cvstudio.com.ar']);
async function db(path:string,method='GET',body?:unknown,extra={}) {const r=await fetch(URL+'/rest/v1/'+path,{method,headers:{...headers,...extra},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error('database');return r.status===204?null:await r.json();}
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
const text=(v:unknown,max:number,required=true)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw new Error('validation');return v.trim()};
function product(v:any){const p={name:text(v.name,70),brand:text(v.brand,32),model:text(v.model,150),description:text(v.description,1800),size:text(v.size,30),price:v.price,art:v.art,published:v.published!==false,cover:text(v.cover||'',500,false),category:text(v.category||'Ritmos',40),position:v.position||0};if(!Number.isFinite(p.price)||p.price<0||p.price>10000000||!Number.isInteger(p.art)||p.art<0||p.art>7||!Number.isInteger(p.position)||p.position<0||p.position>10000)throw new Error('validation');if(p.cover&&!p.cover.startsWith(URL+'/storage/v1/object/public/nicky-covers/'))throw new Error('validation');return p;}
Deno.serve(async(req)=>{const origin=req.headers.get('origin')||'';const cors={'Access-Control-Allow-Origin':origins.has(origin)?origin:'https://cvstudio.com.ar','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};const out=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}});
if(origin&&!origins.has(origin))return out({error:'Origen no autorizado'},403);
if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
try{
 if(req.method==='GET'){const products=await db('nicky_products?archived=eq.false&select=id,body,updated_at&order=id');const [settings]=await db('nicky_settings?id=eq.1&select=body,revision');return out({products:products.filter((p:any)=>p.body.published!==false).map((p:any)=>({...p.body,id:p.id,version:p.updated_at})),settings});}
 if(req.method!=='POST')return out({error:'Método no permitido'},405);
 if(Number(req.headers.get('content-length')||0)>1500000)return out({error:'Archivo demasiado grande'},413);
 const raw=await req.text();if(raw.length>1500000)return out({error:'Archivo demasiado grande'},413);const b=JSON.parse(raw);
 if(b.action==='login'){const user=text(b.username,80),password=text(b.password,128);const client=await hash((req.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim());const data=await db('rpc/nicky_admin_login','POST',{p_user:user,p_password:password,p_client:client});return data.error?out({error:data.error==='limit'?'Demasiados intentos. Esperá 15 minutos.':'Usuario o contraseña incorrectos'},data.error==='limit'?429:401):out(data);}
 const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))return out({error:'Ingresá a Administración para continuar'},401);
 const digest=await hash(token);const sessions=await db('nicky_admin_sessions?token_hash=eq.'+digest+'&expires_at=gt.'+encodeURIComponent(new Date().toISOString())+'&select=expires_at');if(!sessions.length)return out({error:'La sesión venció. Ingresá nuevamente.'},401);
 if(b.action==='logout'){await db('nicky_admin_sessions?token_hash=eq.'+digest,'DELETE');return out({ok:true});}
 if(b.action==='admin'){const products=await db('nicky_products?select=id,body,updated_at,archived&order=id');const [settings]=await db('nicky_settings?id=eq.1&select=body,revision');return out({products:products.map((p:any)=>({...p.body,id:p.id,version:p.updated_at,archived:p.archived})),settings});}
 if(b.action==='save'){const p=product(b.product);const id=b.product.id?text(b.product.id,80):crypto.randomUUID();const version=new Date().toISOString();let rows;if(b.product.id){const expected=text(b.product.version,60);rows=await db('nicky_products?id=eq.'+encodeURIComponent(id)+'&updated_at=eq.'+encodeURIComponent(expected),'PATCH',{body:p,updated_at:version},{Prefer:'return=representation'});if(!rows.length)return out({error:'El producto cambió en otra sesión. Actualizá el panel antes de guardar.'},409);}else rows=await db('nicky_products','POST',{id,body:p,updated_at:version},{Prefer:'return=representation'});return out({product:{...rows[0].body,id,version:rows[0].updated_at}});}
 if(b.action==='archive'||b.action==='restore'){const id=text(b.id,80),expected=text(b.version,60);const rows=await db('nicky_products?id=eq.'+encodeURIComponent(id)+'&updated_at=eq.'+encodeURIComponent(expected),'PATCH',{archived:b.action==='archive',updated_at:new Date().toISOString()},{Prefer:'return=representation'});if(!rows.length)return out({error:'El producto cambió. Actualizá el panel.'},409);return out({ok:true});}
 if(b.action==='settings'){const v=b.settings;const s={headline:text(v.headline,65),accent:text(v.accent,65),subtitle:text(v.subtitle,180),catalogTitle:text(v.catalogTitle,75)};const rows=await db('nicky_settings?id=eq.1&revision=eq.'+Number(b.revision),'PATCH',{body:s,revision:Number(b.revision)+1},{Prefer:'return=representation'});if(!rows.length)return out({error:'La configuración cambió. Actualizá antes de guardar.'},409);return out({settings:rows[0]});}
 if(b.action==='upload'){const mime=text(b.mime,30);if(!['image/jpeg','image/png','image/webp'].includes(mime))return out({error:'Usá JPG, PNG o WebP'},400);const bytes=Uint8Array.from(atob(text(b.data,1400000)),c=>c.charCodeAt(0));if(bytes.length>1048576)return out({error:'La portada debe pesar menos de 1 MB'},400);const sig=Array.from(bytes.slice(0,12));const valid=mime==='image/png'?sig.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':mime==='image/jpeg'?sig[0]===255&&sig[1]===216&&sig[2]===255:String.fromCharCode(...sig.slice(0,4))==='RIFF'&&String.fromCharCode(...sig.slice(8,12))==='WEBP';if(!valid)return out({error:'El archivo no es una imagen válida'},400);const path=crypto.randomUUID()+'.'+({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[mime]);const r=await fetch(URL+'/storage/v1/object/nicky-covers/'+path,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':mime},body:bytes});if(!r.ok)throw new Error('upload');return out({url:URL+'/storage/v1/object/public/nicky-covers/'+path});}
 return out({error:'Operación no disponible'},400);
}catch(e){return out({error:e instanceof Error&&e.message==='validation'?'Revisá los campos ingresados.':'No pudimos completar la operación. Intentá nuevamente.'},400);}
});
