(function(){
'use strict';
const KEY='cvstudio.collaborators.v1';
const LEVELS=['Aprendiz','Operario','Líder','Supervisor','Director'];
const DEFAULTS=[
{id:'pablexe',name:'pablexe',email:'pablexe@cvstudio.com.ar',level:'Director',commission:25,status:'Activo',birthday:'',joined:'2026-07-01'},
{id:'alejandro',name:'Alejandro Rojas',email:'alejandro@cvstudio.com.ar',level:'Operario',commission:15,status:'Activo',birthday:'1998-08-14',joined:'2026-07-01'},
{id:'valentina',name:'Valentina López',email:'valentina@cvstudio.com.ar',level:'Líder',commission:18,status:'Activo',birthday:'1997-08-27',joined:'2026-07-15'}];
const PERMS={Aprendiz:['General','Plantillas'],Operario:['General','Clientes','Plantillas'],Líder:['General','Clientes','Calendario','Plantillas','Generador URL'],Supervisor:['General','Clientes','Administración','Marketing','Calendario','Plantillas','Integraciones','Generador URL'],Director:['Todos los módulos','Configuración','Colaboradores','Permisos y seguridad']};
let rows=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||DEFAULTS}catch(e){return DEFAULTS}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(rows));
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
function render(){const active=rows.filter(x=>x.status==='Activo').length;return `<section class="grid kpi-grid"><section class="kpi-card"><span class="kpi-icon">👥</span><div><small>Colaboradores</small><strong>${rows.length}</strong><span class="trend">${active} activos</span></div></section><section class="kpi-card"><span class="kpi-icon">🪜</span><div><small>Jerarquía</small><strong>5 niveles</strong><span class="trend">Aprendiz → Director</span></div></section><section class="kpi-card"><span class="kpi-icon">🔐</span><div><small>Permisos</small><strong>Reales</strong><span class="trend">por nivel</span></div></section></section><section class="panel"><div class="panel-head"><div><h2>Gestión de colaboradores</h2><p>Edición completa, nivel, comisión, estado y permisos.</p></div><button class="button primary" data-collab-new>+ Nuevo colaborador</button></div><div class="hierarchy-strip">${LEVELS.map((l,i)=>`<span><b>${i+1}</b>${l}</span>`).join('')}</div><div class="collab-functional-list">${rows.map(x=>`<article class="collab-functional-row"><span class="client-avatar">${x.name.split(' ').map(p=>p[0]).slice(0,2).join('').toUpperCase()}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.email)}</small></div><span class="status" style="--c:${['#64748b','#3b82f6','#9b5de5','#ff8a1f','#ffd23f'][LEVELS.indexOf(x.level)]}">${x.level}</span><span><small>Comisión</small><b>${x.commission}%</b></span><span class="status" style="--c:${x.status==='Activo'?'#35d07f':'#ffd23f'}">${x.status}</span><button class="button secondary small" data-collab-edit="${x.id}">Editar</button></article>`).join('')}</div></section>`}
function form(item){const isNew=!item;const x=item||{id:'',name:'',email:'',level:'Aprendiz',commission:10,status:'Activo',birthday:'',joined:new Date().toISOString().slice(0,10)};return `<h2 id="modalTitle">${isNew?'Nuevo colaborador':'Editar colaborador'}</h2><form data-collab-form data-id="${esc(x.id)}"><div class="form-grid"><label>Nombre completo<input name="name" value="${esc(x.name)}" required></label><label>Correo corporativo<input name="email" type="email" value="${esc(x.email)}" required></label><label>Nivel<select name="level">${LEVELS.map(l=>`<option ${l===x.level?'selected':''}>${l}</option>`).join('')}</select></label><label>Comisión (%)<input name="commission" type="number" min="0" max="100" value="${x.commission}" required></label><label>Estado<select name="status"><option ${x.status==='Activo'?'selected':''}>Activo</option><option ${x.status==='Inactivo'?'selected':''}>Inactivo</option></select></label><label>Fecha de ingreso<input name="joined" type="date" value="${x.joined}"></label><label>Fecha de nacimiento<input name="birthday" type="date" value="${x.birthday}"></label><section class="permission-preview"><strong>Permisos del nivel</strong><div data-permission-list>${PERMS[x.level].map(p=>`<span>✓ ${p}</span>`).join('')}</div></section></div><div class="modal-actions">${!isNew&&x.id!=='pablexe'?'<button class="button danger-soft" type="button" data-collab-delete>Eliminar</button>':''}<button class="button secondary" type="button" data-close-modal>Cancelar</button><button class="button primary" type="submit">Guardar</button></div></form>`}
function bind(root){root.querySelector('[data-collab-new]')?.addEventListener('click',()=>open(null));root.querySelectorAll('[data-collab-edit]').forEach(b=>b.onclick=()=>open(rows.find(x=>x.id===b.dataset.collabEdit)))}
function open(item){window.openModal(form(item));const f=document.querySelector('[data-collab-form]');const sel=f.elements.level;sel.onchange=()=>f.querySelector('[data-permission-list]').innerHTML=PERMS[sel.value].map(p=>`<span>✓ ${p}</span>`).join('');f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);const data=Object.fromEntries(fd.entries());data.commission=Number(data.commission);if(item){Object.assign(item,data)}else{data.id=(data.email.split('@')[0]||Date.now().toString()).replace(/[^a-z0-9]/gi,'').toLowerCase();rows.push(data)}save();window.closeModal();window.openModule('colaboradores');window.toast('Colaborador guardado.');};f.querySelector('[data-collab-delete]')?.addEventListener('click',()=>{if(confirm('¿Eliminar este colaborador? Esta acción no se puede deshacer.')){rows=rows.filter(x=>x.id!==item.id);save();window.closeModal();window.openModule('colaboradores');window.toast('Colaborador eliminado.')}})}
window.CVStudioCollaborators={render,bind,levels:LEVELS,permissions:PERMS};
})();
