(function(){
'use strict';
const KEY='cvstudio.sprint1.settings.v1';
const APP_RELEASE={version:'v1.4.39',build:'20260807-home-compacta-final',date:'07/08/2026 · 07:45',name:'Web compacta, demostraciones y precios dinámicos'};
const CHANGELOG=[
 {version:'v1.4.39',date:'07/08/2026',items:['Demostraciones trasladadas debajo de servicios y sin precios superpuestos.','Portfolio uniforme en cuatro tarjetas.','Proceso reducido a una franja compacta de cuatro pasos.','Ventajas renovadas con iconos vectoriales.','Entrega actualizada a 2–4 horas.','Precios exteriores conectados a la configuración comercial.']},
 {version:'v1.4.38',date:'07/08/2026',items:['Servicios y precios trasladados al inicio del recorrido comercial.','Página principal reducida y enfocada en conversión.','Portfolio, proceso, pagos y preguntas compactados.','Vista móvil del proyecto CV corregida.']},
 {version:'v1.4.37',date:'07/08/2026',items:['Administración reorganizada en dos niveles sin perder funciones.','Configuración compactada para mostrar los ocho módulos en una pantalla.','Tarjetas, botones y espacios verticales reajustados.']},
 {version:'v1.4.35',date:'06/08/2026',items:['Comprobación de versión antes de cargar el panel.','URL de rescate independiente de la caché anterior.','Un solo build para HTML, CSS y JavaScript.','Limpieza de Service Workers y cachés residuales.']},
 {version:'v1.3.0',date:'04/08/2026',items:['Versión visible debajo del logo de CVStudio.','Historial de versiones dentro de Estado del Sistema.','Permisos por jerarquía y gestión avanzada de colaboradores.','Generador URL funcional con portfolios existentes y creación de espacios.']},
 {version:'v1.2.0',date:'04/08/2026',items:['Generador URL con Beauty Nails by Eliana y Julieta Ferrari.','Configuración y vista previa de espacios publicados.']},
 {version:'v1.1.0',date:'04/08/2026',items:['Configuración funcional con ocho módulos independientes.','Identidad visual, Open Graph, favicon y recursos de marca.']}
];
const defaults={
 empresa:{nombre:'CVStudio',responsable:'pablexe',dominio:'cvstudio.com.ar',correo:'contacto@cvstudio.com.ar',whatsapp:'',horario:'09:00 a 22:00'},
 ia:{proveedor:'OpenAI',modelo:'GPT-5',estado:'Pendiente',limite:100,asistencia:true},
 estado:{entorno:'Prueba',mantenimiento:false,version:APP_RELEASE.version,sesion:480,logs:true},
 integraciones:{mercadopago:'Conectado',supabase:'Conectado',resend:'Conectado',cloudflare:'Conectado',ga4:'Pendiente',meta:'Pendiente'},
 respaldos:{automaticos:true,frecuencia:'Diario',retencion:30,ultima:'Sin ejecutar'},
 reglas:{empresa:60,colaboradores:20,crecimiento:15,reserva:5,liquidacion:3,alias:'cvstudio.ar'},
 beneficios:{cumpleanos:7,diaLibre:true,capacitacion:true,reconocimiento:true},
 seguridad:{dosFactores:false,contrasenaFuerte:true,intentos:5,inactividad:30,auditoria:true}
};
const clone=o=>JSON.parse(JSON.stringify(o));
function load(){try{return Object.assign(clone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return clone(defaults)}}
let state=load();
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('cvstudio:settings-updated',{detail:clone(state)}));};
const status=v=>`<span class="status" style="--c:${/Conectado|Activo|Producción/.test(v)?'#35d07f':/Pendiente|Prueba/.test(v)?'#ffd23f':'#ff5d73'}">${esc(v)}</span>`;
const cards=[
 ['empresa','🏢','Empresa','Identidad, atención y canales oficiales',()=>[['Responsable',state.empresa.responsable],['Dominio',state.empresa.dominio],['WhatsApp',state.empresa.whatsapp?'Configurado':'Pendiente']]],
 ['ia','🤖','IA','Proveedor, modelo y reglas de asistencia',()=>[['Proveedor',state.ia.proveedor],['Modelo',state.ia.modelo],['Estado',state.ia.estado]]],
 ['estado','📊','Estado del Sistema','Entorno, versión, sesiones y mantenimiento',()=>[['Entorno',state.estado.entorno],['Versión',APP_RELEASE.version],['Mantenimiento',state.estado.mantenimiento?'Activo':'Inactivo']]],
 ['integraciones','🔗','Integraciones','Servicios externos y estado de conexión',()=>[['Mercado Pago',state.integraciones.mercadopago],['Supabase',state.integraciones.supabase],['Meta',state.integraciones.meta]]],
 ['respaldos','🗄','Respaldos','Copias automáticas, frecuencia y retención',()=>[['Automáticos',state.respaldos.automaticos?'Activos':'Inactivos'],['Frecuencia',state.respaldos.frecuencia],['Retención',state.respaldos.retencion+' días']]],
 ['reglas','💰','Reglas Administrativas','Distribución, liquidaciones y cobros',()=>[['Empresa',state.reglas.empresa+'%'],['Colaboradores',state.reglas.colaboradores+'%'],['Liquidación','Día '+state.reglas.liquidacion]]],
 ['beneficios','🎁','Beneficios','Cumpleaños, día libre y reconocimiento',()=>[['Cumpleaños','+'+state.beneficios.cumpleanos+'%'],['Día libre',state.beneficios.diaLibre?'Activo':'Inactivo'],['Capacitación',state.beneficios.capacitacion?'Activa':'Inactiva']]],
 ['seguridad','🛡','Seguridad','Accesos, contraseñas y auditoría',()=>[['2FA',state.seguridad.dosFactores?'Activo':'Pendiente'],['Contraseña fuerte',state.seguridad.contrasenaFuerte?'Activa':'Inactiva'],['Auditoría',state.seguridad.auditoria?'Activa':'Inactiva']]]
];
function render(){
 const alerts=[!state.empresa.whatsapp?'WhatsApp oficial pendiente':null,state.ia.estado==='Pendiente'?'IA pendiente de credenciales':null,!state.seguridad.dosFactores?'2FA recomendado':null].filter(Boolean);
 return `<section class="panel system-status"><div class="health-ring"></div><div><h2>Centro de control</h2><p style="color:var(--muted);margin:5px 0">${APP_RELEASE.name}</p><small>${alerts.length?alerts.length+' revisiones pendientes':'Sin observaciones'}</small></div><div class="system-pills"><div class="system-pill"><small>Sistema</small><strong style="color:var(--green)">Operativo</strong></div><div class="system-pill"><small>Versión</small><strong>${APP_RELEASE.version}</strong></div><div class="system-pill"><small>Respaldos</small><strong>${state.respaldos.automaticos?'Activos':'Manuales'}</strong></div><div class="system-pill"><small>Seguridad</small><strong>${state.seguridad.dosFactores?'Alta':'Estándar'}</strong></div></div><button class="button primary" data-settings-audit>Ejecutar auditoría</button></section><section class="grid settings-grid sprint-settings">${cards.map(c=>`<section class="panel settings-card settings-card-real" data-card="${c[0]}"><div class="settings-card-top"><span class="settings-card-icon">${c[1]}</span><div><h2>${c[2]}</h2><p>${c[3]}</p></div></div><ul>${c[4]().map(r=>`<li><span>${r[0]}</span><strong>${esc(r[1])}</strong></li>`).join('')}</ul><button class="button secondary" style="width:100%;margin-top:12px" data-settings-open="${c[0]}">Configurar ${c[2]}</button></section>`).join('')}</section><section class="settings-version-card"><div><strong>Versión instalada ${APP_RELEASE.version}</strong><small>Build ${APP_RELEASE.build} · Actualizada ${APP_RELEASE.date}</small></div><button class="button secondary" data-version-history>Ver historial de versiones</button></section>`;
}
const input=(n,l,v,t='text')=>`<label>${l}<input name="${n}" type="${t}" value="${esc(v)}"></label>`;
const select=(n,l,v,opts)=>`<label>${l}<select name="${n}">${opts.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select></label>`;
const check=(n,l,v)=>`<label class="settings-check"><input name="${n}" type="checkbox" ${v?'checked':''}><span>${l}</span></label>`;
function modal(id){let f='';const s=state[id];
 if(id==='empresa')f=input('nombre','Nombre comercial',s.nombre)+input('responsable','Responsable',s.responsable)+input('dominio','Dominio',s.dominio)+input('correo','Correo','email' in {}?'email':'text')+input('whatsapp','WhatsApp Business',s.whatsapp,'tel')+input('horario','Horario',s.horario);
 if(id==='ia')f=select('proveedor','Proveedor',s.proveedor,['OpenAI','Anthropic','Google'])+input('modelo','Modelo',s.modelo)+select('estado','Estado',s.estado,['Activo','Pendiente','Desconectado'])+input('limite','Límite mensual',s.limite,'number')+check('asistencia','Asistencia de redacción habilitada',s.asistencia);
 if(id==='estado')f=select('entorno','Entorno',s.entorno,['Prueba','Producción'])+`<label>Versión instalada<input value="${APP_RELEASE.version}" disabled></label><label>Build<input value="${APP_RELEASE.build}" disabled></label>`+input('sesion','Sesión (minutos)',s.sesion,'number')+check('mantenimiento','Modo mantenimiento',s.mantenimiento)+check('logs','Registrar actividad',s.logs)+`<button class="button secondary" type="button" data-version-history style="grid-column:1/-1">Ver historial de versiones</button>`;
 if(id==='integraciones')f=Object.keys(s).map(k=>select(k,k==='ga4'?'Google Analytics 4':k[0].toUpperCase()+k.slice(1),s[k],['Conectado','Pendiente','Desconectado'])).join('');
 if(id==='respaldos')f=check('automaticos','Respaldos automáticos',s.automaticos)+select('frecuencia','Frecuencia',s.frecuencia,['Diario','Semanal','Mensual'])+input('retencion','Retención (días)',s.retencion,'number')+`<label>Último respaldo<input value="${esc(s.ultima)}" disabled></label>`;
 if(id==='reglas')f=input('empresa','Empresa (%)',s.empresa,'number')+input('colaboradores','Colaboradores (%)',s.colaboradores,'number')+input('crecimiento','Fondo crecimiento (%)',s.crecimiento,'number')+input('reserva','Reserva (%)',s.reserva,'number')+input('liquidacion','Día de liquidación',s.liquidacion,'number')+input('alias','Alias de cobro',s.alias);
 if(id==='beneficios')f=input('cumpleanos','Extra cumpleaños (%)',s.cumpleanos,'number')+check('diaLibre','Día libre de cumpleaños',s.diaLibre)+check('capacitacion','Capacitación interna',s.capacitacion)+check('reconocimiento','Reconocimiento por desempeño',s.reconocimiento);
 if(id==='seguridad')f=check('dosFactores','Doble factor',s.dosFactores)+check('contrasenaFuerte','Contraseña fuerte obligatoria',s.contrasenaFuerte)+input('intentos','Intentos antes de bloqueo',s.intentos,'number')+input('inactividad','Expirar por inactividad (días)',s.inactividad,'number')+check('auditoria','Registro de auditoría',s.auditoria);
 return `<h2 id="modalTitle">${cards.find(c=>c[0]===id)[2]}</h2><p style="color:var(--muted)">Componente independiente. Los cambios quedan guardados en este navegador.</p><form data-settings-form="${id}"><div class="form-grid">${f}</div><div class="modal-actions"><button class="button secondary" type="button" data-close-modal>Cancelar</button>${id==='respaldos'?'<button class="button secondary" type="button" data-run-backup>Crear respaldo ahora</button>':''}<button class="button primary" type="submit">Guardar cambios</button></div></form>`;
}
function versionHistory(){window.openModal(`<h2 id="modalTitle">Historial de versiones</h2><p style="color:var(--muted)">Registro de actualizaciones instaladas en el Centro de Operaciones.</p><div class="version-summary"><div><small>Versión actual</small><strong>${APP_RELEASE.version}</strong></div><div><small>Build</small><strong class="build-badge">${APP_RELEASE.build}</strong></div><div><small>Última actualización</small><strong>${APP_RELEASE.date}</strong></div></div><div class="changelog-list">${CHANGELOG.map((r,i)=>`<article class="changelog-entry"><header><strong>${r.version}${i===0?' · Actual':''}</strong><span>${r.date}</span></header><ul>${r.items.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('')}</div><div class="modal-actions"><button class="button primary" data-close-modal>Cerrar</button></div>`)}
function audit(){const rows=[['Empresa',!!state.empresa.dominio,'Dominio y responsable'],['WhatsApp',!!state.empresa.whatsapp,'Canal oficial'],['IA',state.ia.estado==='Activo','Proveedor y modelo'],['Integraciones',Object.values(state.integraciones).filter(v=>v==='Conectado').length>=4,'Servicios esenciales'],['Respaldos',state.respaldos.automaticos,'Copias automáticas'],['Reglas',state.reglas.empresa+state.reglas.colaboradores+state.reglas.crecimiento+state.reglas.reserva===100,'Distribución total 100%'],['Seguridad',state.seguridad.contrasenaFuerte,'Política de acceso']];window.openModal(`<h2 id="modalTitle">Auditoría del sistema</h2><div class="audit-list">${rows.map(r=>`<div class="audit-row"><span class="audit-icon ${r[1]?'ok':'warn'}">${r[1]?'✓':'!'}</span><div><strong>${r[0]}</strong><small>${r[2]}</small></div>${status(r[1]?'Activo':'Revisar')}</div>`).join('')}</div><div class="modal-actions"><button class="button primary" data-close-modal>Cerrar</button></div>`)}
function bind(root){root.querySelectorAll('[data-settings-open]').forEach(b=>b.onclick=()=>{window.openModal(modal(b.dataset.settingsOpen));bindModal()});root.querySelectorAll('[data-version-history]').forEach(b=>b.onclick=versionHistory);const a=root.querySelector('[data-settings-audit]');if(a)a.onclick=audit;}
function bindModal(){document.querySelectorAll('[data-version-history]').forEach(b=>b.onclick=versionHistory);const form=document.querySelector('[data-settings-form]');if(!form)return;const id=form.dataset.settingsForm;const backup=form.querySelector('[data-run-backup]');if(backup)backup.onclick=()=>{state.respaldos.ultima=new Date().toLocaleString('es-AR');save();window.toast('Respaldo local registrado.');window.closeModal();window.openModule('configuracion')};form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);Object.keys(state[id]).forEach(k=>{const el=form.elements[k];if(!el)return;state[id][k]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value.trim()});if(id==='reglas'&&state.reglas.empresa+state.reglas.colaboradores+state.reglas.crecimiento+state.reglas.reserva!==100){window.toast('La distribución debe sumar 100%.');return}save();window.closeModal();window.openModule('configuracion');window.toast('Configuración guardada.')}}
window.CVStudioSettings={render,bind,getState:()=>clone(state),release:APP_RELEASE,versionHistory};
})();
