const API='https://eqepkoegzyqklpxkrkhm.supabase.co/functions/v1/psico-api',KEY='psico-admin-session';let token=sessionStorage.getItem(KEY)||'',data=null,revision=0,tab='general',dirty=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(action,method='GET',body){const r=await fetch(API+'?action='+action,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json();if(!r.ok){if(r.status===401&&action!=='login'){sessionStorage.removeItem(KEY);token='';showLogin()}throw Error(result.error||'No se pudo completar la solicitud.')}return result;}
function showLogin(){$('#workspace').classList.add('hidden');$('#loginPanel').classList.remove('hidden');$('#logout').classList.add('hidden');$('#password').value='';}
function notice(s,error=false){$('#notice').textContent=s;$('#notice').style.color=error?'#942d25':'#123957'}
function markDirty(){dirty=true;$('#dirty').classList.remove('hidden')}
function field(label,path,value,multiline=false,hint=''){return '<div><label>'+esc(label)+'</label>'+(multiline?'<textarea data-path="'+path+'">'+esc(value)+'</textarea>':'<input data-path="'+path+'" value="'+esc(value)+'">')+(hint?'<p class="hint">'+esc(hint)+'</p>':'')+'</div>'}
function render(){let h='';if(tab==='general'){h='<h2>Inicio y marca</h2><p class="hint">Los saltos de línea del título y la frase se respetan en la portada.</p><div class="form-grid">'+field('Título principal','heroTitle',data.heroTitle,true)+field('Texto de presentación','heroText',data.heroText,true)+field('Frase de la portada','heroNote',data.heroNote,true)+field('Sobre nosotros','about',data.about,true)+'</div><h3>Logo original</h3><p class="hint">Cargá el archivo oficial en PNG, JPG o WebP. Se conserva su proporción. Tamaño máximo: 350 KB.</p>'+(data.logo?'<img class="logo-preview" src="'+esc(data.logo)+'" alt="Vista del logo">':'<p class="hint">Todavía no se cargó un logo original.</p>')+'<label for="logoUpload">Seleccionar archivo</label><input id="logoUpload" type="file" accept="image/png,image/jpeg,image/webp">'+field('O pegar un enlace HTTPS al logo','logo',data.logo.startsWith('data:')?'':data.logo,false)+'<button class="btn" id="removeLogo">Quitar logo</button>';}
if(tab==='spaces'){h='<h2>Los cinco espacios</h2><p class="hint">La descripción aparece en la tarjeta. El detalle se abre al pulsar «Ver espacio».</p>'+data.spaces.map((s,i)=>'<article class="item"><h3>Espacio '+(i+1)+'</h3>'+field('Nombre','spaces.'+i+'.title',s.title)+field('Descripción breve','spaces.'+i+'.description',s.description,true)+field('Detalle completo','spaces.'+i+'.detail',s.detail,true)+'</article>').join('')}
if(tab==='episodes'){h='<h2>Podcast y audios</h2>'+field('Presentación del podcast','podcastIntro',data.podcastIntro,true)+'<p class="hint">Pegá un enlace HTTPS directo a un archivo de audio. La portada es opcional. Los primeros tres episodios se muestran en la página principal.</p>'+data.episodes.map((ep,i)=>'<article class="item"><div class="item-controls"><h3>Episodio '+(i+1)+'</h3><button class="btn danger" data-remove="episodes.'+i+'">Quitar episodio</button></div>'+field('Título','episodes.'+i+'.title',ep.title)+field('Enlace al audio','episodes.'+i+'.url',ep.url,false,'Ejemplo: https://…/episodio.mp3')+field('Enlace a la portada','episodes.'+i+'.cover',ep.cover)+'</article>').join('')+'<button class="btn" data-add="episodes">+ Agregar episodio</button>'}
if(tab==='articles'){h='<h2>Artículos y recursos</h2><p class="hint">Los artículos se publican en «Explorar contenido».</p>'+data.articles.map((a,i)=>'<article class="item"><div class="item-controls"><h3>Artículo '+(i+1)+'</h3><button class="btn danger" data-remove="articles.'+i+'">Quitar artículo</button></div>'+field('Título','articles.'+i+'.title',a.title)+field('Contenido','articles.'+i+'.body',a.body,true)+'</article>').join('')+'<button class="btn" data-add="articles">+ Agregar artículo</button>'}
if(tab==='membership'){h='<h2>Comunidad y suscripción</h2>'+field('Presentación y beneficios','membershipText',data.membershipText,true)+'<p class="hint">Este panel administra el contenido editorial. El registro público, los cobros y las suscripciones de miembros se incorporarán cuando se definan sus condiciones.</p>'}
$('#editor').innerHTML=h;$('#logoUpload')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>350000||!['image/png','image/jpeg','image/webp'].includes(file.type)){notice('Usá PNG, JPG o WebP de hasta 350 KB.',true);return}const reader=new FileReader();reader.onload=()=>{data.logo=reader.result;markDirty();render();notice('Logo preparado. Guardá y publicá para verlo en la web.')};reader.readAsDataURL(file)});$('#removeLogo')?.addEventListener('click',()=>{data.logo='';markDirty();render()});}
async function load(){try{const r=await request('admin');data=r.content;revision=r.revision;dirty=false;$('#dirty').classList.add('hidden');$('#loginPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#logout').classList.remove('hidden');render();notice('Sesión de '+r.username+' · Última actualización: '+new Date(r.updated_at).toLocaleString('es-AR'));}catch(e){if(token)notice(e.message,true);else $('#loginMessage').textContent=e.message;}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginButton').disabled=true;$('#loginMessage').textContent='Verificando acceso…';try{const r=await request('login','POST',{username:$('#username').value.trim(),password:$('#password').value});token=r.token;sessionStorage.setItem(KEY,token);$('#password').value='';await load()}catch(err){$('#loginMessage').textContent=err.message;$('#loginMessage').className='message error';}finally{$('#loginButton').disabled=false}});
$('#showPass').addEventListener('click',()=>{const show=$('#password').type==='password';$('#password').type=show?'text':'password';$('#showPass').textContent=show?'Ocultar':'Mostrar'});
$('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#editor').addEventListener('input',e=>{const path=e.target.dataset.path;if(!path)return;const keys=path.split('.');let v=data;for(const k of keys.slice(0,-1))v=v[k];v[keys.at(-1)]=e.target.value;markDirty()});
$('#editor').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add){const list=b.dataset.add;if(data[list].length>=40){notice('El límite es de 40 publicaciones por sección.',true);return}data[list].push(list==='episodes'?{title:'Nuevo episodio',url:'',cover:''}:{title:'Nuevo artículo',body:''});markDirty();render()}if(b.dataset.remove){const [list,i]=b.dataset.remove.split('.');if(!confirm('¿Quitar esta publicación? El cambio se aplica al guardar.'))return;data[list].splice(Number(i),1);markDirty();render()}});
async function save(){document.querySelectorAll('.save').forEach(b=>b.disabled=true);notice('Guardando y publicando…');try{const r=await request('content','PUT',{content:data,revision});revision=r.revision;dirty=false;$('#dirty').classList.add('hidden');notice('Cambios publicados. Recargá la web para ver la actualización.')}catch(e){notice(e.message,true)}finally{document.querySelectorAll('.save').forEach(b=>b.disabled=false)}}
document.querySelectorAll('.save').forEach(b=>b.addEventListener('click',save));$('#reload').addEventListener('click',()=>{if(dirty&&!confirm('¿Descartar los cambios sin guardar y recargar?'))return;load()});$('#logout').addEventListener('click',async()=>{if(dirty&&!confirm('Tenés cambios sin guardar. ¿Cerrar sesión?'))return;try{await request('logout','POST')}catch{}sessionStorage.removeItem(KEY);token='';data=null;dirty=false;showLogin()});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});if(token)load();
