(()=>{'use strict';const API='https://cvstudio-contacto.cvpro-duccionesar.workers.dev';const token=new URLSearchParams(location.search).get('token')||'';const $=id=>document.getElementById(id);const loading=$('loading'),error=$('error'),form=$('signatureForm'),success=$('success'),canvas=$('signatureCanvas'),ctx=canvas.getContext('2d');let drawing=false,hasInk=false,last=null;
async function call(action,payload={}){const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok)throw new Error(data.message||'No se pudo completar la operación.');return data}
function fail(message){loading.hidden=true;form.hidden=true;error.hidden=false;error.textContent=message}
function resize(){const box=canvas.getBoundingClientRect(),ratio=Math.max(1,devicePixelRatio||1);canvas.width=Math.round(box.width*ratio);canvas.height=Math.round(box.height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=3;ctx.strokeStyle='#071b3b'}
function point(event){const r=canvas.getBoundingClientRect(),p=event.touches?.[0]||event.changedTouches?.[0]||event;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function start(e){e.preventDefault();drawing=true;last=point(e)}function move(e){if(!drawing)return;e.preventDefault();const p=point(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;hasInk=true}function end(e){if(drawing)e.preventDefault();drawing=false;last=null}
['pointerdown','touchstart'].forEach(n=>canvas.addEventListener(n,start,{passive:false}));['pointermove','touchmove'].forEach(n=>canvas.addEventListener(n,move,{passive:false}));['pointerup','pointercancel','pointerleave','touchend','touchcancel'].forEach(n=>canvas.addEventListener(n,end,{passive:false}));
function clear(){ctx.clearRect(0,0,canvas.width,canvas.height);hasInk=false}$('clearSignature').onclick=clear;
function trimmedPng(){const source=ctx.getImageData(0,0,canvas.width,canvas.height),d=source.data,w=source.width,h=source.height;let minX=w,minY=h,maxX=-1,maxY=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>12){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(maxX<0)throw new Error('Primero dibujá tu firma.');const pad=Math.round(18*(devicePixelRatio||1)),x=Math.max(0,minX-pad),y=Math.max(0,minY-pad),cw=Math.min(w-x,maxX-minX+1+pad*2),ch=Math.min(h-y,maxY-minY+1+pad*2),out=document.createElement('canvas');out.width=cw;out.height=ch;out.getContext('2d').putImageData(ctx.getImageData(x,y,cw,ch),0,0);return out.toDataURL('image/png')}
form.addEventListener('submit',async e=>{e.preventDefault();if(!hasInk)return fail('Primero dibujá tu firma.');if(!$('consent').checked)return fail('Necesitamos que aceptes las condiciones de uso.');const button=$('submitSignature');button.disabled=true;button.textContent='Enviando…';try{await call('signature-public-submit',{token,consent:true,signature:trimmedPng()});form.hidden=true;error.hidden=true;success.hidden=false;setTimeout(()=>location.href='https://cvstudio.com.ar/',4500)}catch(err){button.disabled=false;button.textContent='Enviar firma';fail(err.message)}});
(async()=>{if(!token)return fail('El enlace de firma no es válido.');try{const data=await call('signature-public-get',{token});$('recipient').textContent=`${data.clientName}, esta solicitud corresponde a tu ${String(data.documentName||'carta de presentación').toLowerCase()}.`;loading.hidden=true;form.hidden=false;requestAnimationFrame(resize)}catch(err){fail(err.message)}})();
})();
